### ISSUE TITLE
Cannot create managed node group - subnet conflict

### ISSUE THREAD

**Issue by karrth** [weaveworks/eksctl#4042] opened 2021-08-02 17:12 UTC
**What were you trying to accomplish?**
I am trying to create a new managed node group for a cluster, while there is one other existing un-managed node group.  I am able to successfully make new un-managed node groups on this cluster.

**What happened?**
Same as documented here:
https://github.com/weaveworks/eksctl/issues/2176

eksctl complains about a duplicate subnet

**How to reproduce it?**
* eksctl version 0.58.0
* region ap-southeast-2
* eks version 1.21

The yaml for the new node group:
```
managedNodeGroups:
  - name: standard-workers-1
    instanceType: m5.2xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 16
    privateNetworking: true
```

The old, already created group:
```
nodeGroups:
  - name: standard-workers-6
    instanceType: m5.2xlarge
    tags: {
      k8s.io/cluster-autoscaler/stage-apps-cluster-nz: "owned",
      k8s.io/cluster-autoscaler/enabled: "true"
    }
    ami: "auto"
    desiredCapacity: 1
    minSize: 1
    maxSize: 16
    privateNetworking: true
```

I am running the following command:
`eksctl create nodegroup --config-file cluster.yaml `, where `cluster.yaml` contains both configs listed above, as well as other cluster information.

I recently did this same thing for 6 other clusters without issue, I'm not sure what is special about this one.

**Logs**
I do have a `-v 4` debug log, here's the bit where it tries to create the cluster.  Let me know if you want the whole thing:
```
2021-08-02 10:47:12 [ℹ]  1 nodegroup (standard-workers-1) was included (based on the include/exclude rules)
2021-08-02 10:47:12 [ℹ]  will create a CloudFormation stack for each of 1 managed nodegroups in cluster "stage-apps-cluster-nz"
2021-08-02 10:47:13 [▶]  found following policies attached to role annotated on aws-node service account: [{
  PolicyArn: "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy",
  PolicyName: "AmazonEKS_CNI_Policy"
}]
2021-08-02 10:47:13 [ℹ]  2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create managed nodegroup "standard-workers-1" } } }
2021-08-02 10:47:13 [▶]  started task: fix cluster compatibility
2021-08-02 10:47:13 [ℹ]  checking cluster stack for missing resources
2021-08-02 10:47:17 [ℹ]  cluster stack has all required resources
2021-08-02 10:47:17 [▶]  completed task: fix cluster compatibility
2021-08-02 10:47:17 [▶]  started task: 1 task: { 1 task: { create managed nodegroup "standard-workers-1" } }
2021-08-02 10:47:17 [▶]  waiting for 1 parallel tasks to complete
2021-08-02 10:47:17 [▶]  started task: 1 task: { create managed nodegroup "standard-workers-1" }
2021-08-02 10:47:17 [▶]  waiting for 1 parallel tasks to complete
2021-08-02 10:47:17 [▶]  started task: create managed nodegroup "standard-workers-1"
2021-08-02 10:47:17 [ℹ]  building managed nodegroup stack "eksctl-stage-apps-cluster-nz-nodegroup-standard-workers-1"
2021-08-02 10:47:17 [▶]  CreateStackInput = {
  Capabilities: ["CAPABILITY_IAM"],
  DisableRollback: false,
  StackName: "eksctl-stage-apps-cluster-nz-nodegroup-standard-workers-1",
  Tags: [
    {
      Key: "alpha.eksctl.io/cluster-name",
      Value: "stage-apps-cluster-nz"
    },
    {
      Key: "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
      Value: "stage-apps-cluster-nz"
    },
    {
      Key: "alpha.eksctl.io/eksctl-version",
      Value: "0.58.0"
    },
    {
      Key: "alpha.eksctl.io/nodegroup-name",
      Value: "standard-workers-1"
    },
    {
      Key: "alpha.eksctl.io/nodegroup-type",
      Value: "managed"
    }
  ],
  TemplateBody: "{\n  \"AWSTemplateFormatVersion\": \"2010-09-09\",\n  \"Description\": \"EKS Managed Nodes (SSH access: false) [created by eksctl]\",\n  \"Mappings\": {\n    \"ServicePrincipalPartitionMap\": {\n      \"aws\": {\n        \"EC2\": \"ec2.amazonaws.com\",\n        \"EKS\": \"eks.amazonaws.com\",\n        \"EKSFargatePods\": \"eks-fargate-pods.amazonaws.com\"\n      },\n      \"aws-cn\": {\n        \"EC2\": \"ec2.amazonaws.com.cn\",\n        \"EKS\": \"eks.amazonaws.com\",\n        \"EKSFargatePods\": \"eks-fargate-pods.amazonaws.com\"\n      },\n      \"aws-us-gov\": {\n        \"EC2\": \"ec2.amazonaws.com\",\n        \"EKS\": \"eks.amazonaws.com\",\n        \"EKSFargatePods\": \"eks-fargate-pods.amazonaws.com\"\n      }\n    }\n  },\n  \"Resources\": {\n    \"LaunchTemplate\": {\n      \"Type\": \"AWS::EC2::LaunchTemplate\",\n      \"Properties\": {\n        \"LaunchTemplateData\": {\n          \"BlockDeviceMappings\": [\n            {\n              \"DeviceName\": \"/dev/xvda\",\n              \"Ebs\": {\n                \"Iops\": 3000,\n                \"Throughput\": 125,\n                \"VolumeSize\": 80,\n                \"VolumeType\": \"gp3\"\n              }\n            }\n          ],\n          \"MetadataOptions\": {\n            \"HttpPutResponseHopLimit\": 2,\n            \"HttpTokens\": \"optional\"\n          },\n          \"SecurityGroupIds\": [\n            {\n              \"Fn::ImportValue\": \"eksctl-stage-apps-cluster-nz-cluster::ClusterSecurityGroupId\"\n            }\n          ],\n          \"TagSpecifications\": [\n            {\n              \"ResourceType\": \"instance\",\n              \"Tags\": [\n                {\n                  \"Key\": \"Name\",\n                  \"Value\": \"stage-apps-cluster-nz-standard-workers-1-Node\"\n                },\n                {\n                  \"Key\": \"alpha.eksctl.io/nodegroup-name\",\n                  \"Value\": \"standard-workers-1\"\n                },\n                {\n                  \"Key\": \"alpha.eksctl.io/nodegroup-type\",\n                  \"Value\": \"managed\"\n                }\n              ]\n            },\n            {\n              \"ResourceType\": \"volume\",\n              \"Tags\": [\n                {\n                  \"Key\": \"Name\",\n                  \"Value\": \"stage-apps-cluster-nz-standard-workers-1-Node\"\n                },\n                {\n                  \"Key\": \"alpha.eksctl.io/nodegroup-name\",\n                  \"Value\": \"standard-workers-1\"\n                },\n                {\n                  \"Key\": \"alpha.eksctl.io/nodegroup-type\",\n                  \"Value\": \"managed\"\n                }\n              ]\n            },\n            {\n              \"ResourceType\": \"network-interface\",\n              \"Tags\": [\n                {\n                  \"Key\": \"Name\",\n                  \"Value\": \"stage-apps-cluster-nz-standard-workers-1-Node\"\n                },\n                {\n                  \"Key\": \"alpha.eksctl.io/nodegroup-name\",\n                  \"Value\": \"standard-workers-1\"\n                },\n                {\n                  \"Key\": \"alpha.eksctl.io/nodegroup-type\",\n                  \"Value\": \"managed\"\n                }\n              ]\n            }\n          ]\n        },\n        \"LaunchTemplateName\": {\n          \"Fn::Sub\": \"${AWS::StackName}\"\n        }\n      }\n    },\n    \"ManagedNodeGroup\": {\n      \"Type\": \"AWS::EKS::Nodegroup\",\n      \"Properties\": {\n        \"AmiType\": \"AL2_x86_64\",\n        \"ClusterName\": \"stage-apps-cluster-nz\",\n        \"InstanceTypes\": [\n          \"m5.2xlarge\"\n        ],\n        \"Labels\": {\n          \"alpha.eksctl.io/cluster-name\": \"stage-apps-cluster-nz\",\n          \"alpha.eksctl.io/nodegroup-name\": \"standard-workers-1\"\n        },\n        \"LaunchTemplate\": {\n          \"Id\": {\n            \"Ref\": \"LaunchTemplate\"\n          }\n        },\n        \"NodeRole\": {\n          \"Fn::GetAtt\": [\n            \"NodeInstanceRole\",\n            \"Arn\"\n          ]\n        },\n        \"NodegroupName\": \"standard-workers-1\",\n        \"ScalingConfig\": {\n          \"DesiredSize\": 1,\n          \"MaxSize\": 16,\n          \"MinSize\": 1\n        },\n        \"Subnets\": {\n          \"Fn::Split\": [\n            \",\",\n            {\n              \"Fn::ImportValue\": \"eksctl-stage-apps-cluster-nz-cluster::SubnetsPrivate\"\n            }\n          ]\n        },\n        \"Tags\": {\n          \"alpha.eksctl.io/nodegroup-name\": \"standard-workers-1\",\n          \"alpha.eksctl.io/nodegroup-type\": \"managed\"\n        }\n      }\n    },\n    \"NodeInstanceRole\": {\n      \"Type\": \"AWS::IAM::Role\",\n      \"Properties\": {\n        \"AssumeRolePolicyDocument\": {\n          \"Statement\": [\n            {\n              \"Action\": [\n                \"sts:AssumeRole\"\n              ],\n              \"Effect\": \"Allow\",\n              \"Principal\": {\n                \"Service\": [\n                  {\n                    \"Fn::FindInMap\": [\n                      \"ServicePrincipalPartitionMap\",\n                      {\n                        \"Ref\": \"AWS::Partition\"\n                      },\n                      \"EC2\"\n                    ]\n                  }\n                ]\n              }\n            }\n          ],\n          \"Version\": \"2012-10-17\"\n        },\n        \"ManagedPolicyArns\": [\n          \"arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy\",\n          \"arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy\",\n          \"arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly\",\n          \"arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess\",\n          \"arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore\"\n        ],\n        \"Path\": \"/\",\n        \"Tags\": [\n          {\n            \"Key\": \"Name\",\n            \"Value\": {\n              \"Fn::Sub\": \"${AWS::StackName}/NodeInstanceRole\"\n            }\n          }\n        ]\n      }\n    }\n  }\n}"
}
2021-08-02 10:47:17 [ℹ]  deploying stack "eksctl-stage-apps-cluster-nz-nodegroup-standard-workers-1"
2021-08-02 10:47:17 [▶]  start waiting for CloudFormation stack "eksctl-stage-apps-cluster-nz-nodegroup-standard-workers-1"
2021-08-02 10:47:17 [ℹ]  waiting for CloudFormation stack "eksctl-stage-apps-cluster-nz-nodegroup-standard-workers-1"
2021-08-02 10:47:34 [ℹ]  waiting for CloudFormation stack "eksctl-stage-apps-cluster-nz-nodegroup-standard-workers-1"
2021-08-02 10:47:51 [ℹ]  waiting for CloudFormation stack "eksctl-stage-apps-cluster-nz-nodegroup-standard-workers-1"
2021-08-02 10:48:12 [ℹ]  waiting for CloudFormation stack "eksctl-stage-apps-cluster-nz-nodegroup-standard-workers-1"
2021-08-02 10:48:13 [✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-stage-apps-cluster-nz-nodegroup-standard-workers-1"
2021-08-02 10:48:13 [ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
2021-08-02 10:48:13 [▶]  AWS::CloudFormation::Stack/eksctl-stage-apps-cluster-nz-nodegroup-standard-workers-1: ROLLBACK_IN_PROGRESS – "The following resource(s) failed to create: [ManagedNodeGroup]. Rollback requested by user."
2021-08-02 10:48:13 [✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "One or more subnets are duplicate (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 50f54b82-4de8-4053-a7cd-2b931230a4bc; Proxy: null)"
```

**Anything else we need to know?**
PopOS, binary version of eksctl

**Versions**
```
eksctl version: 0.58.0
kubectl version: v1.20.8
OS: linux
```

**Comment by karrth** [comment] 2021-08-02 17:37
I have this happening with a second cluster now - both are in `ap-southeast-2`.  I'll configure digging into config for other commonalities.

**Comment by karrth** [comment] 2021-08-13 15:18
I was able to get around this by specifying the subnets specifically in the nodegroup definition:
```
managedNodeGroups:
  - name: standard-workers-10
    instanceType: m5.2xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 16
    privateNetworking: true
    subnets:
      - subnet-x
      - subnet-y
      - subnet-z
```

Which were the same subnets defined in the cluster config, like so:
```
vpc:
  id: vpc-x
  subnets:
    private:
      PrivateSubnetA:
        id: subnet-x
      PrivateSubnetB:
        id: subnet-y
      PrivateSubnetC:
        id: subnet-z
```

**Comment by aclevername** [comment] 2021-08-16 12:10
Thanks for opening he issue @karrth . Can you post a snippet of the cloudformation stack that failed to deploy? Similar to https://github.com/weaveworks/eksctl/issues/2176#issuecomment-635367555 . Also following on questions raised in the previouis issue, is this cluster a new cluster, or one thats gone through many upgrades & eksctl versions?

 I will also attempt to reproduce.

**Comment by aclevername** [comment] 2021-08-16 12:31
Also can you confirm that this is what your VPC setup looks like @karrth ?
```
vpc:
  id: vpc-x
  subnets:
    private:
      PrivateSubnetA:
        id: subnet-x
      PrivateSubnetB:
        id: subnet-y
      PrivateSubnetC:
        id: subnet-z
```

No more additional subnets or public subnets?

**Comment by aclevername** [comment] 2021-08-16 16:15
@karrth I've tried to reproduce this with no luck. My current theory is that there was a regression is some previous version of eksctl that got fixed. This regression must of broken the way in which we form the `outputs` of the CloudFormation stack, causing its `Subnets` output to contain duplicate entries. Until we get more information I suggest you continue to specify the subnets for each nodegroup in this cluster, to prevent the error from occurring.

**Comment by karrth** [comment] 2021-08-23 16:21
Sorry for the delay, I was out on vacation :)

> Also can you confirm that this is what your VPC setup looks like @karrth ?
> 
> ```
> vpc:
>   id: vpc-x
>   subnets:
>     private:
>       PrivateSubnetA:
>         id: subnet-x
>       PrivateSubnetB:
>         id: subnet-y
>       PrivateSubnetC:
>         id: subnet-z
> ```
> 
> No more additional subnets or public subnets?

There are also 3 public subnets in these clusters.

> Thanks for opening he issue @karrth . Can you post a snippet of the cloudformation stack that failed to deploy? Similar to [#2176 (comment)](https://github.com/weaveworks/eksctl/issues/2176#issuecomment-635367555) . Also following on questions raised in the previouis issue, is this cluster a new cluster, or one thats gone through many upgrades & eksctl versions?
> 
> I will also attempt to reproduce.

I believe this is the part of the cloudformation template you want:
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "EKS Managed Nodes (SSH access: false) [created by eksctl]",
  "Resources": {
    "ManagedNodeGroup": {
      "Type": "AWS::EKS::Nodegroup",
      "Properties": {
        "Subnets": {
          "Fn::Split": [
            ",",
            {
              "Fn::ImportValue": "eksctl-stage-apps-cluster-nz-cluster::SubnetsPrivate"
            }
          ]
        },
      }
    },
  }
}
```



> @karrth I've tried to reproduce this with no luck. My current theory is that there was a regression is some previous version of eksctl that got fixed. This regression must of broken the way in which we form the `outputs` of the CloudFormation stack, causing its `Subnets` output to contain duplicate entries. Until we get more information I suggest you continue to specify the subnets for each nodegroup in this cluster, to prevent the error from occurring.

That sounds like a plausible explanation.  Let me know if there is any further information I can gather on the issue.

**Comment by aclevername** [comment] 2021-09-14 08:38
Thanks for the extra information @karrth . Can you provide the cloudformation template from the cluster stack? I want to see what outputs it has, as well as how the template specified those outputs. Thanks

**Comment by karrth** [comment] 2021-09-14 18:09
In diffing the template with a cluster not experiencing this problem, I only saw differences in the VPC/subnet IDs.  The number of subnet IDs in the cluster listed below was surprising though, considering it should have the same number as the one I was diffing against.

Cloudformation template:
```
{
  "Mappings": {
    "ServicePrincipalPartitionMap": {
      "aws": {
        "EC2": "ec2.amazonaws.com",
        "EKS": "eks.amazonaws.com",
        "EKSFargatePods": "eks-fargate-pods.amazonaws.com"
      },
      "aws-cn": {
        "EC2": "ec2.amazonaws.com.cn",
        "EKS": "eks.amazonaws.com",
        "EKSFargatePods": "eks-fargate-pods.amazonaws.com"
      },
      "aws-us-gov": {
        "EC2": "ec2.amazonaws.com",
        "EKS": "eks.amazonaws.com",
        "EKSFargatePods": "eks-fargate-pods.amazonaws.com"
      }
    }
  },
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "EKS cluster (dedicated VPC: false, dedicated IAM: true) [created and managed by eksctl]",
  "Resources": {
    "PolicyELBPermissions": {
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Action": [
                "ec2:DescribeAccountAttributes"
              ],
              "Effect": "Allow",
              "Resource": "*"
            }
          ],
          "Version": "2012-10-17"
        },
        "PolicyName": {
          "Fn::Sub": "${AWS::StackName}-PolicyELBPermissions"
        },
        "Roles": [
          {
            "Ref": "ServiceRole"
          }
        ]
      },
      "Type": "AWS::IAM::Policy"
    },
    "IngressNodeToDefaultClusterSG": {
      "Properties": {
        "Description": "Allow unmanaged nodes to communicate with control plane (all ports)",
        "FromPort": 0,
        "GroupId": {
          "Fn::GetAtt": "ControlPlane.ClusterSecurityGroupId"
        },
        "IpProtocol": "-1",
        "SourceSecurityGroupId": {
          "Ref": "ClusterSharedNodeSecurityGroup"
        },
        "ToPort": 65535
      },
      "Type": "AWS::EC2::SecurityGroupIngress"
    },
    "IngressDefaultClusterToNodeSG": {
      "Properties": {
        "Description": "Allow managed and unmanaged nodes to communicate with each other (all ports)",
        "FromPort": 0,
        "GroupId": {
          "Ref": "ClusterSharedNodeSecurityGroup"
        },
        "IpProtocol": "-1",
        "SourceSecurityGroupId": {
          "Fn::GetAtt": "ControlPlane.ClusterSecurityGroupId"
        },
        "ToPort": 65535
      },
      "Type": "AWS::EC2::SecurityGroupIngress"
    },
    "ClusterSharedNodeSecurityGroup": {
      "Type": "AWS::EC2::SecurityGroup",
      "Properties": {
        "GroupDescription": "Communication between all nodes in the cluster",
        "Tags": [
          {
            "Key": "Name",
            "Value": {
              "Fn::Sub": "${AWS::StackName}/ClusterSharedNodeSecurityGroup"
            }
          }
        ],
        "VpcId": "vpc-02756f8de7ec76d84"
      }
    },
    "ControlPlane": {
      "Type": "AWS::EKS::Cluster",
      "Properties": {
        "Name": "stage-apps-cluster-nz",
        "ResourcesVpcConfig": {
          "SecurityGroupIds": [
            {
              "Ref": "ControlPlaneSecurityGroup"
            }
          ],
          "SubnetIds": [
            "subnet-0080d324320a8936e",
            "subnet-09f32a797eac041c7",
            "subnet-0080d324320a8936e",
            "subnet-09f32a797eac041c7",
            "subnet-073213e9c11e99713",
            "subnet-073213e9c11e99713",
            "subnet-03684ef35fd2ddbf7",
            "subnet-00c0421d0dc9db8c8",
            "subnet-03684ef35fd2ddbf7",
            "subnet-0db97bb950a2d95d9",
            "subnet-00c0421d0dc9db8c8",
            "subnet-0db97bb950a2d95d9"
          ]
        },
        "RoleArn": {
          "Fn::GetAtt": "ServiceRole.Arn"
        },
        "Version": "1.14"
      }
    },
    "ControlPlaneSecurityGroup": {
      "Type": "AWS::EC2::SecurityGroup",
      "Properties": {
        "GroupDescription": "Communication between the control plane and worker nodegroups",
        "Tags": [
          {
            "Key": "Name",
            "Value": {
              "Fn::Sub": "${AWS::StackName}/ControlPlaneSecurityGroup"
            }
          }
        ],
        "VpcId": "vpc-02756f8de7ec76d84"
      }
    },
    "IngressInterNodeGroupSG": {
      "Type": "AWS::EC2::SecurityGroupIngress",
      "Properties": {
        "Description": "Allow nodes to communicate with each other (all ports)",
        "FromPort": 0,
        "GroupId": {
          "Ref": "ClusterSharedNodeSecurityGroup"
        },
        "IpProtocol": "-1",
        "SourceSecurityGroupId": {
          "Ref": "ClusterSharedNodeSecurityGroup"
        },
        "ToPort": 65535
      }
    },
    "PolicyCloudWatchMetrics": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Action": [
                "cloudwatch:PutMetricData"
              ],
              "Effect": "Allow",
              "Resource": "*"
            }
          ],
          "Version": "2012-10-17"
        },
        "PolicyName": {
          "Fn::Sub": "${AWS::StackName}-PolicyCloudWatchMetrics"
        },
        "Roles": [
          {
            "Ref": "ServiceRole"
          }
        ]
      }
    },
    "PolicyNLB": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Action": [
                "elasticloadbalancing:*",
                "ec2:CreateSecurityGroup",
                "ec2:Describe*"
              ],
              "Effect": "Allow",
              "Resource": "*"
            }
          ],
          "Version": "2012-10-17"
        },
        "PolicyName": {
          "Fn::Sub": "${AWS::StackName}-PolicyNLB"
        },
        "Roles": [
          {
            "Ref": "ServiceRole"
          }
        ]
      }
    },
    "ServiceRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "eks.amazonaws.com"
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          "arn:aws:iam::aws:policy/AmazonEKSServicePolicy",
          "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
        ]
      }
    }
  },
  "Outputs": {
    "ClusterSecurityGroupId": {
      "Export": {
        "Name": {
          "Fn::Sub": "${AWS::StackName}::ClusterSecurityGroupId"
        }
      },
      "Value": {
        "Fn::GetAtt": "ControlPlane.ClusterSecurityGroupId"
      }
    },
    "ARN": {
      "Export": {
        "Name": {
          "Fn::Sub": "${AWS::StackName}::ARN"
        }
      },
      "Value": {
        "Fn::GetAtt": "ControlPlane.Arn"
      }
    },
    "CertificateAuthorityData": {
      "Value": {
        "Fn::GetAtt": "ControlPlane.CertificateAuthorityData"
      }
    },
    "ClusterStackName": {
      "Value": {
        "Ref": "AWS::StackName"
      }
    },
    "Endpoint": {
      "Export": {
        "Name": {
          "Fn::Sub": "${AWS::StackName}::Endpoint"
        }
      },
      "Value": {
        "Fn::GetAtt": "ControlPlane.Endpoint"
      }
    },
    "FeatureNATMode": {
      "Value": "Disable"
    },
    "SecurityGroup": {
      "Export": {
        "Name": {
          "Fn::Sub": "${AWS::StackName}::SecurityGroup"
        }
      },
      "Value": {
        "Ref": "ControlPlaneSecurityGroup"
      }
    },
    "ServiceRoleARN": {
      "Export": {
        "Name": {
          "Fn::Sub": "${AWS::StackName}::ServiceRoleARN"
        }
      },
      "Value": {
        "Fn::GetAtt": "ServiceRole.Arn"
      }
    },
    "SharedNodeSecurityGroup": {
      "Export": {
        "Name": {
          "Fn::Sub": "${AWS::StackName}::SharedNodeSecurityGroup"
        }
      },
      "Value": {
        "Ref": "ClusterSharedNodeSecurityGroup"
      }
    },
    "SubnetsPrivate": {
      "Export": {
        "Name": {
          "Fn::Sub": "${AWS::StackName}::SubnetsPrivate"
        }
      },
      "Value": {
        "Fn::Join": [
          ",",
          [
            "subnet-0080d324320a8936e",
            "subnet-09f32a797eac041c7",
            "subnet-0080d324320a8936e",
            "subnet-09f32a797eac041c7",
            "subnet-073213e9c11e99713",
            "subnet-073213e9c11e99713"
          ]
        ]
      }
    },
    "SubnetsPublic": {
      "Export": {
        "Name": {
          "Fn::Sub": "${AWS::StackName}::SubnetsPublic"
        }
      },
      "Value": {
        "Fn::Join": [
          ",",
          [
            "subnet-03684ef35fd2ddbf7",
            "subnet-00c0421d0dc9db8c8",
            "subnet-03684ef35fd2ddbf7",
            "subnet-0db97bb950a2d95d9",
            "subnet-00c0421d0dc9db8c8",
            "subnet-0db97bb950a2d95d9"
          ]
        ]
      }
    },
    "VPC": {
      "Export": {
        "Name": {
          "Fn::Sub": "${AWS::StackName}::VPC"
        }
      },
      "Value": "vpc-02756f8de7ec76d84"
    }
  }
}
```
Relevant (current) cluster config:
```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: stage-apps-cluster-nz
  region: ap-southeast-2
  version: "1.21"

vpc:
  id: vpc-02756f8de7ec76d84
  subnets:
    private:
      PrivateSubnetA:
        id: subnet-0080d324320a8936e
      PrivateSubnetB:
        id: subnet-09f32a797eac041c7
      PrivateSubnetC:
        id: subnet-073213e9c11e99713
    public:
      PublicSubnetA:
        id: subnet-03684ef35fd2ddbf7
      PublicSubnetB:
        id: subnet-0db97bb950a2d95d9
      PublicSubnetC:
        id: subnet-00c0421d0dc9db8c8

managedNodeGroups:
  - name: standard-workers-11
    instanceType: m5.2xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 16
    privateNetworking: true
    subnets:
      - subnet-0080d324320a8936e
      - subnet-09f32a797eac041c7
      - subnet-073213e9c11e99713
```

**Comment by aclevername** [comment] 2021-09-16 15:22
Thanks @karrth . I still haven't managed to reproduce this, so my theory of this being a temporary regression in a previous version of eksctl that got fixed seems likely. 

Are you happy to continue to specifying the subnets for each nodegroup in this cluster as a workaround?

An alternative would be to manually edit the stack, to remove the duplicate subnet outputs. However this is obviously a bit hacky (I've never edited a stack post-creation manaually), and I haven't tested it so I wouldn't recommend unless you really have to (and would try on a test cluster first). Sorry I couldn't be of more help.

**Comment by karrth** [comment] 2021-09-16 16:08
We can continue specifying the subnets for now.  I expect we're going to rebuild these clusters in the semi-near future.  We've at least documented the problem and a workaround for others to find.  I'll take a gander at editing the stack and see if that resolves the issue in our testing environment.

**Comment by aclevername** [comment] 2021-09-20 11:07
> We can continue specifying the subnets for now. I expect we're going to rebuild these clusters in the semi-near future. We've at least documented the problem and a workaround for others to find. I'll take a gander at editing the stack and see if that resolves the issue in our testing environment.

Thanks @karrth. I'm going to close this issue for now, feel free to re-open if needed :smile:

**Closed by aclevername** 2021-09-20 11:07 UTC
Labels: kind/bug
