### ISSUE TITLE
eksctl refuses to upgrade nodegroup it created

### ISSUE THREAD

**Issue by flybd5** [weaveworks/eksctl#3849] opened 2021-06-15 03:49 UTC
**What were you trying to accomplish?**

Upgrade my nodegroup. The one I originally created was using instances that were too big, so i created this nodegroup-smaller nodegroup with three smaller instances and deleted the first one. When I list the nodegroups with eksctl it shows up but it doesn't show up on the EKS cluster page on aws. The nodes have no nodegroup. Now I tried to upgrade the nodes using the nodegroup name like this:

`eksctl upgrade nodegroup --cluster rancher-server -r us-east-2 --name nodegroup-smaller`

...and I get this error:

`Error: upgrade is only supported for managed nodegroups; could not find one with name "nodegroup-smaller"`

**How to reproduce it?**

- Create cluster.
- create a nodegroup with three nodes of any size.
- create new nodegroup with three nodes of any size.
- delete the original nodegroup

**Anything else we need to know?**
Are you using a downloaded binary or did you compile eksctl? Downloaded binary.
What type of AWS credentials are you using (i.e. default/named profile, MFA)? Default

**Versions**
$ eksctl version
`0.53.0`
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:35:50Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by cPu1** [comment] 2021-06-15 07:21
>Error: upgrade is only supported for managed nodegroups; could not find one with name "nodegroup-smaller"

As the error message indicates, `eksctl upgrade nodegroup` is only supported for managed nodegroups. You're trying to upgrade an unmanaged nodegroup. To create a managed nodegroup, specify your nodegroup specifications in `managedNodeGroups` instead of `nodeGroups`, or pass `--managed` if you're not using a config file.

**Comment by cPu1** [comment] 2021-06-15 07:23
I'm closing the issue because this is the expected behaviour. Please feel free to open a new issue if you have more questions.

**Closed by cPu1** 2021-06-15 07:23 UTC

**Comment by flybd5** [comment] 2021-06-15 15:39
Actually, no, this is **not** expected behavior. There is no "managed" option when creating nodegroups so the user's assumption is that they are all managed when created with EKSCTL. If that is not the case, it's a failure of whomever wrote the documentation. When the new nodegroup was created it did NOT show up on AWS as the nodegroup associated with the nodes, so that is not expected behavior.
