### ISSUE TITLE
`eksctl utils update-aws-node` removes iamserviceaccount annotation

### ISSUE THREAD

**Issue by patstrom** [weaveworks/eksctl#1784] opened 2020-02-04 15:26 UTC
**What happened?**

I just ran `eksctl utils update-aws-node` and pods failed to start due to the CNI not being able to apply an IP address. I managed to track it down to the serviceaccount now missing the necessary annotation for IAM role for service accounts. There were literally no error messages in any related tools (eksctl, the CNI etc).

**What you expected to happen?**

Since I created the serviceaccount and role by following the [documentation](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-cni-walkthrough.html) and the service account shows up when doing `eksctl get iamserviceaccounts`I expected the annotation to be preserved.

**How to reproduce it?**

Run `eksctl utils update-aws-node` and it will print something like `[ℹ]  (plan) would have replaced "kube-system:ServiceAccount/aws-node"`. With `--approve` it will replace the service account with a new one that doesn't have the annotation

**Versions**
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.13.0"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"archive", BuildDate:"2020-01-25T21:52:51Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by patstrom** [comment] 2020-02-05 09:06
It also seems that `eksctl utils update-aws-node` applies the updates regardless of whether the `--approve` flag is given or not. Just doing `eksctl utils update-aws-node` (without `--approve`) performs the actual update, which in this case entails overwriting the serviceaccount to remove the annotation and restarting all pods (thus rendering them useless). I'd consider this a fairly critical bug.

On that note it also always considers aws-node out-of-date, even if I've just updated it (with the `--approve` flag).

```
~ $ kc get po -l k8s-app=aws-node -n kube-system
NAME             READY   STATUS    RESTARTS   AGE
aws-node-7dwd7   1/1     Running   0          3m48s
aws-node-jmp6l   1/1     Running   0          5m3s
aws-node-kq22k   1/1     Running   0          2m
aws-node-mr26x   1/1     Running   0          4m23s
aws-node-n2q2c   1/1     Running   0          2m36s
aws-node-pfr2g   1/1     Running   0          3m15s
aws-node-z5s78   1/1     Running   0          5m38s
~ $ kc exec -n kube-system aws-node-7dwd7 env | grep AWS
AWS_VPC_K8S_CNI_MTU=9001
AWS_ROLE_ARN=arn:aws:iam::<redacted>:role/eksctl-<cluster-name>-addon-iamserviceacco-Role1-1GBTMTD215OPM
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_VPC_K8S_CNI_LOGLEVEL=DEBUG
AWS_VPC_K8S_CNI_VETHPREFIX=eni
~ $ kc get sa aws-node -o yaml -n kube-system
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<redacted>:role/eksctl-<cluster-name>-addon-iamserviceacco-Role1-1GBTMTD215OPM
  creationTimestamp: "2019-07-18T06:10:50Z"
  name: aws-node
  namespace: kube-system
  resourceVersion: "53714180"
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/aws-node
  uid: cab2a8ed-a922-11e9-9f1a-069af099ed00
secrets:
- name: aws-node-token-lwh6v
~ $ eksctl utils update-aws-node --cluster <cluster-name>
[ℹ]  eksctl version 0.13.0
[ℹ]  using region eu-west-1
[ℹ]  (plan) would have replaced "ClusterRole.rbac.authorization.k8s.io/aws-node"
[ℹ]  (plan) would have replaced "kube-system:ServiceAccount/aws-node"
[ℹ]  (plan) would have replaced "ClusterRoleBinding.rbac.authorization.k8s.io/aws-node"
[ℹ]  (plan) would have replaced "kube-system:DaemonSet.apps/aws-node"
[ℹ]  (plan) would have replaced "CustomResourceDefinition.apiextensions.k8s.io/eniconfigs.crd.k8s.amazonaws.com"
[✖]  (plan) "aws-node" is not up-to-date
[!]  no changes were applied, run again with '--approve' to apply the changes
~ $ kc get sa aws-node -o yaml -n kube-system
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2019-07-18T06:10:50Z"
  name: aws-node
  namespace: kube-system
  resourceVersion: "53716863"
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/aws-node
  uid: cab2a8ed-a922-11e9-9f1a-069af099ed00
secrets:
- name: aws-node-token-rdslw
```

Not shown here is that the daemon set is also replaced and all pods replaced. Even though they are up-to-date (as I had just updated them with using `eksctl`).

**Comment by ovd-capturi** [comment] 2020-02-12 12:26
We just had the exact same error. Added cni_policy to our node role until it's fixed.

**Comment by TBBle** [comment] 2020-04-21 07:26
Looks to be the same as #1645?

**Comment by patstrom** [comment] 2020-07-21 11:31
This still happens on the latest version (0.24) and makes the `eksctl utils update-aws-node` essentially useless.

**Comment by michaelbeaumont** [comment] 2020-07-21 13:24
Duplicate of https://github.com/weaveworks/eksctl/issues/1645

**Closed by michaelbeaumont** 2020-07-21 13:24 UTC
Labels: kind/bug, priority/important-soon
