### ISSUE TITLE
delete cluster with --approve

### ISSUE THREAD

**Issue by tigerpeng2001** [weaveworks/eksctl#5137] opened 2022-04-19 22:33 UTC
### What feature/behavior/change do you want?
Add --approve to the delete command

### Why do you want this feature?
I am new to EKS and eksctl. While play around, I notice the upgrade commands have the --approve flag, but delete commands do not? Upgrading is a dangerous activity, but deleting is the destructive one. It would be better to have a safety pin for the deleting.

**Comment by Skarlso** [comment] 2022-04-20 05:18
Hi!

Please see the discussion around here: https://github.com/weaveworks/eksctl/issues/3977.

TL;DR, it would be a massive breaking change that we decided not to implement. We don't know why it wasn't used when first the project was created. Now, so many workflows rely on this behaviour that it would be a considerable deviation from the standard workflow.

**Comment by Himangini** [comment] 2022-04-21 17:08
Dupe of #3977 

@tigerpeng2001 Thanks for the feature request. Unfortunately, we won't be adding this feature anytime soon.

**Closed by Himangini** 2022-04-21 17:08 UTC
Labels: kind/feature, kind/breaking
