### ISSUE TITLE
ARM eksctl build

### ISSUE THREAD

**Issue by tabern** [weaveworks/eksctl#2280] opened 2020-06-02 05:42 UTC
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
Ability to run eksctl on ARM-based instances. Very useful for automation.

**What feature/behavior/change do you want?**
New build of eksctl for ARM processors.

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".

**Comment by martina-if** [comment] 2020-06-03 11:16
Duplicate of #1949

**Closed by martina-if** 2020-06-03 11:16 UTC
Labels: closed/duplicate, kind/feature
