### ISSUE TITLE
auto-kubeconfig not working

### ISSUE THREAD

**Issue by cdenneen** [weaveworks/eksctl#752] opened 2019-04-24 17:24 UTC
eksctl 0.1.29
Created cluster with `--auto-kubeconfig` and no configuration created
Ran `eksctl utils write-kubeconfig --auto-kubeconfig` and it does generate but didn't upon cluster creation.

**Comment by errordeveloper** [comment] 2019-04-27 13:24
I wasn't able to reproduce this...
```
2019-04-26T15:49:37+01:00 [ℹ]  kubectl command should work with "/Users/ilya/.kube/eksctl/clusters/ridiculous-badger-1556289277", try 'kubectl --kubeconfig=/Users/ilya/.kube/eksctl/clusters/ridiculous-badger-1556289277 get nodes'
2019-04-26T15:49:37+01:00 [✔]  EKS cluster "ridiculous-badger-1556289277" in "us-west-2" region is ready
```

**Comment by cdenneen** [comment] 2019-04-30 17:52
@errordeveloper I think I know the steps to reproduce:

- make failure happen with the nodegroup creation.

It seems from the eksctl create cluster output that it starts to create nodegroup stack before it writes out the kubeconfig and if the nodegroup fails (maybe a bad/typo AZ or subnet) it fails to write the kubeconfig even though the cluster itself (control plane) is up and available, and you can use the write-kubeconfig to generate it in that case.

```
. . .
[ℹ]  building cluster stack "eksctl-eks-test-use1-cluster"
[ℹ]  deploying stack "eksctl-eks-test-use1-cluster"
[ℹ]  building nodegroup stack "eksctl-eks-test-use1-nodegroup-workers-1"
[ℹ]  deploying stack "eksctl-eks-test-use1-nodegroup-workers-1"
[✔]  all EKS cluster resource for "eks-test-use1" had been created
[✔]  saved kubeconfig as "/Users/cdenneen/.kube/eksctl/clusters/eks-test-use1"
. . .
```

So this maybe just write config after control plane creates successfully, regardless if one or more nodegroups fail?

**Comment by errordeveloper** [comment] 2019-05-01 14:25
In that case this is a duplicate of https://github.com/weaveworks/eksctl/issues/640. We can certainly write kubeconfig earlier.

**Closed** 2019-05-01 14:26 UTC
Labels: area/general-cli, closed/duplicate
