### ISSUE TITLE
Add support for Bottlerocket NVIDIA GPU variant in eksctl

### ISSUE THREAD

**Issue by Vaishvenk** [weaveworks/eksctl#4760] opened 2022-02-08 06:52 UTC
**What feature/behavior/change do you want?**
Bottlerocket is releasing an AMI specifically supporting NVIDIA based GPU EC2 instance types in addition to regular AMIs that exist today. For EKS self-managed nodes using Bottlerocket, we expect AMI resolvers in eksctl to auto-detect and resolve to the correct Bottlerocket AMI based on the specified AMI family (Bottlerocket, in this case), instance type and region in the create command, or via the config file. 

For Bottlerocket NVIDIA GPU support, the device plugin is pre-baked into the Bottlerocket GPU enabled AMI and hence we do not expect eksctl to install additional plugins. We want install-nvidia-plugin to be defaulted to false and eksctl to return an error if users pass true. Users do not have to update the K8s device plugin separately since updating their nodes to a new Bottlerocket AMI should have corresponding software including the plugin updated. 

Sample command:
```shell
$ eksctl create cluster 
--name bottlerocket_nvidia_gpu_cluster 
--instance-type g4dn.xlarge
--region us-west-2 
--node-ami-family Bottlerocket 
--install-nvidia-plugin=false
```

SSM params for Bottlerocket: EKS self-managed nodes
X86: /aws/service/bottlerocket/aws-k8s-1.21-nvidia/x86_64/latest/image_id
ARM: /aws/service/bottlerocket/aws-k8s-1.21-nvidia/arm/latest/image_id

**Why do you want this feature?**
Several Bottlerocket users today create and manage EKS clusters with Bottlerocket as the underlying node OS via eksctl. With this feature, Bottlerocket users will have an interface to easily use the NVIDIA GPU based AMIs. For other specialized computing instance types, in the future, Bottlerocket might release new AMIs specific to a given accelerated compute vendor. We want EKS + Bottlerocket users to be able to use eksctl to spin up clusters with self-managed nodes using the new Bottlerocket NVIDIA GPU based AMI.

**Comment by cPu1** [comment] 2022-02-08 07:19
Thanks for the detailed issue! The implementation for resolving the AMI for GPU instance types looks straightforward to me, however, we need to think more about how we want to handle the `--install-nvidia-plugin` flag, as a cluster can have a mix of Bottlerocket and AL2 running GPU instances, and AL2 requires the device plugin to be installed.

**Comment by rothgar** [comment] 2022-02-08 19:53
Ideally, the nvidia-plugin option could be specific to each nodegroup. It would be nice if it did the "right thing" for a user and not try to install the plugin if the nodegroup is GPU instances && AMI family is bottlerocket. If the family is AL* && GPU type then the plugin should be installed. I think this could work from the CLI and from a config file.

You'll also need to remove some existing checks around Bottlerocket and GPU instances https://github.com/weaveworks/eksctl/blob/main/pkg/apis/eksctl.io/v1alpha5/validation.go#L473-L474

**Comment by cPu1** [comment] 2022-02-09 15:25
Ideally, the nvidia-plugin option could be specific to each nodegroup. It would be nice if it did the "right thing" for a user and not try to install the plugin if the nodegroup is GPU instances && AMI family is bottlerocket. If the family is AL* && GPU type then the plugin should be installed. I think this could work from the CLI and from a config file.
> 
> You'll also need to remove some existing checks around Bottlerocket and GPU instances https://github.com/weaveworks/eksctl/blob/main/pkg/apis/eksctl.io/v1alpha5/validation.go#L473-L474

@rothgar right, this is what we are planning to do, however, if you create an AL2 GPU nodegroup later using `eksctl create nodegroup`, eksctl will need to install the NVIDIA device plugin DaemonSet and the plugin will end up running even on Bottlerocket GPU nodes. This would have been straightforward with a `nodeSelector` applied to the device plugin that targets only AL2 GPU nodes but there are no well-known labels applied to GPU nodes that can be used here. 

It's unclear whether running the device plugin on Bottlerocket GPU nodes would cause any issues or not, but before relying on this behaviour which is wasteful of resources, we'd like to work on a cleaner solution that ensures the device plugin is run only on AL2 GPU nodes.

**Comment by cPu1** [comment] 2022-02-09 15:25
> Ideally, the nvidia-plugin option could be specific to each nodegroup. It would be nice if it did the "right thing" for a user and not try to install the plugin if the nodegroup is GPU instances && AMI family is bottlerocket. If the family is AL* && GPU type then the plugin should be installed. I think this could work from the CLI and from a config file.
> 
> You'll also need to remove some existing checks around Bottlerocket and GPU instances https://github.com/weaveworks/eksctl/blob/main/pkg/apis/eksctl.io/v1alpha5/validation.go#L473-L474

 Ideally, the nvidia-plugin option could be specific to each nodegroup. It would be nice if it did the "right thing" for a user and not try to install the plugin if the nodegroup is GPU instances && AMI family is bottlerocket. If the family is AL* && GPU type then the plugin should be installed. I think this could work from the CLI and from a config file.
> 
> You'll also need to remove some existing checks around Bottlerocket and GPU instances https://github.com/weaveworks/eksctl/blob/main/pkg/apis/eksctl.io/v1alpha5/validation.go#L473-L474

@rothgar right, this is what we are planning to do, however, if you create an AL2 GPU nodegroup later using `eksctl create nodegroup`, eksctl will need to install the NVIDIA device plugin DaemonSet and the plugin will end up running even on Bottlerocket GPU nodes. This would have been straightforward with a `nodeSelector` applied to the device plugin that targets only AL2 GPU nodes but there are no well-known labels applied to GPU nodes that can be used here. 

It's unclear whether running the device plugin on Bottlerocket GPU nodes would cause any issues or not, but before relying on this behaviour which is wasteful of resources, we'd like to work on a cleaner solution that ensures the device plugin is run only on AL2 GPU nodes.

**Comment by cPu1** [comment] 2022-02-09 15:25
> Ideally, the nvidia-plugin option could be specific to each nodegroup. It would be nice if it did the "right thing" for a user and not try to install the plugin if the nodegroup is GPU instances && AMI family is bottlerocket. If the family is AL* && GPU type then the plugin should be installed. I think this could work from the CLI and from a config file.
> 
> You'll also need to remove some existing checks around Bottlerocket and GPU instances https://github.com/weaveworks/eksctl/blob/main/pkg/apis/eksctl.io/v1alpha5/validation.go#L473-L474


@rothgar right, this is what we are planning to do, however, if you create an AL2 GPU nodegroup later using `eksctl create nodegroup`, eksctl will need to install the NVIDIA device plugin DaemonSet and the plugin will end up running even on Bottlerocket GPU nodes. This would have been straightforward with a `nodeSelector` applied to the device plugin that targets only AL2 GPU nodes but there are no well-known labels applied to GPU nodes that can be used here. 

It's unclear whether running the device plugin on Bottlerocket GPU nodes would cause any issues or not, but before relying on this behaviour which is wasteful of resources, we'd like to work on a cleaner solution that ensures the device plugin is run only on AL2 GPU nodes.

**Comment by rothgar** [comment] 2022-02-09 17:46
Good point. I've had some issues of nodes not joining the cluster when the daemonset was running. I haven't pinpointed if the daemonset was the cause of the problem or just a coincidence.

I wish there were some kind of `node.kubernetes.io/distro` common label :(

**Comment by cPu1** [comment] 2022-02-15 14:00
There is no well-known label that can be used to target AL2 GPU instance types that'd allow us to schedule the device plugin pods only on AL2 GPU nodes. We can consider adding a new label to nodegroups using AL2 GPU instance types when `eksctl create nodegroup` is used, and use that label as a nodeSelector in the NVIDIA device plugin DaemonSet, but this approach suffers from a problem. If AL2 GPU instance types are already being used in the cluster, patching the existing DaemonSet would cause the pods to no longer run on them, potentially breaking GPU-accelerated applications on those nodes. A more complete solution would be to also apply those labels to existing AL2 GPU nodes, however, this is more complex to achieve for self-managed nodegroups, especially those created outside of eksctl.

I ran the device plugin on Bottlerocket GPU nodes and did not run into any node-related failures. Another user was able to successfully run GPU-accelerated workloads on Bottlerocket GPU nodes running the device plugin, although we need to verify [this part](https://github.com/weaveworks/eksctl/issues/4771#issuecomment-1040258935). 

It'd be best if AL2 GPU AMIs started adding a label to identify themselves as AL2 GPU nodes, simplifying targeting device plugin pods to those nodes with a `nodeSelector`. Alternatively, Bottlerocket GPU nodes can start labelling themselves and the device plugin can use an anti-affinity rule, but the former approach is cleaner. But until this labelling feature is added, I think we should not try to address this case and let the device plugin run on Bottlerocket GPU nodes if a cluster also has AL2 GPU nodes. We can, however, ensure that the device plugin is only installed when an AL2 GPU instance type is created.

**Closed** 2022-02-24 18:37 UTC
Labels: kind/feature, area/nodegroup
