### ISSUE TITLE
eksctl 0.31.0 doesn't respect availabilityZones for managedNodeGroups in config file

### ISSUE THREAD

**Issue by guanchzhou** [weaveworks/eksctl#2806] opened 2020-11-09 18:14 UTC
**What happened?**

The following command
```
eksctl upgrade nodegroup --cluster=test-cluster --name=managed-ng-1 --config-file=test-cluster.yaml --kubernetes-version=1.17
```
with this particular config file

`
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-west-2
  version: "1.17"

availabilityZones: ["us-west-2a", "us-west-2b"]

managedNodeGroups:
  - name: managed-ng-1
    availabilityZones: ["us-west-2a", "us-west-2b"]
    minSize: 2
    maxSize: 4
    instanceType: m5.xlarge
    desiredCapacity: 2
    volumeSize: 20
    labels: { role: worker }
    tags:
      nodegroup-role: worker
`
does not respect `availabilityZones` defined for managedNodeGroups. 

During upgrade it creates nodes in all available zones in region (including us-west-2d) and at the end of upgrade it left running nodes in c and d instead of a and b.

**What you expected to happen?**

Expected to have nodes only in a and b as it clearly defined in config.

**How to reproduce it?**

Run described command with described config file.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version

0.31.0

$ kubectl version

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**

Upgrade had no errors in console.

```
[ℹ]  updating nodegroup stack to a newer format before upgrading nodegroup version
[ℹ]  Update nodegroup stack
[ℹ]  upgrading nodegroup version
[ℹ]  Update nodegroup stack
[ℹ]  nodegroup successfully upgrade
```

**Comment by cPu1** [comment] 2020-11-09 18:29
`eksctl upgrade nodegroup` only reads the cluster name (`metadata.name`) and region (`metadata.region`) when a config file is supplied, and all other fields, including `managedNodeGroups[*].availabilityZones`, are ignored. 

This is not a bug as changing the `availabilityZones` is not a feature that's supported. If you need to use new a new set of availability zones, you'll have to create a new nodegroup, and drain and delete the old one.

**Comment by cPu1** [comment] 2020-11-09 18:33
Closing the issue. Please feel free to open a new issue if you have any more questions, or ask us in [Weave Community Slack (#eksctl) ](https://weave-community.slack.com/messages/CAYBZBWGL/)

**Closed by cPu1** 2020-11-09 18:33 UTC
