### ISSUE TITLE
Can't create a cluster with managed nodegroup

### ISSUE THREAD

**Issue by artem-nefedov** [weaveworks/eksctl#2675] opened 2020-09-25 14:11 UTC
**What happened?**

eksctl fails to create a cluster with the following error from CFN:

```
Logical ID: ManagedNodeGroup
Status reason: The provided role doesn't have the Amazon EKS Managed Policies associated with it. Please ensure the following policies [arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy, arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy, arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly] are attached (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: ****; Proxy: null)
```

**How to reproduce it?**

eksctl create cluster -f manifest.yaml

manifest.yaml contenst:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fake-cluster
  region: us-west-2
  tags:
    Environment: fake
    Owner: fake
    Requestor: fake
    Role: fake
  version: "1.17"

iam:
  serviceAccounts:
  - attachPolicy:
      Statement:
      - Action:
        - route53:ChangeResourceRecordSets
        Effect: Allow
        Resource: arn:aws:route53:::hostedzone/*
      - Action:
        - route53:ListHostedZones
        - route53:ListResourceRecordSets
        - route53:ListTagsForResource
        Effect: Allow
        Resource: '*'
      Version: "2012-10-17"
    metadata:
      labels:
        istio-injection: disabled
      name: external-dns
      namespace: external-dns
  - attachPolicy:
      Statement:
      - Action:
        - autoscaling:DescribeAutoScalingGroups
        - autoscaling:DescribeAutoScalingInstances
        - autoscaling:DescribeLaunchConfigurations
        - autoscaling:DescribeTags
        - autoscaling:SetDesiredCapacity
        - autoscaling:TerminateInstanceInAutoScalingGroup
        - ec2:DescribeLaunchTemplateVersions
        Effect: Allow
        Resource: '*'
      Version: "2012-10-17"
    metadata:
      name: cluster-autoscaler
      namespace: kube-system
  withOIDC: true

managedNodeGroups:
- desiredCapacity: 2
  launchTemplate:
    id: lt-12345
  maxSize: 10
  minSize: 2
  name: managed-ng-1
  privateNetworking: true
  tags:
    Environment: fake
    Owner: fake
    Requestor: fake
    Role: fake
secretsEncryption:
  keyARN: FakeKey
```

**Anything else we need to know?**
Version 0.26.0 works fine.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.28.1
```

**Comment by michaelbeaumont** [comment] 2020-09-25 14:35
@artem-nefedov Thanks for the bug report! The issue is in the process of being fixed. As a workaround, you can set `withOIDC: false` and `serviceAccounts: []` and creation should succeed, you can then use `utils associate-oidc-provider` and [`create iamserviceaccount`](https://eksctl.io/usage/iamserviceaccounts/#usage-with-config-files)

**Comment by michaelbeaumont** [comment] 2020-10-03 20:38
This issue is now fixed, there is another that still breaks managed nodegroups with OIDC

**Closed** 2020-10-03 22:25 UTC
Labels: kind/bug

**Comment by michaelbeaumont** [comment] 2020-10-04 18:10
The second issue is now fixed as well
