### ISSUE TITLE
SIGSEV with custom CIDR

### ISSUE THREAD

**Issue by benwilson512** [weaveworks/eksctl#1011] opened 2019-07-09 19:00 UTC
**What happened?**
Running the example https://github.com/weaveworks/eksctl/blob/master/examples/02-custom-vpc-cidr-no-nodes.yaml causes a SIGSEV

**What you expected to happen?**
It should not segfault, and should create the cluster.

**How to reproduce it?**
```
curl https://raw.githubusercontent.com/weaveworks/eksctl/master/examples/02-custom-vpc-cidr-no-nodes.yaml -o ./custom-cidr.yml
eksctl create cluster -f ./custom-cidr.yml
```

**Anything else we need to know?**
OS X, homebrew install.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.39"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:52:26Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
```

**Logs**
```
ben:cluster ben$ eksctl create cluster -f ./custom-cidr.yml -v 4
2019-07-09T14:48:43-04:00 [ℹ]  using region eu-north-1
2019-07-09T14:48:44-04:00 [▶]  role ARN for the current session is "arn:aws:sts::332145145575:assumed-role/CargosenseDev/1562698123983825000"
2019-07-09T14:48:44-04:00 [▶]  determining availability zones
2019-07-09T14:48:44-04:00 [ℹ]  setting availability zones to [eu-north-1a eu-north-1c eu-north-1b]
2019-07-09T14:48:44-04:00 [▶]  VPC CIDR (10.10.0.0/16) was divided into 8 subnets [10.10.0.0/19 10.10.32.0/19 10.10.64.0/19 10.10.96.0/19 10.10.128.0/19 10.10.160.0/19 10.10.192.0/19 10.10.224.0/19]
2019-07-09T14:48:44-04:00 [ℹ]  subnets for eu-north-1a - public:10.10.0.0/19 private:10.10.96.0/19
2019-07-09T14:48:44-04:00 [ℹ]  subnets for eu-north-1c - public:10.10.32.0/19 private:10.10.128.0/19
2019-07-09T14:48:44-04:00 [ℹ]  subnets for eu-north-1b - public:10.10.64.0/19 private:10.10.160.0/19
2019-07-09T14:48:44-04:00 [ℹ]  using Kubernetes version 1.13
2019-07-09T14:48:44-04:00 [ℹ]  creating EKS cluster "cluster-2" in "eu-north-1" region
2019-07-09T14:48:44-04:00 [▶]  cfg.json = \
{
    "kind": "ClusterConfig",
    "apiVersion": "eksctl.io/v1alpha5",
    "metadata": {
        "name": "cluster-2",
        "region": "eu-north-1",
        "version": "1.13"
    },
    "iam": {},
    "vpc": {
        "cidr": "10.10.0.0/16",
        "subnets": {
            "private": {
                "eu-north-1a": {
                    "cidr": "10.10.96.0/19"
                },
                "eu-north-1b": {
                    "cidr": "10.10.160.0/19"
                },
                "eu-north-1c": {
                    "cidr": "10.10.128.0/19"
                }
            },
            "public": {
                "eu-north-1a": {
                    "cidr": "10.10.0.0/19"
                },
                "eu-north-1b": {
                    "cidr": "10.10.64.0/19"
                },
                "eu-north-1c": {
                    "cidr": "10.10.32.0/19"
                }
            }
        },
        "autoAllocateIPv6": true
    },
    "availabilityZones": [
        "eu-north-1a",
        "eu-north-1c",
        "eu-north-1b"
    ]
}

2019-07-09T14:48:44-04:00 [ℹ]  will create a CloudFormation stack for cluster itself and 0 nodegroup stack(s)
2019-07-09T14:48:44-04:00 [ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=eu-north-1 --name=cluster-2'
2019-07-09T14:48:44-04:00 [ℹ]  1 task: { create cluster control plane "cluster-2" }
2019-07-09T14:48:44-04:00 [▶]  started task: create cluster control plane "cluster-2"
2019-07-09T14:48:44-04:00 [ℹ]  building cluster stack "eksctl-cluster-2-cluster"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x20abc92]

goroutine 63 [running]:
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).addNATGateways(0xc00011f590, 0xc00031b150, 0x35f9cc0)
	/src/pkg/cfn/builder/vpc.go:125 +0x32
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).addResourcesForVPC(0xc00011f590, 0x0, 0x0)
	/src/pkg/cfn/builder/vpc.go:115 +0x379
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ClusterResourceSet).AddAllResources(0xc00011f590, 0xc00011f590, 0xc0004e6e80)
	/src/pkg/cfn/builder/cluster.go:43 +0x88
github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).createClusterTask(0xc00053ab10, 0xc0000a0b40, 0x60, 0x0)
	/src/pkg/cfn/manager/cluster.go:33 +0x329
github.com/weaveworks/eksctl/pkg/cfn/manager.(*taskWithoutParams).Do(0xc0007029c0, 0xc0000a0b40, 0xc0000a0b40, 0x1)
	/src/pkg/cfn/manager/tasks.go:132 +0x34
github.com/weaveworks/eksctl/pkg/cfn/manager.doSingleTask(0xc0000a0a20, 0x3a86800, 0xc0007029c0, 0x0)
	/src/pkg/cfn/manager/tasks.go:185 +0xec
github.com/weaveworks/eksctl/pkg/cfn/manager.doSequentialTasks(0xc0000a0a20, 0xc00031ab30, 0x1, 0x1)
	/src/pkg/cfn/manager/tasks.go:215 +0x70
created by github.com/weaveworks/eksctl/pkg/cfn/manager.(*TaskTree).DoAllSync
	/src/pkg/cfn/manager/tasks.go:115 +0x246
```

**Comment by cPu1** [comment] 2019-07-10 07:29
This seems to be a duplicate of https://github.com/weaveworks/eksctl/issues/1003

We have a PR for this issue pending review, it should land in the next release.

**Comment by cPu1** [comment] 2019-07-10 07:47
This seems to be a duplicate of https://github.com/weaveworks/eksctl/issues/1003

We have a PR for this pending review, it should land in the next release.

**Comment by errordeveloper** [comment] 2019-07-10 08:00
@benwilson512 the following should work as a work-around:

```JSON
{
    "kind": "ClusterConfig",
    "apiVersion": "eksctl.io/v1alpha5",
    "metadata": {
        "name": "cluster-2",
        "region": "eu-north-1",
        "version": "1.13"
    },
    "iam": {},
    "vpc": {
        "cidr": "10.10.0.0/16",
        "nat": { "gateway": "HighlyAvailable" },
    }
}
```

You can chose `HighlyAvailable` or `Single`. Please let us know what works for you, then close the issue, as it's already being addressed.

**Closed** 2019-07-10 14:13 UTC
Labels: area/aws-vpc, area/config-file, closed/duplicate, kind/bug

**Comment by errordeveloper** [comment] 2019-07-10 15:09
@benwilson512 so this workaround worked, right?

**Comment by benwilson512** [comment] 2019-07-10 15:30
Ah oops yes this worked.
