### ISSUE TITLE
eksctl enable repo does not detect helm operator pod as started and fails

### ISSUE THREAD

**Issue by log2** [weaveworks/eksctl#2152] opened 2020-05-07 22:08 UTC
**What happened?**
Tried to enable FluxCD together with helm operator.
Command used:
EKSCTL_EXPERIMENTAL=true eksctl enable repo --cluster=*** --region=eu-central-1 --git-url=git@bitbucket.org:***/*** --git-email=***@eco-mind.eu --git-private-ssh-key-path flux_id_rsa --git-branch develop --git-paths sof

("sof" being "State Of Flux" ... didn't want for Flux to check in main folder)

After some checking for helm operator pod start up, got a final error and no success, however flux pods appear to be all up, including Helm operator:
```
kubectl get pod --namespace flux
NAME                             READY   STATUS    RESTARTS   AGE
flux-d476f487c-7cskq             1/1     Running   0          11m
helm-operator-74546bd6f5-j6pws   1/1     Running   0          11m
memcached-689f7846dc-nzv7n       1/1     Running   0          11m
```
The problem might be that helm operator pod is named "helm-operator", not "flux-helm-operator", which eksctl apparently searches for (see log below):

```
kubectl get pod -l name=helm-operator -n flux -o=yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubernetes.io/psp: eks.privileged
      prometheus.io/scrape: "true"
    creationTimestamp: "2020-05-07T21:41:59Z"
    generateName: helm-operator-74546bd6f5-
    labels:
      name: helm-operator
      pod-template-hash: 74546bd6f5
```

**What you expected to happen?**
FluxCD being installed with confirmation message from eksctl experimental. Note that FluxCD might be up, though, but in that case the error message I received from eksctl is a bit misleading.

**How to reproduce it?**
Enable FluxCD on repo with eksctl, including helm operator (i.e., --with-helm)

**Anything else we need to know?**
macOS Catalina 10.15.4
```
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287
```

eksctl downloaded by brew

Using regular pair of aws_access_key_id / aws_secret_access_key in a named profile (AWS_PROFILE is populated)

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.18.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
```
[ℹ]  Generating manifests
[ℹ]  Cloning git@bitbucket.org:***
Cloning into '/var/folders/l6/jtjsvcgd1lb0mldcmgt55_cm0000gn/T/eksctl-install-flux-clone-963158006'...
remote: Counting objects: 4528, done.
remote: Compressing objects: 100% (3836/3836), done.
remote: Total 4528 (delta 2662), reused 1012 (delta 487)
Receiving objects: 100% (4528/4528), 61.10 MiB | 3.84 MiB/s, done.
Resolving deltas: 100% (2662/2662), done.
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
Switched to a new branch 'develop'
[ℹ]  Writing Flux manifests
[ℹ]  created "Namespace/flux"
[ℹ]  Applying manifests
[ℹ]  created "flux:Service/memcached"
[ℹ]  created "flux:ServiceAccount/flux"
[ℹ]  created "ClusterRole.rbac.authorization.k8s.io/flux"
[ℹ]  created "ClusterRoleBinding.rbac.authorization.k8s.io/flux"
[ℹ]  created "flux:ServiceAccount/helm-operator"
[ℹ]  created "ClusterRole.rbac.authorization.k8s.io/helm-operator"
[ℹ]  created "ClusterRoleBinding.rbac.authorization.k8s.io/helm-operator"
[ℹ]  created "flux:Secret/flux-git-deploy"
[ℹ]  created "flux:Deployment.apps/memcached"
[ℹ]  created "flux:Deployment.apps/flux"
[ℹ]  created "CustomResourceDefinition.apiextensions.k8s.io/helmreleases.helm.fluxcd.io"
[ℹ]  created "flux:Deployment.apps/helm-operator"
[ℹ]  Waiting for Helm Operator to start
[!]  Helm Operator is not ready yet (Could not create a dialer: Could not get pod name: Could not find pod for selector: labels "name in (flux-helm-operator)"), retrying ...
(^-- repeated many times)
[✖]  You may find the local clone of git@bitbucket.org:*/*.git used by eksctl at /var/folders/l6/jtjsvcgd1lb0mldcmgt55_cm0000gn/T/eksctl-install-flux-clone-963158006
Error: timed out waiting for Helm Operator's pod to be created
```

**Comment by michaelbeaumont** [comment] 2020-05-07 22:13
@log2  this looks like a duplicate of https://github.com/weaveworks/eksctl/issues/2118 which is fixed in the current release candidate

**Closed** 2020-05-07 22:40 UTC
Labels: closed/duplicate, kind/bug

**Comment by log2** [comment] 2020-05-09 09:44
Tried 0.19.0-rc.1, bug seems fixed. Thank you @michaelbeaumont for your advice.
