### ISSUE TITLE
eksctl to generate yaml from cli 

### ISSUE THREAD

**Issue by dilshad18** [weaveworks/eksctl#1984] opened 2020-03-27 09:01 UTC
**Why do you want this feature?**
as i was unable to use --version flag in yaml so i had run eksctl cli , if eksctl genrate a yaml file from cli just like kubectl this will be big help e.g. kubectl something --dry-run -o yaml > file

**What feature/behavior/change do you want?**

eksctl create cluster play -t t2.medium -r ap-south-1 -N 2 --version 1.15 --nodegroup-name play. --dry-run -o yaml  > file and then eksctl can apply that file

**Comment by alanoberto** [comment] 2020-04-02 23:46
Hi @dilshad18, could you solve the -version in YAML? I have the same issue

**Comment by karlmuscat-dpg** [comment] 2020-04-03 15:32
@dilshad18 @alanoberto is it maybe `ClusterMeta.version`? +1 to add generation of yaml though

**Comment by dilshad18** [comment] 2020-04-03 18:04
@alanoberto yes, @karlmuscat-dpg thanks for hint
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: XXX
  region: xxxx
  version: "1.15"
nodeGroups:
  - name: ASGxxx
    instanceType: xxx
    desiredCapacity: xxx

**Comment by michaelbeaumont** [comment] 2021-01-19 13:30
Duplicate of https://github.com/weaveworks/eksctl/issues/633

**Closed** 2021-01-19 13:30 UTC
Labels: kind/feature, priority/backlog
