### ISSUE TITLE
panic error in create cluster

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#1876] opened 2020-03-02 11:49 UTC
Reported in https://github.com/weaveworks/launcher/issues/308 by @cadedaniel 

I have a CI system that ran the following command:
```
eksctl create cluster xyz --nodes 1 --node-type=c5.xlarge --timeout=40m --region us-east-2 --auto-kubeconfig --version 1.14 --vpc-public-subnets=subnet-05cf456f7164b5bc3,subnet-0f6ee465d5b9eab20 --vpc-private-subnets=subnet-0522bc923906d6a26,subnet-0133c270976907933
```

It produced the following crash:
```
[ℹ]  eksctl version 0.11.1
[ℹ]  using region us-east-2
[✔]  using existing VPC (vpc-074a87335e1e88bbc) and subnets (private:[subnet-0133c270976907933 subnet-0522bc923906d6a26] public:[subnet-05cf456f7164b5bc3 subnet-0f6ee465d5b9eab20])
[!]  custom VPC/subnets will be used; if resulting cluster doesn't function as expected, make sure to review the configuration of VPC/subnets
[ℹ]  nodegroup "ng-6bed9233" will use "ami-082bb518441d3954c" [AmazonLinux2/1.14]
[ℹ]  using Kubernetes version 1.14
[ℹ]  creating EKS cluster "xyz" in "us-east-2" region with un-managed nodes
[ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial nodegroup
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-east-2 --cluster=xyz'
[ℹ]  CloudWatch logging will not be enabled for cluster "xyz" in "us-east-2"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=us-east-2 --cluster=xyz'
[ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "xyz" in "us-east-2"
[ℹ]  2 sequential tasks: { create cluster control plane "xyz", create nodegroup "ng-6bed9233" }
[ℹ]  building cluster stack "eksctl-xyz-cluster"
[ℹ]  deploying stack "eksctl-xyz-cluster"
[ℹ]  building nodegroup stack "eksctl-xyz-nodegroup-ng-6bed9233"
[ℹ]  --nodes-min=1 was set automatically for nodegroup ng-6bed9233
[ℹ]  --nodes-max=1 was set automatically for nodegroup ng-6bed9233
[ℹ]  deploying stack "eksctl-xyz-nodegroup-ng-6bed9233"
[✔]  all EKS cluster resources for "xyz" have been created
[✔]  saved kubeconfig as "/root/.kube/eksctl/clusters/xyz"
[ℹ]  adding identity "arn:aws:iam::123456789012:role/eksctl-xyz ConfigMap
[ℹ]  nodegroup "ng-6bed9233" has 0 node(s)
[ℹ]  waiting for at least 1 node(s) to become ready in "ng-6bed9233"
[ℹ]  nodegroup "ng-6bed9233" has 1 node(s)
[ℹ]  node "ip-10-0-3-191.us-east-2.compute.internal" is ready
panic: runtime error: slice bounds out of range
goroutine 877 [running]:
bytes.(*Buffer).grow(0xc00093ad20, 0x101, 0xc0000a66d8)
	/usr/local/go/src/bytes/buffer.go:151 +0x2c9
bytes.(*Buffer).Write(0xc00093ad20, 0xc000460000, 0x101, 0x8000, 0x0, 0x0, 0x101)
	/usr/local/go/src/bytes/buffer.go:175 +0xe6
io.(*multiWriter).Write(0xc000804700, 0xc000460000, 0x101, 0x8000, 0x101, 0x0, 0x0)
	/usr/local/go/src/io/multi.go:60 +0x87
io.copyBuffer(0x3643d00, 0xc000804700, 0x3644980, 0xc00000e308, 0xc000460000, 0x8000, 0x8000, 0x31ac890, 0x0, 0x57bd460)
	/usr/local/go/src/io/io.go:404 +0x1fb
io.Copy(...)
	/usr/local/go/src/io/io.go:364
github.com/weaveworks/launcher/pkg/kubectl.outputMatrix.func1(0x3643d00, 0xc000804700, 0x3644980, 0xc00000e308)
	/go/pkg/mod/github.com/weaveworks/launcher@v0.0.0-20180711153254-f1b2830d4f2d/pkg/kubectl/local.go:61 +0x84
created by github.com/weaveworks/launcher/pkg/kubectl.outputMatrix
	/go/pkg/mod/github.com/weaveworks/launcher@v0.0.0-20180711153254-f1b2830d4f2d/pkg/kubectl/local.go:67 +0x4f6
```

That line in this repository is [here](https://github.com/weaveworks/launcher/blob/master/pkg/kubectl/local.go#L61):
```go
        _, _ = io.Copy(dst, src)
```

I don't know how exactly this line was invoked, but I suspect the issue is on [line 52](https://github.com/weaveworks/launcher/blob/master/pkg/kubectl/local.go#L52). The [docs](https://golang.org/pkg/os/exec/#Cmd.StdoutPipe) for `cmd.StdoutPipe()` say it can return an error, which is ignored:
```go
    stdoutPipe, _ := cmd.StdoutPipe()
```

**Comment by agbanagba** [comment] 2020-05-20 18:10
I will take a look at this and investigate further.

**Comment by agbanagba** [comment] 2020-05-24 19:34
I tried recreating the bug but my command ran successfully as seen below

    eksctl create cluster xyz --nodes 1 --node-type=c5.xlarge --timeout=40m --region eu-west-1 --auto-kubeconfig --version 1.14 --vpc-public-subnets=subnet-03f876c50a78ccbca,subnet-0d4b334acadda5fcd --vpc-private-subnets=subnet-0b33721f76f6edc0f,subnet-02c2121cbdebeb175
    [ℹ]  eksctl version 0.11.0
    [ℹ]  using region eu-west-1
    [✔]  using existing VPC (vpc-007bae328e3fe2363) and subnets (private:[subnet-02c2121cbdebeb175 subnet-0b33721f76f6edc0f] public:[subnet-03f876c50a78ccbca subnet-0d4b334acadda5fcd])
    [!]  custom VPC/subnets will be used; if resulting cluster doesn't function as expected, make sure to review the configuration of VPC/subnets
    [ℹ]  nodegroup "ng-7d6fa1b3" will use "ami-059c6874350e63ca9" [AmazonLinux2/1.14]
    [ℹ]  using Kubernetes version 1.14
    [ℹ]  creating EKS cluster "xyz" in "eu-west-1" region with un-managed nodes
    [ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial nodegroup
    [ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=eu-west-1 --cluster=xyz'
    [ℹ]  CloudWatch logging will not be enabled for cluster "xyz" in "eu-west-1"
    [ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=eu-west-1 --cluster=xyz'
    [ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "xyz" in "eu-west-1"
    [ℹ]  2 sequential tasks: { create cluster control plane "xyz", create nodegroup "ng-7d6fa1b3" }
    [ℹ]  building cluster stack "eksctl-xyz-cluster"
    [ℹ]  deploying stack "eksctl-xyz-cluster"
    [!]  retryable error (RequestError: send request failed
    caused by: Post https://cloudformation.eu-west-1.amazonaws.com/: dial tcp: lookup cloudformation.eu-west-1.amazonaws.com on 127.0.0.53:53: read udp 127.0.0.1:59767->127.0.0.53:53: i/o timeout) from cloudformation/DescribeStacks - will retry after delay of 30.465407ms
    [ℹ]  building nodegroup stack "eksctl-xyz-nodegroup-ng-7d6fa1b3"
    [ℹ]  --nodes-min=1 was set automatically for nodegroup ng-7d6fa1b3
    [ℹ]  --nodes-max=1 was set automatically for nodegroup ng-7d6fa1b3
    [ℹ]  deploying stack "eksctl-xyz-nodegroup-ng-7d6fa1b3"
    [✔]  all EKS cluster resources for "xyz" have been created
    [✔]  saved kubeconfig as "~/.kube/eksctl/clusters/xyz"
    [ℹ]  adding identity "arn:aws:iam::642881291524:role/eksctl-xyz-nodegroup-ng-7d6fa1b3-NodeInstanceRole-1HPSB79UM8EB2" to auth ConfigMap
    [ℹ]  nodegroup "ng-7d6fa1b3" has 0 node(s)
    [ℹ]  waiting for at least 1 node(s) to become ready in "ng-7d6fa1b3"
    [ℹ]  nodegroup "ng-7d6fa1b3" has 1 node(s)
    [ℹ]  node "ip-10-0-1-162.eu-west-1.compute.internal" is ready
    [ℹ]  kubectl command should work with "~/.kube/eksctl/clusters/xyz", try 'kubectl --kubeconfig=/home/oghenetega/.kube/eksctl/clusters/xyz get nodes'
    [✔]  EKS cluster "xyz" in "eu-west-1" region is ready  


I looked at the bug carefully and realized we might be dealing with a possible race condition here that rarely occurs since using the race detector did not give me any results. 

Two goroutines are spawned that copy data from two readers (stdoutPipe & stderrPipe) to two multiwriters that both writes to a combined buffer without a lock. Below is a snippet that does that copy.

	stdoutPipe, _ := cmd.StdoutPipe()
	stderrPipe, _ := cmd.StderrPipe()


	stdoutWriter := io.MultiWriter(&combinedBuf, &stdoutBuf)
	stderrWriter := io.MultiWriter(&combinedBuf, &stderrBuf)


	var wg sync.WaitGroup
	copy := func(dst io.Writer, src io.Reader) {
		defer wg.Done()
		_, _ = io.Copy(dst, src)
	}


	err = cmd.Start()
	if err == nil {
		wg.Add(2)
		go copy(stdoutWriter, stdoutPipe)
		go copy(stderrWriter, stderrPipe)
		// we need to wait for all reads to finish before calling cmd.Wait
		wg.Wait()
		err = cmd.Wait()
	}

This is an upstream dependency on the weaveworks/launcher repo. @martina-if can I raise a PR in that repository as I can't see an CONTRIBUTING rules there.

**Comment by martina-if** [comment] 2020-05-26 09:30
Hi @agbanagba good catch! I am not sure what's the state of that repo but yeah, I think it should be fine to open a PR against it. I will also review with my team if this dependency can be replaced.

**Comment by agbanagba** [comment] 2020-05-26 17:26
Thanks @martina-if. I will make the PR against the repo in the meantime.

**Comment by martina-if** [comment] 2020-06-03 13:31
https://github.com/weaveworks/launcher/pull/313

**Comment by agbanagba** [comment] 2020-07-15 15:16
@martina-if This is resolved and can be closed. Thanks

**Comment by michaelbeaumont** [comment] 2020-07-15 15:18
@agbanagba Do you want to create a PR to use the new version of `launcher`?

**Comment by agbanagba** [comment] 2020-07-15 15:21
No new version released yet. The PR in launcher was merged today. I can create an issue to use new version of launcher when released referencing this if that's okay.

**Comment by michaelbeaumont** [comment] 2020-07-15 15:25
@agbanagba I don't think we need to wait, we aren't referencing a release for the package anyway

**Comment by agbanagba** [comment] 2020-07-15 15:26
Oh yeah. I'll check it out and create a PR. Thanks @michaelbeaumont

**Closed** 2020-07-20 12:52 UTC
Labels: kind/bug, needs-investigation, priority/important-soon
