### ISSUE TITLE
Image tag linting on eksctl utils

### ISSUE THREAD

**Issue by Guillermogsjc** [weaveworks/eksctl#6265] opened 2023-02-07 06:51 UTC
Hi,

again the error reported on issue https://github.com/weaveworks/eksctl/issues/6144 is happening.

The command `eksctl utils update-kube-proxy --approve --cluster ${CLUSTER_NAME}` patches `kube-proxy` daemonset telling to pull an image with an **unexistent tag**.

Specifically in this moment, it tries to get the image `602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.22.16-eksbuild.3` , while the available ones are: https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html, so the daemonset keeps in `ErrImgPull`forever, causing nodes to fail join the cluster.

Maybe there should be a hard CI linting on this kind of codes about existing image tags to use and patch, because this crashes hard and `eksctl`is the official client. Refer to [@jimdial](https://github.com/jimdial-aws) for the doc and sync part.

Kind regards.

**Comment by cPu1** [comment] 2023-02-07 10:30
@Guillermogsjc, I'm unable to reproduce this in the latest version of eksctl. What version of eksctl are you using? The fix you're referring to was released in [https://github.com/weaveworks/eksctl/releases/tag/v0.127.0](v0.127.0).

**Comment by Guillermogsjc** [comment] 2023-02-07 10:43
hi @cPu1 , will update from `v0.112.0` (the version where it is happening), to `>=v0.127.0` .  Thanks for the quick response and sorry for the noise introduced.

**Comment by Guillermogsjc** [comment] 2023-02-13 14:45
hi,

sorry, just executed on `v128.0`  the command `eksctl utils update-kube-proxy --approve --cluster ${CLUSTER_NAME}` and the kubeproxy daemonset changed his image to use `602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.22.16-eksbuild.3` (unexisting image)

 currently sets kube-proxy daemonset in an unoperating way so it just kills the cluster avoiding nodes to join with ErrPullImage forever on kube-proxy daemonset.

as said, a heavy linting on the tags available is necessary for this kind of client calls. To patch the daemonset into an unexisting image is killing a cluster.

**Closed** 2023-02-13 14:51 UTC
Labels: kind/bug, area/add-ons
