### ISSUE TITLE
Cannot create Bottlerocket nodegroup from cli options

### ISSUE THREAD

**Issue by rothgar** [weaveworks/eksctl#4863] opened 2022-02-28 22:28 UTC
**What were you trying to accomplish?**

Create a cluster with Bottlerocket node group without using a config file.

**What happened?**

I get this error during node group creation
```
2022-02-28 10:45:50 [✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Resource handler returned message: \"[Issue(Code=Ec2LaunchTemplateInvalidConfiguration, Message=User data was not in the MIME multipart format.)] (Service: null, Status Code: 0, Request ID: null, Extended Request ID: null)\" (RequestToken: e723fed3-206e-c209-f13d-df86cd280ee4, HandlerErrorCode: GeneralServiceException)"
```

**How to reproduce it?**

Using `eksctl` 0.86.0-rc.0 use this command 

```
eksctl create cluster --name br-gpu \
    --instance-types g4dn.xlarge \
    --node-ami-family Bottlerocket
```

**Logs**

**Anything else we need to know?**

If I use a config file and don't set any settings for the node group the cluster is created properly. It appears only to be an issue from the CLI. Here's an example config that worked.

```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bottlerocket-test
  region: ca-central-1

nodeGroups:
  - name: ng1-public
    instanceType: m5.xlarge
    desiredCapacity: 2
    amiFamily: Bottlerocket
```

**Versions**

```
$ eksctl info

eksctl version: 0.86.0-rc.0
kubectl version: v1.23.4
OS: linux
```
This is related to #4809 and while using a config file for the cluster works it doesn't appear that user-data is sent to the CFN stack (even if no user-data is needed) which causes the issue.

**Comment by cPu1** [comment] 2022-03-01 06:59
This is certainly a bug as I was able to reproduce it. 

However, your CLI options do not map to the config file as eksctl creates managed nodegroups by default, whereas your config file is using self-managed (`nodeGroups`) nodegroups.

**Comment by Himangini** [comment] 2022-03-01 11:47
@rothgar thanks for reporting the issue. We will investigate further and work on resolving this soon. 👍🏻

**Comment by aclevername** [comment] 2022-03-01 16:12
Thanks @rothgar . Looking into it it appears as part of https://github.com/weaveworks/eksctl/pull/4809 we only tested support for `unmanaged` nodegroups (referred as `nodeGroups` in the config file).

Any `eksctl create cluster` or `eksctl create nodegroup` defaults to creating a managed nodegroup (referred as `managedNodeGroups` in the config file). To create an unmanaged nodegroup pass in the `--managed=false` flag.

Prior to https://github.com/weaveworks/eksctl/pull/4809 the behaviour was to error when attempting to create a managed GPU Bottlerocket nodegroup:
- ```
  eksctl create nodegroup --cluster jk --name br-old --instance-types g4dn.xlarge --node-ami-family Bottlerocket
  Error: couldn't create cluster provider from options: GPU instance types are not supported for Bottlerocket 
  ```
 
I think this error checking got removed as part of  https://github.com/weaveworks/eksctl/pull/4809, but since  https://github.com/weaveworks/eksctl/pull/4809 didn't add support for managed we are seeing the error you have.

## next steps
We have 3 options:
- Return to the previous behaviour of erroring for managed GPU Bottlerocket instances
- Specify a custom AMI in the launch template managed nodegroup, and ensure this AMI is the GPU Bottlerocket AMI we use for unmanaged nodegroup
- Specify the AMI type as one that is appropriate for bottlerocket GPU. [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-nodegroup.html#cfn-eks-nodegroup-amitype). Does/will this this exist? This is the simplest option. At the moment I only see `BOTTLEROCKET_ARM_64` and `BOTTLEROCKET_x86_64` as an option, its missing a similar option that exists for GPU, for example AL2 has `AL2_x86_64_GPU`

Looking at the original issue https://github.com/weaveworks/eksctl/issues/4760 it appears we are only intending to add support for unmanaged nodegroups for now? If so then option 1 of erroring (and perhaps suggesting to use an unmanaged nodegroup) seems like the sensible option

**Comment by Himangini** [comment] 2022-03-01 17:51
To summarise after discussion with AWS, we have decided to go for Option 1 
> Return to the previous behaviour of erroring for managed GPU Bottlerocket instances
cc @kdaula @Vaishvenk

**Comment by rothgar** [comment] 2022-03-01 20:28
Thanks for the investigation. I forgot that the CLI created managed nodes by default now so I can use the `--managed=false` option for now until Bottlerocket managed node groups are available.

A clearer error message would be nice to have which I think would help users debug faster.

**Comment by rothgar** [comment] 2022-03-01 20:45
Another limitation I just found testing this. It appears I can't specify my instance types with `--managed=false`

```
eksctl create cluster --name br-gpu \
    --instance-types g4dn.xlarge \
    --node-ami-family Bottlerocket \
    --managed=false
Error: --instance-types is only valid with managed nodegroups (--managed)
```

**Comment by aclevername** [comment] 2022-03-01 20:58
> Another limitation I just found testing this. It appears I can't specify my instance types with `--managed=false`
> 
> 
> 
> ```
> 
> eksctl create cluster --name br-gpu \
> 
>     --instance-types g4dn.xlarge \
> 
>     --node-ami-family Bottlerocket \
> 
>     --managed=false
> 
> Error: --instance-types is only valid with managed nodegroups (--managed)
> 
> ```

I believe there's an alternative flag for unmanaged, --node-type I believe. Will check tomorrow why we restrict that flag for managed

**Comment by rothgar** [comment] 2022-03-01 21:11
> I believe there's an alternative flag for unmanaged, --node-type I believe. Will check tomorrow why we restrict that flag for managed

It might be because self-managed node groups are only allowed to be a single instance type? The ASG could still be multiple types but there may be another reason to limit how many instance types are used for self-managed

**Comment by aclevername** [comment] 2022-03-02 12:44
> It might be because self-managed node groups are only allowed to be a single instance type? The ASG could still be multiple types but there may be another reason to limit how many instance types are used for self-managed

Makes sense!

> * Return to the previous behaviour of erroring for managed GPU Bottlerocket instances

this fix will be out in the next release :smile:

**Closed by aclevername** 2022-03-02 12:44 UTC
Labels: kind/bug, area/nodegroup, needs-investigation, bottlerocket
