### ISSUE TITLE
InvalidParameterException: Cluster is already at the desired configuration

### ISSUE THREAD

**Issue by davivcgarcia** [weaveworks/eksctl#4043] opened 2021-08-02 22:37 UTC
**What were you trying to accomplish?**

I'm trying to boostrap an cluster, configuring endpoint visibility and restriction:

```yaml
vpc:
  nat:
    gateway: HighlyAvailable
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
  publicAccessCIDRs:
    - 0.0.0.0/0
```

**What happened?**

Cluster creation fails, with the following error:

```
2021-08-02 19:25:54 [ℹ]  waiting for requested "EndpointAccessUpdate" in cluster "sandbox" to succeed
2021-08-02 19:25:56 [!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
2021-08-02 19:25:56 [ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-east-1 --name=sandbox'
2021-08-02 19:25:56 [✖]  InvalidParameterException: Cluster is already at the desired configuration with endpointPrivateAccess: true , endpointPublicAccess: true, and Public Endpoint Restrictions: [0.0.0.0/0]
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "266c3cc6-ca48-41e5-80b9-a7c2d1c53bfe"
  },
  ClusterName: "sandbox",
  Message_: "Cluster is already at the desired configuration with endpointPrivateAccess: true , endpointPublicAccess: true, and Public Endpoint Restrictions: [0.0.0.0/0]"
}
Error: failed to create cluster "sandbox"
```

**How to reproduce it?**

1. Get config example at: https://gist.github.com/davivcgarcia/040f66962e9f8e31eb03fbdf09ad97e0
2. Create cluster with `eksctl create cluster -f eksctl-config.yaml 

**Versions**

```
eksctl version: 0.59.0
kubectl version: v1.21.3
OS: darwin
```

**Comment by Callisto13** [comment] 2021-08-03 11:18
Huh that's a funny one. Did this happen the very first time you ran the command with this config? As in: it didn't fail once and you updated something then ran again? There was no stack/cluster with a similar name lying around?

**Comment by davivcgarcia** [comment] 2021-08-03 12:41
> Huh that's a funny one. Did this happen the very first time you ran the command with this config? As in: it didn't fail once and you updated something then ran again? There was no stack/cluster with a similar name lying around?

Yes, the problem happens when I'm creating the cluster (first time running the command). If I try to execute again, it complains the cluster already exists. And no, there is no other cluster with same naming around.

I noticed the problem is related to the `publicAccessCIDRs` configuration. Removing it from the config allowed me to create the cluster.

**Comment by Callisto13** [comment] 2021-08-03 12:48
👍  thanks for confirming

> I noticed the problem is related to the publicAccessCIDRs configuration. Removing it from the config allowed me to create the cluster.

Good to know, we will try to repro. If you get any more data points in the meantime please add to this thread.

**Comment by davivcgarcia** [comment] 2021-09-03 01:50
@Callisto13 do we have any update on this?

**Comment by Callisto13** [comment] 2021-09-07 11:46
Sorry @davivcgarcia we haven't had capacity to look into this yet 😞  It is still on our list

**Comment by Callisto13** [comment] 2021-09-07 11:54
From the looks of it, it seems like the following has happened:

- `publicAccess: true` probably already sets the public CIDR to be `0.0.0.0/0`
- The log line `waiting for requested "EndpointAccessUpdate" in cluster "sandbox" to succeed` seems to be a separate post-create task. So from that I would think that the `publicAccessCIDRs` is not meant to be set as part of a general cluster create, but a separate command to update the CIDRs if you wish to restrict them from the default.

So in the case of your config, it is probably not necessary to set `publicAccessCIDRs` if you aren't changing the default, so this is working as intended.

Obviously that error is annoying and we can probably make it less aggressive so that it logs a simple "No changes to make" warning instead of an all-out "create failed" (the create finished just fine).

**Comment by davivcgarcia** [comment] 2021-09-13 16:55
> * `publicAccess: true` probably already sets the public CIDR to be `0.0.0.0/0`

Yes, looks like the default CIDR is 0.0.0.0/0.

> * The log line `waiting for requested "EndpointAccessUpdate" in cluster "sandbox" to succeed` seems to be a separate post-create task. So from that I would think that the `publicAccessCIDRs` is not meant to be set as part of a general cluster create, but a separate step to update the CIDRs if you wish to restrict them from the default after create completes. (There is also a dedicated command for this `eksctl utils set-public-access-cidrs -f config.yaml`).
> 
> So in the case of your config, it is probably not necessary to set `publicAccessCIDRs` if you aren't changing the default, so this is working as intended.

My original idea was to have a declarative configuration file, explicitiing all options that would be used to create it. That's why I decided to add this value there. This error prevents the rest of the tasks to be executed, like boostrapping FluxCD in the cluster.
 
> Obviously that error is annoying and we can probably make it less aggressive so that it logs a simple "No changes to make" warning instead of an all-out "create failed" (the create finished just fine).

+1

**Comment by Himangini** [comment] 2021-11-15 15:24
Closing this as it's working as intended.

**Closed by Himangini** 2021-11-15 15:24 UTC
Labels: good first issue, kind/improvement
