### ISSUE TITLE
Signifigant clean up after delete cluster needed

### ISSUE THREAD

**Issue by kyprifog** [weaveworks/eksctl#755] opened 2019-04-27 11:25 UTC
**What happened?**
I used eksctl delete cluster and afterwards I found the following still running:
All ec2 instances associated with the kubernetes cluster
All VPC artifacts and NAT gateways associated with the cluster
All cloud formation scripts were still running and provisioned

**What you expected to happen?**
No ec2 instances running
No running NAT gateways
No running cloud formation scripts

**How to reproduce it?**
Spin up a cluster and then delete it using eksctl.

**Anything else we need to know?**
This seems like a big gaff.  By the time I found out my account I was using to play around with eksctl had been charged several hundred dollars.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.29"}
]$ uname -a
Linux chronos 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by errordeveloper** [comment] 2019-04-27 13:32
Did `eksctl delete cluster` exit cleanly? It's not possible for it to exit cleanly and what you described to happen. Beside that, we are aware of a few issue regarding deletions, e.g. #103 and #536.

**Comment by kyprifog** [comment] 2019-05-01 15:02
It did exit cleanly.  It seems like those issues you referenced refers to 2 of the 3 issues I pointed out.  Whats the work around for these until it gets solved?  Ideally I want to be able to delete the cluster and bring it back up quickly to avoid costs.  Maybe I should look into scaling it up and down instead so I dont need to set up my cluster ever time, but then I think there is still quite a bit of daily cost in the VPC (NAT gateways).   What would you recommend to use this tool and minimize the cost?  Right now I'm leaning towards terraform, but I really like how this sets up aws-iam-authenticator for you.

**Comment by rpatrick00** [comment] 2019-05-03 13:59
I had a similar experience.  I ended up with a NAT Gateway, Internet Gateway, ENI, and Elastic IP that were created with eksctl create cluster not being removed by eksctl delete cluster (and continuing to rack up AWS charges for the last two weeks...).

**Comment by kyprifog** [comment] 2019-05-03 15:18
Glad I wasn't the only one.  I forgot to mention I also had a hard time getting everything back down again as well.  This seems like it should be addressed because it makes people that are just playing around with your tool scared to use it.    @errordeveloper it sounds like there is a clear path now that you've laid the groundwork for it.  Could you possibly give a step by step on what needs to be done so someone can take a whack at it?  Thanks!

**Comment by errordeveloper** [comment] 2019-05-03 15:44
Could you please clarify is CloudFormation stacks were still in place in any state?

**Comment by errordeveloper** [comment] 2019-05-03 15:47
> Could you possibly give a step by step on what needs to be done so someone can take a whack at it?

@kyprifog please have a good look at https://github.com/weaveworks/eksctl/issues/536, I can go over it, but Slack or VC would probably be best. I'm in BST, by the way.

**Comment by jvanzyl** [comment] 2019-10-04 14:45
My friend and I both were surprised by bills that we received after deleting a cluster using eksctl. The command exited without error but all the workers were left. In my case I received a bill for US250 and he a bill for US100. Yes, we should have gone to look at the console but afterward but this might be something you want to look into as you might be incurring a lot of cost as it's not expected after a delete command is issued.

**Comment by kyprifog** [comment] 2019-10-16 14:36
@errordeveloper unfortunately I went back to just using kops, but I like what you guys are doing, keep up the good work, i'm curious to see where this goes.

**Comment by mikemountjoy** [comment] 2020-05-17 17:54
Yes also caught out by a significant bill. eksctl left behind cloudformation stacks and attached resources after delete. Poor.

**Comment by michaelbeaumont** [comment] 2020-10-27 15:31
Duplicate of #2172

**Closed by michaelbeaumont** 2020-10-27 15:31 UTC
Labels: area/deletions, awaiting more information, kind/bug, priority/important-soon
