### ISSUE TITLE
EKS cluster name has different regex pattern than eksctl which leads to errors

### ISSUE THREAD

**Issue by ihormudryy** [weaveworks/eksctl#3808] opened 2021-06-04 11:44 UTC
I tried to run command the command for my EKS cluster e.g bla_bla_bla which was legitimately created:
`eksctl create iamserviceaccount \
    --name iam-test \
    --namespace default \
    --cluster bla_bla_bla \
    --attach-policy-arn arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess \
    --approve \
    --override-existing-serviceaccounts
`

got error 
`2021-06-04 13:36:55 [✖]  creating CloudFormation stack "eksctl-Privacy_Solution_Services-addon-iamserviceaccount-default-iam-test": ValidationError: 1 validation error detected: Value 'eksctl-bla_bla_bla-addon-iamserviceaccount-default-iam-test' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*
	status code: 400, request id: 41c59bfd-c2e9-4eef-a045-d22ec3fc8ac6
Error: failed to create iamserviceaccount(s)
`

EKS cluster names allow other characters than dash only, so it leads to potential errors and it is not possible to change EKS name after it's created.

**Comment by Callisto13** [comment] 2021-06-04 15:04
Hi @ihormudryy thanks for reporting.

The error is coming from the CloudFormation API which annoyingly does not allow underscore characters. I believe eksctl recently merged work which sanitises cluster names so that we do not hit this error, could you tell me your eksctl version please?

**Comment by ihormudryy** [comment] 2021-06-04 16:08
Hi Claudia,

thanks for the quick reply! My version is 0.52.0

**Comment by Callisto13** [comment] 2021-06-04 16:10
okay that is very recent. I will try to find out where the work went and do a quick PR if it never made it in

**Comment by Callisto13** [comment] 2021-06-07 08:43
gah, we never did the work https://github.com/weaveworks/eksctl/issues/2943 🤦‍♀️  my bad, we will get to it asap

**Comment by Callisto13** [comment] 2021-06-11 08:38
Closing, please see https://github.com/weaveworks/eksctl/issues/2943#issuecomment-859390934

**Closed by Callisto13** 2021-06-11 08:38 UTC
Labels: good first issue

**Comment by slobo** [comment] 2021-12-02 01:27
Sorry to resurrect this, hoping it's less noise than new ticket, but is the conclusion that `eksctl` has no intention of supporting `iamserviceaccount` when there is underscore in the cluster name?

In other words, are we SOL trying to follow instructions that recommend `eksctl` with our `_` named clusters?

**Comment by Skarlso** [comment] 2021-12-02 07:08
@slobo The problem is not on `eksctl` side, but on CloudFormation not allowing anything with an `_` in it. So no. We are not supporting `_` in names as of right now.
