### ISSUE TITLE
Eksctl get nodegroup fails to describe nodes 

### ISSUE THREAD

**Issue by ajayk** [weaveworks/eksctl#3910] opened 2021-06-28 23:27 UTC
**What were you trying to accomplish?**
```
eksctl get nodegroups   --cluster my-cluster  --region us-west-2
```

**What happened?**
```
2021-06-28 16:18:52 [ℹ]  eksctl version 0.54.0
2021-06-28 16:18:52 [ℹ]  using region us-west-2
Error: getting nodegroup's kubernetes version: failed to list nodes: no nodes were found
```

**How to reproduce it?**
This bug was introduced in 0.54.0 as not seeing on earlier versions of eksctl , we had to revert back to 0.53.0 

**Versions**
0.54.0

**Comment by Callisto13** [comment] 2021-06-29 08:12
I believe this is a dupe of https://github.com/weaveworks/eksctl/issues/3894 which was fixed in `0.55.0-rc.0`. Please re-open if it is something else.

**Closed by Callisto13** 2021-06-29 08:12 UTC
Labels: kind/bug
