### ISSUE TITLE
Support m6g instance type in node group

### ISSUE THREAD

**Issue by walkley** [weaveworks/eksctl#2302] opened 2020-06-08 13:24 UTC
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
EKS User Guide has documented the instance type of a1 and m6g in the ARM support:
https://docs.aws.amazon.com/eks/latest/userguide/arm-support.html

**What feature/behavior/change do you want?**
Support instance type as m6g for node group.

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".

**Comment by michaelbeaumont** [comment] 2020-06-09 17:16
Duplicate of https://github.com/weaveworks/eksctl/issues/1949

**Closed by michaelbeaumont** 2020-06-09 17:16 UTC
Labels: kind/feature
