### ISSUE TITLE
update policies on existing serviceaccounts not updating

### ISSUE THREAD

**Issue by cdenneen** [weaveworks/eksctl#2739] opened 2020-10-14 16:19 UTC
Running 0.28.1 tried to add 4th policy to the attachPolicyARNs for the serviceAccounts in the eksctl Config.
Ran as `eksctl create iamserviceaccount --approve --override-existing-serviceaccounts` but the 4 service accounts that should have been "updated" did not show up.

Reviewing the existing roles that match those 4 service accounts I can confirm that only the old 3 policies are attached to the roles.

So need to know why the 4 serviceaccounts that should be updated are not being updated.

Possible related issues:
#1497
#2665

**Comment by michaelbeaumont** [comment] 2020-10-16 12:10
Thanks @cdenneen. I want to track this in #1497, so I'm going to close this issue.

**Comment by michaelbeaumont** [comment] 2020-10-16 12:10
Duplicate of #1497

**Closed by michaelbeaumont** 2020-10-16 12:10 UTC
Labels: kind/bug, priority/important-soon
