### ISSUE TITLE
Import values from other cloudformation templates automatically to cluster config .yaml

### ISSUE THREAD

**Issue by jsidney** [weaveworks/eksctl#3304] opened 2021-02-18 11:40 UTC
**What feature/behavior/change do you want?**
 is there a way of letting eksctl reference exported values from other cloudformation templates in its setup?
for example, i have a nested template that is setting up the following resources for my app:
a vpc with all the required routing and security etc
storage layer (rds, efs, etc)
other resources (logging, ecr, etc)
iam (cluster and node group roles etc)
it would be really awesome if i could just reference the exported outputs from those templates in eksctl instead of manually copy and pasting the values from cloudformation into my cluster's yaml definition

Traditionally, with other cloudformation templates, you could use the `Fn::ImportValue` function to import ARNS, domain names etc to a new stack.

**Why do you want this feature?**
in many big organisations, certain areas of AWS are the domain of specific teams (ie: vpc creation belongs to a network team etc). In many situations, they will provision resources using tools such as AWS ControlTower and ServiceCatalogue. In these cases, the cloudformation templates are in the account, but eksctl requires hard-coding (ie: copy pasting) arns, ids and the like into your cluster config yaml. This can lead to:
* copy-pasta errors
* wasted time looking for updates etc
* essentially 2 separate sources of truth - your eksctl config and the other cloudformation templates. this can cause troubles when upgrades to resources take place (eg: a role ARN changes or a security group id changes). in this case, you would have to modify your eksctl yaml before running any upgrades. 

Making this change could allow for a quicker and easier path for integrating an eks cluster into the broader aws environment in question

**Comment by michaelbeaumont** [comment] 2021-02-18 12:56
Duplicate of https://github.com/weaveworks/eksctl/issues/1141

**Closed by michaelbeaumont** 2021-02-18 12:56 UTC
Labels: kind/feature
