### ISSUE TITLE
managedNodeGroups define isntanceType in created LaunchTemplate

### ISSUE THREAD

**Issue by jimmyraywv** [weaveworks/eksctl#4147] opened 2021-08-29 20:05 UTC
I am using `eksctl` with a config file to create a cluster and 1 managed node group.
```
managedNodeGroups:
  - name: mng-1
    labels:
      node-group: mng-1
      owner: jimmy
      role: managed-worker
      env: dev
      billing: lob-cc
    instanceType: t3.small
...
```

I realize that under the covers, a launch template is created, but the `LaunchTemplate:LaunchTemplateData:InstanceType` is missing. Instead, the `ManagedNodeGroup:Properties:InstanceTypes` string array is added, and contains one entry for the instance type that I specified in the `managedNodeGroups` instance element. The end result is a launch template without an instance type.

Is this by design? Is there a way to force the launch template to specify the `LaunchTemplate:LaunchTemplateData:InstanceType` element, short of using a custom launch template?

**Comment by cPu1** [comment] 2021-08-30 07:51
>Is this by design? 

This is indeed by design. Launch templates do not support specifying multiple instance types but the Managed Nodegroups API does, so for consistency, eksctl always passes the specified instance type(s) to the CreateNodegroup API instead of setting it in the launch template. 

>Is there a way to force the launch template to specify the LaunchTemplate:LaunchTemplateData:InstanceType element, short of using a custom launch template?

There isn't. You'll have to use a custom launch template. May I ask what problem you're trying to address by having the instance type set in the launch template? Are you trying to launch EC2 instances manually using the eksctl-created launch template?

**Comment by jimmyraywv** [comment] 2021-08-30 13:44
@cPu1 I stumbled across it when I was looking at Warm Pools. The launch template was missing the instance type. Thanks for the quick response.

**Comment by cPu1** [comment] 2021-09-30 08:16
Closing this, please feel free to open a new issue if you have more questions.

**Closed by cPu1** 2021-09-30 08:16 UTC
Labels: kind/help
