### ISSUE TITLE
Integration test failure for managed_nodegroup_test

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#4228] opened 2021-09-17 14:58 UTC
The test case `should return the previously created cluster` failed with a timeout error. A minute may not be enough time for listing clusters in all regions, so we should consider either increasing the timeout, or removing the `all-regions` argument. 

```
Logs:

• Failure [60.002 seconds]
(Integration) Create Managed Nodegroups
/__w/eksctl/eksctl/integration/tests/managed/managed_nodegroup_test.go:56
  cluster with 1 managed nodegroup
  /__w/eksctl/eksctl/integration/tests/managed/managed_nodegroup_test.go:226
    and listing clusters
    /__w/eksctl/eksctl/integration/tests/managed/managed_nodegroup_test.go:248
      should return the previously created cluster [It]
      /__w/eksctl/eksctl/integration/tests/managed/managed_nodegroup_test.go:249

      Timed out after 60.000s.
      Expected process to exit.  It did not.

      /__w/eksctl/eksctl/integration/runner/runner.go:125
```

**Comment by tanvp112** [comment] 2021-09-18 02:58
`eksctl get cluster --all-regions --timeout 30m`

Very helpful command to provide a global views of all clusters, it ran 43s on my laptop.

**Comment by cPu1** [comment] 2021-11-24 07:27
Not stale!

**Comment by Himangini** [comment] 2021-11-24 14:11
increase timeout should fix this :)

**Comment by Skarlso** [comment] 2021-11-26 10:02
Are there any logs of a failure to investigate further? Otherwise, I'll just increase the timeout if you are sure that is the root cause @cPu1

**Comment by Skarlso** [comment] 2021-11-26 10:03
Also, it's pretty sus for a `list` command to time out after a full minute...

**Comment by Skarlso** [comment] 2021-11-26 10:05
Unless that's not the actual command that timed out. But I can't find a failed log to investigate.

**Comment by Skarlso** [comment] 2021-11-26 15:07
This didn't occur for a long time now. So will close this for now. If this test fails again, we'll reopen this thing or just open a new ticket.

**Closed by Skarlso** 2021-11-26 15:07 UTC
Labels: kind/bug
