### ISSUE TITLE
[Bug] SSH public key already exists, but fingerprints don't match

### ISSUE THREAD

**Issue by rtsp** [weaveworks/eksctl#5145] opened 2022-04-21 20:21 UTC
### What were you trying to accomplish?

Create an **additional** managedNodeGroups.

### What happened?

eksctl failed to create new nodegroup after trying to verify existing key on AWS.

```
$ eksctl create nodegroup -f cluster.yaml
2022-04-22 02:59:43 [ℹ]  eksctl version 0.93.0
2022-04-22 02:59:43 [ℹ]  using region ap-southeast-1
2022-04-22 02:59:45 [ℹ]  nodegroup "ops-spot-v22-1" will use "" [AmazonLinux2/1.22]
2022-04-22 02:59:45 [ℹ]  using SSH public key "../ssh/redacted.pub" as "eksctl-redacted-nodegroup-ops-spot-v22-1-eeeId+MO8TpTv2M/qAi8ElhBPHBSX0xXMhR08c6NK+Q"
Error: SSH public key eksctl-redacted-nodegroup-ops-spot-v22-1-eeeId+MO8TpTv2M/qAi8ElhBPHBSX0xXMhR08c6NK+Q already exists, but fingerprints don't match (exected: "eeeId+MO8TpTv2M/qAi8ElhBPHBSX0xXMhR08c6NK+Q", got: "eeeId+MO8TpTv2M/qAi8ElhBPHBSX0xXMhR08c6NK+Q=")
```

Note the diference

- `eeeId+MO8TpTv2M/qAi8ElhBPHBSX0xXMhR08c6NK+Q` expected
- `eeeId+MO8TpTv2M/qAi8ElhBPHBSX0xXMhR08c6NK+Q=` got

Actual fingerprint from `ssh-keygen`

```
$ ssh-keygen -lf ../ssh/redacted.pub
256 SHA256:eeeId+MO8TpTv2M/qAi8ElhBPHBSX0xXMhR08c6NK+Q redacted (ED25519)
```

Actual key is

```
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFKnzVJT1WfvmjMePdRUU+np823aaaSCoAZxmuiOQ/fB
```

### How to reproduce it?

Use my key to create cluster twice would fail on 2nd time.

**Logs**

See above

**Anything else we need to know?**

The function that failed is here

https://github.com/weaveworks/eksctl/blob/518cac9379e07d5b06dae91486e61bc647b163db/pkg/ssh/client/ssh.go#L131-L141

**Versions**

```
$ eksctl info
eksctl version: 0.93.0
kubectl version: v1.23.5
OS: linux
```

**Comment by rtsp** [comment] 2022-04-21 21:13
![image](https://user-images.githubusercontent.com/314429/164552890-6efcb9d0-b726-4197-9cc2-e56f4baa3243.png)

Seems like AWS actually return key with `=` character.

Now I'm not sure which fingerprint is correct:

- AWS (with `=`)
- `ssh-keygen` (without `=`)
- Or both?

**Comment by nikimanoledaki** [comment] 2022-04-22 09:31
Thanks @rtsp, someone from the team or I will investigate this and get back to you :)

**Comment by Skarlso** [comment] 2022-04-22 09:42
I bet it's a linebreak.

**Comment by Skarlso** [comment] 2022-04-22 09:46
@rtsp Can you please post the configuration file and how you define the key? Are you using file or pasted in SSH?

**Comment by Skarlso** [comment] 2022-04-22 10:00
BTW, I tested the key import from AWS. They add the padding to it for some reason. I created a brand new key with fingerprint:

```
64OuseEfObM7yYiEyK7u42qN1kHj6/JGnpro1XqO4pM
```

And AWS generated the fingerprint:

```
64OuseEfObM7yYiEyK7u42qN1kHj6/JGnpro1XqO4pM=
```

So, they add the extra padding for some reason.

**Comment by rtsp** [comment] 2022-04-22 10:02
> @rtsp Can you please post the configuration file and how you define the key? Are you using file or pasted in SSH?

From file

``` yaml
    ssh:
      allow: true
      publicKeyPath: ../ssh/redacted.pub
```

`../ssh/redacted.pub`
```
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEi+o5lkuUmMwpYCN4ZmaQnYJG/hdpks2ykGieEGA8Kn redacted
```

**Comment by Skarlso** [comment] 2022-04-22 10:03
>      publicKeyPath: ../ssh/redacted.pub

Would you mind making this an absolute path, please? Just for the sake of trying. :) Also, I assume permission on the file are `0400`?

**Comment by rtsp** [comment] 2022-04-22 10:11
> > ```
> >  publicKeyPath: ../ssh/redacted.pub
> > ```
> 
> Would you mind making this an absolute path, please? Just for the sake of trying. :) Also, I assume permissions on the file are `0400`?

Actually it's 0640 (because it's public key)

But for the sake of trying. I've chmod to 400 and try both same dir and absolute path as requested.

```
-rw-r--r-- 1 kubernetes kubernetes 4.3K 2022-04-22 07:05 cluster.yaml
-r-------- 1 kubernetes kubernetes  182 2022-04-22 17:05 redacted.pub
```

Problem still occur 😂 
```
    ssh:
      allow: true
      publicKeyPath: redacted.pub
```
```
2022-04-22 17:07:55 [ℹ]  using SSH public key "redacted.pub" as "eksctl-redacted-nodegroup-ops-spot-v22-1-eeeId+MO8TpTv2M/qAi8ElhBPHBSX0xXMhR08c6NK+Q"
Error: SSH public key eksctl-redacted-nodegroup-ops-spot-v22-1-eeeId+MO8TpTv2M/qAi8ElhBPHBSX0xXMhR08c6NK+Q already exists, but fingerprints don't match (exected: "eeeId+MO8TpTv2M/qAi8ElhBPHBSX0xXMhR08c6NK+Q", got: "eeeId+MO8TpTv2M/qAi8ElhBPHBSX0xXMhR08c6NK+Q=")
```

```
    ssh:
      allow: true
      publicKeyPath: /home/kubernetes/kubernetes/redacted/eks/redacted.pub
```
```
2022-04-22 17:09:33 [ℹ]  using SSH public key "/home/kubernetes/kubernetes/redacted/eks/redacted.pub" as "eksctl-redacted-nodegroup-ops-spot-v22-1-eeeId+MO8TpTv2M/qAi8ElhBPHBSX0xXMhR08c6NK+Q"
Error: SSH public key eksctl-redacted-nodegroup-ops-spot-v22-1-eeeId+MO8TpTv2M/qAi8ElhBPHBSX0xXMhR08c6NK+Q already exists, but fingerprints don't match (exected: "eeeId+MO8TpTv2M/qAi8ElhBPHBSX0xXMhR08c6NK+Q", got: "eeeId+MO8TpTv2M/qAi8ElhBPHBSX0xXMhR08c6NK+Q=")
```

**Comment by rtsp** [comment] 2022-04-22 10:14
> OH! AWS is using a different fingerprint. That won't match ssh-keygen fingerprint.

Look like it's the padding in base64 spec that isn't a hard requirement for decoding.

I think changing this to substring check or trim the `=` padding out before checking should fix this issue. 😄

**Comment by Skarlso** [comment] 2022-04-22 10:21
>I think changing this to substring check or trim the = padding out before checking should fix this issue. 😄

Sure, it would fix the immediate problem, but we don't know about the cause. :) We can't just patch and move on. :D

I think it actually might on `eksctl` side, since we might be using an incorrect algorithm. I think we should try and use the AWS fingerprinting. Or, I don't know...  I mean, if this wouldn't be working, there would be a lot more issues about it, right?

**Comment by Skarlso** [comment] 2022-04-22 10:22
I mean, this was tested here https://github.com/weaveworks/eksctl/pull/4835 and worked apparently.. :D

**Comment by Skarlso** [comment] 2022-04-22 10:33
So if I generate a local key, import it, and point my config like this:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gb-test-ssh
  region: us-west-2
  version: '1.21'

managedNodeGroups:
  - name: mng-1
    minSize: 1
    desiredCapacity: 1
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_ed25519.pub
```

It does work and creates the cluster:

```
2022-04-22 12:32:22 [ℹ]  using SSH public key "/Users/skarlso/.ssh/id_ed25519.pub" as "eksctl-gb-test-ssh-nodegroup-mng-1-DF3hnpZAPYvtyUJvhKXDz0x/eMWN828yE8ObUpTU06I"
2022-04-22 12:32:23 [ℹ]  using Kubernetes version 1.21
2022-04-22 12:32:23 [ℹ]  creating EKS cluster "gb-test-ssh" in "us-west-2" region with managed nodes
2022-04-22 12:32:23 [ℹ]  1 nodegroup (mng-1) was included (based on the include/exclude rules)
2022-04-22 12:32:23 [ℹ]  will create a CloudFormation stack for cluster itself and 0 nodegroup stack(s)
2022-04-22 12:32:23 [ℹ]  will create a CloudFormation stack for cluster itself and 1 managed nodegroup stack(s)
2022-04-22 12:32:23 [ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-west-2 --cluster=gb-test-ssh'
```

**Comment by Skarlso** [comment] 2022-04-22 10:35
Now waiting for it to complete so I create an **additional** nodegroup.

**Comment by rtsp** [comment] 2022-04-22 10:46
According to [RFC 4648](https://datatracker.ietf.org/doc/html/rfc4648#section-4) base64 padding is depend on input length and SSH key fingerprint length always need one `=` padding character.

as It's not required by spec so ssh-keygen, go and AWS may treat this padding differently but in the end it's identical so I think it's safe to trim those padding character out.

**Comment by Skarlso** [comment] 2022-04-22 10:55
Reproduced:

```
2022-04-22 12:53:38 [ℹ]  using SSH public key "/Users/skarlso/.ssh/id_ed25519.pub" as "eksctl-gb-test-ssh-nodegroup-mng-1-DF3hnpZAPYvtyUJvhKXDz0x/eMWN828yE8ObUpTU06I"
Error: SSH public key eksctl-gb-test-ssh-nodegroup-mng-1-DF3hnpZAPYvtyUJvhKXDz0x/eMWN828yE8ObUpTU06I already exists, but fingerprints don't match (exected: "DF3hnpZAPYvtyUJvhKXDz0x/eMWN828yE8ObUpTU06I", got: "DF3hnpZAPYvtyUJvhKXDz0x/eMWN828yE8ObUpTU06I=")
```

> I think it's safe to trim those padding character

I don't think that is the source of this bug. :) But it definitely an option. I think we are just doing something wonky on nodegroup creation with an existing key in the create nodegroup command path.

**Comment by rtsp** [comment] 2022-04-22 11:02
I've confirm the difference with newly generated key.

AWS always render key with padding

![image](https://user-images.githubusercontent.com/314429/164701825-62259462-3ad8-40c4-862b-07668622a8cc.png)

ssh-keygen always not

```
$ ssh-keygen -lf tested.pub
256 SHA256:UlJQcibErkbUBknfUbO9bFXdwoDJmH3HwtXlmYtOhPY no comment (ED25519)
```

I'm not sure for Golang but I bet it same as ssh-keygen 😂
Here's the code computing local fingerprint

https://github.com/weaveworks/eksctl/blob/518cac9379e07d5b06dae91486e61bc647b163db/pkg/ssh/client/ssh.go#L51-L67

**Comment by Skarlso** [comment] 2022-04-22 11:10
Oh. I understand what's going on :/ It's a bit.. eh. So it didn't die at first because it imported the key under a different name even if the key already existed. And then, on the second go, it was trying to use the same key and that's when it actually compared the fingerprint and failed. So our testing didn't reveal this because we didn't use the same key again on a second creation attempt.

Nice catch. Eventually, I think you're right. We should just trim the padding and add a clear document that we do so. This is an unfortunate situation.

**Comment by rtsp** [comment] 2022-04-22 11:11
I think I found root function that compute this fingerprint and it's intended to be unpadded.

> // fingerprint as unpadded base64 encoded sha256 hash.
in 
https://github.com/kubernetes/kops/blob/fad75ec278d1bf6ff1111b929d773cbf5a4ab69f/vendor/golang.org/x/crypto/ssh/keys.go#L1474-L1483

**Comment by Skarlso** [comment] 2022-04-22 11:12
Yeah trimming won't work in case of MD5 RSA SSH2 hashes....

**Comment by Skarlso** [comment] 2022-04-22 11:13
> I think I found root function that compute this fingerprint and it's intended to be unpadded.
> 
> > // fingerprint as unpadded base64 encoded sha256 hash.
> 
> https://github.com/kubernetes/kops/blob/fad75ec278d1bf6ff1111b929d773cbf5a4ab69f/vendor/golang.org/x/crypto/ssh/keys.go#L1474-L1483

Yep, that's the same we are using.

**Comment by Skarlso** [comment] 2022-04-22 11:15
@rtsp Can you test with a non ed25519 key please? I think we might be in the clear for those as we are using this:

```go
fingerprint, err := pki.ComputeAWSKeyFingerprint(string(key))
```

to compute those.

**Comment by rtsp** [comment] 2022-04-22 11:28
@Skarlso 

Yep. I tested on differernt cluster and the RSA key works fine. 

```
$ eksctl create nodegroup -f cluster-init.yml
2022-04-22 18:24:48 [ℹ]  eksctl version 0.93.0
2022-04-22 18:24:48 [ℹ]  using region ap-southeast-1
2022-04-22 18:24:51 [ℹ]  nodegroup "core-b-v21-1" will use "" [AmazonLinux2/1.21]
2022-04-22 18:24:51 [ℹ]  using SSH public key "../../ssh/redacted.pub" as "eksctl-redacted-cluster-nodegroup-core-b-v21-1-94:29:3b:32:1d:8d:19:d4:b2:b5:6a:ce:9c:bc:24:66"
2022-04-22 18:24:51 [ℹ]  nodegroup "prod-b-v21-1" will use "" [AmazonLinux2/1.21]
2022-04-22 18:24:51 [ℹ]  using SSH public key "../../ssh/redacted.pub" as "eksctl-redacted-cluster-nodegroup-prod-b-v21-1-94:29:3b:32:1d:8d:19:d4:b2:b5:6a:ce:9c:bc:24:66"
2022-04-22 18:24:51 [ℹ]  nodegroup "prod-b-v21-1-spot" will use "" [AmazonLinux2/1.21]
2022-04-22 18:24:51 [ℹ]  using SSH public key "../../ssh/redacted.pub" as "eksctl-redacted-cluster-nodegroup-prod-b-v21-1-spot-94:29:3b:32:1d:8d:19:d4:b2:b5:6a:ce:9c:bc:24:66"
2022-04-22 18:24:51 [ℹ]  nodegroup "dev-b-v21-1-spot" will use "" [AmazonLinux2/1.21]
2022-04-22 18:24:51 [ℹ]  using SSH public key "../../ssh/redacted.pub" as "eksctl-redacted-cluster-nodegroup-dev-b-v21-1-spot-94:29:3b:32:1d:8d:19:d4:b2:b5:6a:ce:9c:bc:24:66"
2022-04-22 18:24:52 [ℹ]  4 existing nodegroup(s) (core-b-v21-1,dev-b-v21-1-spot,prod-b-v21-1,prod-b-v21-1-spot) will be excluded
```

**Comment by Skarlso** [comment] 2022-04-22 11:36
This feels so wrong. :D I can't fathom why they would do this... Trimming is also tricky since we could accidentally remove intentionally added padding!

Also, this is a breaking change. We use the fingerprint as part of the keyname. If I change the fingerprint to match with AWS we break using existing keys and existing clusters using SSH.

Sorry, for now, please try using a different keytype. This needs a bit more... fines. Or fingerspitzengefühl. :)

**Comment by rtsp** [comment] 2022-04-22 12:13
![image](https://user-images.githubusercontent.com/314429/164710953-2f905e2f-9803-43d3-bd67-fe030b9e46ff.png)

AWS choose base64(sha256) fingerprint for Ed25519 key and Hex fingerprint for RSA.

I don't understand why they choose this but this is why there's no trimming problem for RSA at all.

---

> Also, this is a breaking change. We use the fingerprint as part of the keyname. If I change the fingerprint to match with AWS we break using existing keys and existing clusters using SSH.

May be we only trim to use in comparison (this line) and keep the rest as before?

https://github.com/weaveworks/eksctl/blob/518cac9379e07d5b06dae91486e61bc647b163db/pkg/ssh/client/ssh.go#L135


> Sorry, for now, please try using a different keytype. This needs a bit more... finesse. Or fingerspitzengefühl. :)

No problem. I already switched to RSA 😂

**Comment by rtsp** [comment] 2022-04-22 12:15
BTW, for permanent fix I think we may need to do at [kops](https://github.com/kubernetes/kops/blob/fad75ec278d1bf6ff1111b929d773cbf5a4ab69f/pkg/pki/sshkey.go#L69-L89) instead.

If this function intended to compute AWS key fingerprint and use with AWS. I think it should include padding to ensure that it's identical to the AWS API responses.

```go
// ComputeAWSKeyFingerprint computes the AWS-specific fingerprint of the SSH public key
func ComputeAWSKeyFingerprint(publicKey string) (string, error) {
	sshPublicKey, err := parseSSHPublicKey(publicKey)
	if err != nil {
		return "", err
	}

	switch fmt.Sprintf("%T", sshPublicKey) {
	case "*ssh.rsaPublicKey":
		der, err := rsaToDER(sshPublicKey)
		if err != nil {
			return "", fmt.Errorf("error computing fingerprint for SSH public key: %v", err)
		}
		h := md5.Sum(der)
		return colonSeparatedHex(h[:]), nil
	case "ssh.ed25519PublicKey":
		return ssh.FingerprintSHA256(sshPublicKey), nil
	}

	return "", fmt.Errorf("unexpected type of SSH key (%T); AWS can only import RSA and ed25519 keys", sshPublicKey)
}
```

**Comment by Skarlso** [comment] 2022-04-22 12:26
>May be we only trim to use in comparison (this line) and keep the rest as before?

I'm reluctant to delete otherwise we could delete intentional padding, right? But if we add it to ours, we'll have to check the key type there so we don't add it to MD5 hashes. That's a bit of code shuffling then.

>If this function intended to compute AWS key fingerprint and use with AWS. I think it should include padding to ensure that it's identical to the AWS API responses.

Yeah, we added that part of the code :D That's using the same thing but we added to eksctl first so we can support it before kops merged and released it. :)

**Comment by rtsp** [comment] 2022-04-22 13:01
> But if we add it to ours, we'll have to check the key type there so we don't add it to MD5 hashes. That's a bit of code shuffling then.

Yeah, that's why I lured to trimming `=` out instead because RSA key fingerprint (from AWS) is in hex format so it's safe to trim it away.

Also, the  `existing.KeyFingerprint` (from AWS, with padding) is only used in this function and used for comparison only so I guess it's pretty safe to modify it. 😄 

But for modifying `pki.ComputeAWSKeyFingerprint`, I think it would break a lot since it used many place such as `getKeyName`.

**Comment by Skarlso** [comment] 2022-04-22 13:22
>Yeah, that's why I lured to trimming = out instead because RSA key fingerprint (from AWS) is in hex format so it's safe to trim it away without breaking RSA fingerprint (from AWS).

What I'm talking about that if there are `=` because there was a spare byte in the key and the `=` is equally part of the base64 code, we would also trim that.

**Comment by Skarlso** [comment] 2022-04-22 13:32
What I'm trying to say is that I'm not sure that they are adding the extra padding because of encoding or they are just always doing a `string+"="` if that makes sense?

**Comment by Skarlso** [comment] 2022-04-22 14:27
>fingerprint is a base64 of sha256

When you say that this comes to me like you say they took the sha256 generated fingerprint then run a base64 on it. Which is not the result we are seeing, right? :) Or do you mean something else?

Yeah I saw that they are using sha256 on ed25519 instead of MD5. They do that because of a weird thing where they double convert from openssl or something like that. And they don't do that to ed25519.

**Comment by Skarlso** [comment] 2022-04-22 14:32
I guess, in the end, it doesn't matter. It's a single word, and we aren't concatenating it to anything, so even if there is extra padding, it wouldn't matter.

**Comment by rtsp** [comment] 2022-04-22 15:00
> > fingerprint is a base64 of sha256
> 
> When you say that this comes to me like you say they took the sha256 generated fingerprint then run a base64 on it. Which is not the result we are seeing, right? :) Or do you mean something else?

Yes this is correct.

But now I know why you're confusing because when I trying to redact sensitive information, I pasted wrong key to the topic. The correct key that I have a problem with is `AAAAC3NzaC1lZDI1NTE5AAAAIFKnzVJT1WfvmjMePdRUU+np823aaaSCoAZxmuiOQ/fB` and it's fingerprint is  `eeeId+MO8TpTv2M/qAi8ElhBPHBSX0xXMhR08c6NK+Q=`

You can calculating the key fingerprint by running this command, and it have a padding char. 😄 

```
$ echo 'AAAAC3NzaC1lZDI1NTE5AAAAIFKnzVJT1WfvmjMePdRUU+np823aaaSCoAZxmuiOQ/fB' | base64 -w0 -d | openssl dgst -binary -sha256 | base64 -w0; echo
eeeId+MO8TpTv2M/qAi8ElhBPHBSX0xXMhR08c6NK+Q=
```

**Comment by cPu1** [comment] 2022-05-09 11:11
Both AWS and eksctl use the same algorithm to generate the fingerprint for Ed25519 keys, but the Go implementation uses an unpadded base64 encoding (`base64.RawStdEncoding`), which is why the eksctl-generated fingerprint has no padding (`=`).

Go's implementation is more in line with [OpenSSH](https://www.openssh.com/txt/release-6.8):

```
 * Add FingerprintHash option to ssh(1) and sshd(8), and equivalent
   command-line flags to the other tools to control algorithm used
   for key fingerprints. The default changes from MD5 to SHA256 and
   format from hex to base64.

   Fingerprints now have the hash algorithm prepended. An example of
   the new format: SHA256:mVPwvezndPv/ARoIadVY98vAC0g+P/5633yTC4d/wXE
   Please note that visual host keys will also be different.
```

**Closed** 2022-05-09 11:29 UTC
Labels: kind/bug
