### ISSUE TITLE
Reduce the number of external API calls

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#2946] opened 2020-12-15 12:31 UTC
We have recently started to have some API calls throttled (to cloudformation mostly).

Work done as part of https://github.com/weaveworks/eksctl/issues/2174 has likely contributed heavily to this, but it has also been casually noticed that we are perhaps making many more calls than we need to, and this has been made opaque in general code sprawl.

This issue is about optimising our code to keep API calls to a minimum. (This is likely a large task, and will require some refactoring. Break into smaller chunks if needed.)

**Comment by aclevername** [comment] 2021-01-14 15:54
I'm going to investigate the CFN calls around `eksctl get clusters` first as this appears to cause a lot of throttling

**Comment by aclevername** [comment] 2021-01-14 16:13
for 16 EKS clusters we issue 44 `DescribeStack` calls to cloudformation.  This is most likely the cause of the throttling:
```
./eksctl get clusters
[ℹ]  eksctl version 0.37.0-dev+66708d31.2021-01-14T16:08:13Z
[ℹ]  using region us-west-2
[!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: 5afb05e4-c9fe-44f4-b526-2c5066392088) from cloudformation/DescribeStacks - will retry after delay of 925.223147ms
[ℹ]  DescribeCount: 44
```

**Comment by aclevername** [comment] 2021-01-27 15:40
a lot of throttling during `create/delete nodegroup`

```
./eksctl33 create nodegroup -f cluster.yaml
[ℹ]  eksctl version 0.33.0
[ℹ]  using region us-west-2
[ℹ]  will use version 1.18 for new nodegroup(s) based on control plane version
[!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: 95edf075-631b-4908-82d1-af199846011a) from cloudformation/DescribeStacks - will retry after delay of 522.72417ms
[ℹ]  nodegroup "spot-managed-node-group" present in the cluster, but missing from the given config
[ℹ]  nodegroup "ng-managed" present in the cluster, but missing from the given config
[ℹ]  nodegroup "ng-c292c102" present in the cluster, but missing from the given config
[ℹ]  4 existing nodegroup(s) (ng-c292c102,ng-managed,spot-managed-node-group,spot-managed-node-group-2) will be excluded
[ℹ]  2 sequential tasks: { fix cluster compatibility, no tasks }
[ℹ]  checking cluster stack for missing resources
[!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: 5f98052f-c5d6-4472-98ed-c26e217ca587) from cloudformation/DescribeStacks - will retry after delay of 594.329443ms
[ℹ]  cluster stack has all required resources
[ℹ]  no tasks
[✔]  created 0 nodegroup(s) in cluster "jk"
[✔]  created 0 managed nodegroup(s) in cluster "jk"
[!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: 88f6ddf9-d1b4-4756-b455-715e774b2030) from cloudformation/DescribeStacks - will retry after delay of 760.9655ms
[ℹ]  checking security group configuration for all nodegroups
[ℹ]  all nodegroups have up-to-date configuration
```

```
./eksctl delete nodegroup -f cluster.yaml
[ℹ]  eksctl version 0.38.0-dev+16e9c8ef.2021-01-27T14:45:31Z
[ℹ]  using region us-west-2
[ℹ]  comparing 0 nodegroups defined in the given config ("cluste.yaml") against remote state
[ℹ]  1 nodegroup (spot-managed-node-group) was included (based on the include/exclude rules)
[ℹ]  (plan) would drain 1 nodegroup(s) in cluster "jk"
[ℹ]  (plan) would delete 1 nodegroups from cluster "jk"
[!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: 3852bfd0-6782-4f28-9981-64743043e04e) from cloudformation/DescribeStacks - will retry after delay of 961.154192ms
[!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: bc3bdc76-cd9a-4d57-b434-e626cb35d88a) from cloudformation/DescribeStacks - will retry after delay of 972.906537ms
[ℹ]  (plan) 1 task: { delete unowned nodegroup "spot-managed-node-group" }
[ℹ]  (plan) would delete 0 nodegroups from auth ConfigMap in cluster "jk"
[✔]  (plan) would have deleted 1 nodegroup(s) from cluster "jk"
[!]  no changes were applied, run again with '--approve' to apply the changes
(log-remaining-stacks → origin {6} ?:2 ✗) eksctl ./eksctl delete nodegroup -f cluste.yaml --approve
[ℹ]  eksctl version 0.38.0-dev+16e9c8ef.2021-01-27T14:45:31Z
[ℹ]  using region us-west-2
[ℹ]  comparing 0 nodegroups defined in the given config ("cluste.yaml") against remote state
[ℹ]  1 nodegroup (spot-managed-node-group) was included (based on the include/exclude rules)
[ℹ]  will drain 1 nodegroup(s) in cluster "jk"
[!]  no nodes found in nodegroup "spot-managed-node-group" (label selector: "alpha.eksctl.io/nodegroup-name=spot-managed-node-group")
[ℹ]  will delete 1 nodegroups from cluster "jk"
[!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: fdb778b4-a858-4bec-80c1-4b57055806e4) from cloudformation/DescribeStacks - will retry after delay of 604.961677ms
```

**Comment by aclevername** [comment] 2021-01-29 15:14
> a lot of throttling during `create/delete nodegroup`
> 
> ```
> ./eksctl33 create nodegroup -f cluster.yaml
> [ℹ]  eksctl version 0.33.0
> [ℹ]  using region us-west-2
> [ℹ]  will use version 1.18 for new nodegroup(s) based on control plane version
> [!]  retryable error (Throttling: Rate exceeded
>         status code: 400, request id: 95edf075-631b-4908-82d1-af199846011a) from cloudformation/DescribeStacks - will retry after delay of 522.72417ms
> [ℹ]  nodegroup "spot-managed-node-group" present in the cluster, but missing from the given config
> [ℹ]  nodegroup "ng-managed" present in the cluster, but missing from the given config
> [ℹ]  nodegroup "ng-c292c102" present in the cluster, but missing from the given config
> [ℹ]  4 existing nodegroup(s) (ng-c292c102,ng-managed,spot-managed-node-group,spot-managed-node-group-2) will be excluded
> [ℹ]  2 sequential tasks: { fix cluster compatibility, no tasks }
> [ℹ]  checking cluster stack for missing resources
> [!]  retryable error (Throttling: Rate exceeded
>         status code: 400, request id: 5f98052f-c5d6-4472-98ed-c26e217ca587) from cloudformation/DescribeStacks - will retry after delay of 594.329443ms
> [ℹ]  cluster stack has all required resources
> [ℹ]  no tasks
> [✔]  created 0 nodegroup(s) in cluster "jk"
> [✔]  created 0 managed nodegroup(s) in cluster "jk"
> [!]  retryable error (Throttling: Rate exceeded
>         status code: 400, request id: 88f6ddf9-d1b4-4756-b455-715e774b2030) from cloudformation/DescribeStacks - will retry after delay of 760.9655ms
> [ℹ]  checking security group configuration for all nodegroups
> [ℹ]  all nodegroups have up-to-date configuration
> ```
> 
> ```
> ./eksctl delete nodegroup -f cluster.yaml
> [ℹ]  eksctl version 0.38.0-dev+16e9c8ef.2021-01-27T14:45:31Z
> [ℹ]  using region us-west-2
> [ℹ]  comparing 0 nodegroups defined in the given config ("cluste.yaml") against remote state
> [ℹ]  1 nodegroup (spot-managed-node-group) was included (based on the include/exclude rules)
> [ℹ]  (plan) would drain 1 nodegroup(s) in cluster "jk"
> [ℹ]  (plan) would delete 1 nodegroups from cluster "jk"
> [!]  retryable error (Throttling: Rate exceeded
>         status code: 400, request id: 3852bfd0-6782-4f28-9981-64743043e04e) from cloudformation/DescribeStacks - will retry after delay of 961.154192ms
> [!]  retryable error (Throttling: Rate exceeded
>         status code: 400, request id: bc3bdc76-cd9a-4d57-b434-e626cb35d88a) from cloudformation/DescribeStacks - will retry after delay of 972.906537ms
> [ℹ]  (plan) 1 task: { delete unowned nodegroup "spot-managed-node-group" }
> [ℹ]  (plan) would delete 0 nodegroups from auth ConfigMap in cluster "jk"
> [✔]  (plan) would have deleted 1 nodegroup(s) from cluster "jk"
> [!]  no changes were applied, run again with '--approve' to apply the changes
> (log-remaining-stacks → origin {6} ?:2 ✗) eksctl ./eksctl delete nodegroup -f cluste.yaml --approve
> [ℹ]  eksctl version 0.38.0-dev+16e9c8ef.2021-01-27T14:45:31Z
> [ℹ]  using region us-west-2
> [ℹ]  comparing 0 nodegroups defined in the given config ("cluste.yaml") against remote state
> [ℹ]  1 nodegroup (spot-managed-node-group) was included (based on the include/exclude rules)
> [ℹ]  will drain 1 nodegroup(s) in cluster "jk"
> [!]  no nodes found in nodegroup "spot-managed-node-group" (label selector: "alpha.eksctl.io/nodegroup-name=spot-managed-node-group")
> [ℹ]  will delete 1 nodegroups from cluster "jk"
> [!]  retryable error (Throttling: Rate exceeded
>         status code: 400, request id: fdb778b4-a858-4bec-80c1-4b57055806e4) from cloudformation/DescribeStacks - will retry after delay of 604.961677ms
> ```

I looked into this, I don't think we can reduce the number of Cloudformation calls at the moment. We get the stack for each nodegroup as we need to look into it to see if it's a nodegroups thats Managed or not, you can't detect this from the name. An alterntive would be to lookup in Kubernetes, but this would lean away from our approach of treating Cloudformation as the source of truth so I don't think its a good idea.

**Comment by Callisto13** [comment] 2021-02-01 10:12
Gah that's a bummer 😞  thanks for keeping on top of this.

**Comment by NaranKPatel** [comment] 2021-03-03 23:53
Can you reduce the no. of calls? i.e. exponential back off, queuing, etc to reduce the potential of encountering throttling? Users are getting impacted by this issue?

**Comment by cPu1** [comment] 2021-03-04 09:27
> Can you reduce the no. of calls? i.e. exponential back off, queuing, etc to reduce the potential of encountering throttling? Users are getting impacted by this issue?

@NaranKPatel we do have some commands where we can reduce the number of AWS API calls. Can you help us with the specific commands you're facing this issue for so we can prioritise them?

**Comment by cPu1** [comment] 2021-03-04 09:34
> > Can you reduce the no. of calls? i.e. exponential back off, queuing, etc to reduce the potential of encountering throttling? Users are getting impacted by this issue?
> 
> @NaranKPatel we do have some commands where we can reduce the number of AWS API calls. Can you help us with the specific commands you're facing this issue for so we can prioritise them?

From a comment from another user in the community Slack, it appears that it's for `create iamserviceaccounts`, `upgrade cluster` and `create cluster`, among other commands.

**Comment by NaranKPatel** [comment] 2021-03-04 20:53
create iamserviceaccounts incurs huge number of then proceeding cloudformation/DescribeStacks calls, to the point where it breaks any related changes and makes a mess of the cluster that needs 2+ hours of work to clean-up! I'm going through and looking at further commands but 3 you've listed (create iamserviceaccounts, upgrade cluster and create cluster) generate a lot proceeding describe calls. Basically any command that follows this behavior needs to be mitigated as mentioned above.

**Comment by andreamaruccia** [comment] 2021-04-01 08:29
Is it possible to reduce the loglevel for retryable errors in some way?

**Comment by pkit** [comment] 2021-11-11 11:58
I'm not really sure what's going on here? What's the point in reducing a number of calls if it's an AWS issue and it still succeeds after enough retries?

@NaranKPatel 
> to the point where it breaks any related changes and makes a mess of the cluster that needs 2+ hours of work to clean-up!

Have you raised that with AWS? What was the answer?
What was the failure scenario? I.e. some calls failed, what was number of retries? How much time the retries run?

**Comment by aclevername** [comment] 2021-11-11 12:10
> I'm not really sure what's going on here? What's the point in reducing a number of calls if it's an AWS issue and it still succeeds after enough retries?

For us we are just trying to reduce the number of duplicate API calls we make. When this issue was originally opened we had *a lot* of of unnecessary API calls due to poor code. We've been cleaning it up as part of this. Your right though that we will still have to do a certain amount of calls that will most likely hit the retry limit.

**Comment by pkit** [comment] 2021-11-11 14:01
Thanks. It was not clear to me that from the first to the last entry there was a lot of work done!
On the other hand I have come to this issue from #2965 , which kind of means: "we won't add more functionality if it increases a number of API calls". Which was kinda counter-intuitive to me...

**Comment by aclevername** [comment] 2021-11-16 14:41
> Thanks. It was not clear to me that from the first to the last entry there was a lot of work done! On the other hand I have come to this issue from #2965 , which kind of means: "we won't add more functionality if it increases a number of API calls". Which was kinda counter-intuitive to me...

I don't think that was the intended message, but more that we have to consider this carefully when editing existing commands. If `eksctl get clusters` went from 10 api call sfor 10 clusters, to 30 or 40 users might have a noticeably degraded UX

**Comment by aclevername** [comment] 2022-01-11 12:36
closing for now, feel free to re-open if anybody hits an new throttling issues

**Closed by aclevername** 2022-01-11 12:36 UTC
Labels: technical debt, kind/improvement, priority/important-longterm
