### ISSUE TITLE
Update cluster using CLI

### ISSUE THREAD

**Issue by roeera** [weaveworks/eksctl#323] opened 2018-11-26 12:33 UTC
Hi,

First nice Job, I came from Kops which do a very good job. (Although it would be nice to replace cloudformation with tf of something else)

One thing that I missing here is the option to update cluster, let's say that I would like to update instances type, or update ssh key for all at once. It would be nice if that could work.
Let me know what is the best option to update configs.

Best.

**Comment by michelzanini** [comment] 2018-12-17 16:01
I would like to know that one as well 👍

**Comment by kingdonb** [comment] 2019-02-27 13:08
So there are two parts to this, one is upgrading the control plane (easy since https://aws.amazon.com/blogs/compute/making-cluster-updates-easy-with-amazon-eks/) and the other is upgrading the worker nodes which looks a bit more complicated:

https://docs.aws.amazon.com/eks/latest/userguide/update-workers.html

given that you have to choose between migrating to a new worker node group, or upgrading in-place.  This still looks like news to me, the last time I checked there was only one option, and that was migrating your workloads to a new worker group.

Does anyone have this on a roadmap?

**Comment by kingdonb** [comment] 2019-02-27 13:11
This seems to be a dupe of #348 or #357

**Comment by errordeveloper** [comment] 2019-03-01 10:55
Thanks folks, we are working on this. Closing in favour of #348.

**Closed** 2020-05-21 15:43 UTC
Labels: area/upgrades, closed/duplicate
