### ISSUE TITLE
Feature request: enabling asg-access,external-dns-access,alb-ingress-access  with eksctl utils

### ISSUE THREAD

**Issue by ismailyenigul** [weaveworks/eksctl#2328] opened 2020-06-12 19:54 UTC
If you created a cluster **`without`** the following parameters, you can't enable them with eksctl later. 
```
--asg-access \
--external-dns-access \
--alb-ingress-access \
```
You have to delete/create the cluster or you need to add above policies yourself.
It would be great if these iam policies can be enabled/disabled with `eks utils` parameters

**Comment by martina-if** [comment] 2020-07-03 06:22
Probably better to implement this as part of https://github.com/weaveworks/eksctl/issues/462

**Comment by michaelbeaumont** [comment] 2021-01-19 11:14
Duplicate of #2774

**Closed** 2021-01-19 11:15 UTC
Labels: kind/feature, priority/backlog
