### ISSUE TITLE
set update-auth-configmap false by default

### ISSUE THREAD

**Issue by jithendra89** [weaveworks/eksctl#1586] opened 2019-11-20 22:43 UTC
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
A clear and concise description of why you want this feature. Include use-cases and any specific constraints you may have.
Im updating nodegroups in the existing cluster. I have created new node groups using the same cluster role. Then I'm trying to delete and drain node groups as described in https://eksctl.io/usage/managing-nodegroups/. But when I do cluster breaks and authentication failed due to eksctl updating configmap and it has set cluster roles to []. 
I think its best user decided whether to update configmap or not. 

**What feature/behavior/change do you want?**
A clear and concise description of the change you would like to see in eksctl.

Make --update-auth-configmap default false so config map don't get updates by default.

**Comment by rndstr** [comment] 2020-03-04 17:31
closing this as duplicate of #1703 since the newer one has more information and discussion going on now, thanks for submitting!

**Closed by rndstr** 2020-03-04 17:31 UTC
Labels: kind/feature
