### ISSUE TITLE
Incomplete error message

### ISSUE THREAD

**Issue by derrickburns** [weaveworks/eksctl#783] opened 2019-05-08 00:25 UTC
**What happened?**
I got the following error message, but it does not tell me which pod!

[✖]  This pod has more than one PodDisruptionBudget, which the eviction subresource does not support.

**What you expected to happen?**

**How to reproduce it?**
Include the steps to reproduce the bug

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.31"}
$ uname -a
Darwin TP-MBP 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
Also include your version of `heptio-authenticator-aws`

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Comment by martina-if** [comment] 2019-05-09 14:39
Hi @derrickburns , thanks for the report. Can you please tell us which command did you run? And can you run it including the arguments `-v 4` so we see more information about what's happening?

**Comment by derrickburns** [comment] 2019-07-24 03:23
Hi @martina-if .  I am sorry. I don't have more info.

**Comment by martina-if** [comment] 2019-07-24 15:47
Hi @derrickburns , I think that message comes from either the kubernetes API or one of the AWS ones so it doesn't seem to be in our control. I will close this for now since we cannot reproduce it but if it happens again, please reopen this issue and provide the command with the logs and we will be happy to help.

**Closed by martina-if** 2019-07-24 15:47 UTC
Labels: awaiting more information
