### ISSUE TITLE
timed out waiting for control plane "demo-cluster" after 20m0s

### ISSUE THREAD

**Issue by NekhilKotha** [weaveworks/eksctl#520] opened 2019-02-07 12:06 UTC
Please [search existing issues (open & closed)](https://github.com/weaveworks/eksctl/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if there is a similar one. If there is, add comments or vote where appropriate.

If you did not find a similar issue or if it did not help then ask for help in our [slack channel](https://weave-community.slack.com/messages/eksctl/)

**What help do you need?**
Describe the type of help you need
While creating cluster using eksctl I'm facing below error.

[✔]  all EKS cluster resource for "demo-cluster" had been created
[✔]  saved kubeconfig as "/root/.kube/config"

[✖]  timed out waiting for control plane "demo-cluster" after 20m0s

command used for cluster creation --> **eksctl create cluster  --version=1.11 --name=demo-cluster --nodes=3 --node-type=m4.xlarge --region=us-west-2 --tags owner=demouser**

**Comment by errordeveloper** [comment] 2019-02-07 18:38
Hi @NekhilKotha! This sounds like #347 (which I've not been able to reproduce yet), have you installed `aws-iam-authenticator`?

**Comment by NekhilKotha** [comment] 2019-02-08 07:15
> Hi @NekhilKotha! This sounds like #347 (which I've not been able to reproduce yet), have you installed `aws-iam-authenticator`?

Hi @errordeveloper , No I haven't installed **aws-iam-authenticator**
I believe we don't need **aws-iam-authenticator** for creating cluster right?

**Comment by errordeveloper** [comment] 2019-02-08 07:56
Yes, by design you don't have to have it, but it seems that we have a bug
(#347) that affects some users.

**Comment by errordeveloper** [comment] 2019-02-12 09:13
@NekhilKotha did you manage to get past this?

**Comment by whereisaaron** [comment] 2019-02-16 03:16
I just created a node group is it timed about after 20 minutes. This was because creating the NodeInstanceRole took 13 minutes alone. 20 minutes is took short for CloudFormation speed!

**Comment by errordeveloper** [comment] 2019-02-20 10:18
@whereisaaron seems like you are describing a different issue, this one is about 'waiting for control plane', which is on cluster creation...

**Comment by whereisaaron** [comment] 2019-02-20 18:51
If this is issue is caused by the infinite loop and not CF speed, then yes, I'm in the wrong place 👍

**Comment by errordeveloper** [comment] 2019-02-22 08:32
We have a fix for this coming in #569.

**Closed** 2019-02-22 13:54 UTC
Labels: awaiting more information
