### ISSUE TITLE
Adding an option to choose the stack name that will be created when we run eksctl create call.

### ISSUE THREAD

**Issue by kakarotbyte** [weaveworks/eksctl#3599] opened 2021-04-17 16:14 UTC
**What feature/behavior/change do you want?**
It will be beneficial to have a **custom CFN stack name** flag  that can be used to control the name of the stack that will be created. 

**Why do you want this feature?**

When we create EKS cluster using AWS cli/console by using a name like "under_score" we will not be able to  run **create iamserviceaccount** because Limitation in CFN. 

https://github.com/weaveworks/eksctl/blob/34f77ed7ca8b567bb6fa44da2b00de808a081e80/pkg/cfn/manager/api.go#L114-L119

>eksctl create iamserviceaccount \
> --cluster=under_score \
> --namespace=kube-system \
> --name=aws-load-balancer-controller \
> --attach-policy-arn=arn:aws:iam::<0123456789>:policy/AWSLoadBalancerControllerIAMPolicy \
> --override-existing-serviceaccounts \
> --approve
...
2021-04-17 23:08:09 [✖]  creating CloudFormation stack "eksctl-under_score-addon-iamserviceaccount-kube-system-aws-load-balancer-controller": ValidationError: 1 validation error detected: Value 'eksctl-under_score-addon-iamserviceaccount-kube-system-aws-load-balancer-controller' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*

As per [Specifying stack name and parameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-using-console-create-stack-parameters.html) stack name can contain only **alphanumeric characters (case-sensitive) and hyphens.** It must start with an alphabetic character and can't be longer than 128 characters.

 way around this at the moment:
-
- Create IRSA manually using [AWS management console](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html).
OR
- Create a new cluster with supported naming format.

**Comment by Callisto13** [comment] 2021-04-19 11:37
Hey @kakarotbyte, thanks for requesting this.

There is already a PR open to allow users to prefix the created stack name https://github.com/weaveworks/eksctl/pull/3600 🎉 . We can't allow users to set the entire stack name, since `eksctl` needs certain patterns present.

As for the underscore issue, when creating stacks on clusters which were not created by `eksctl` we can sanitise the names before we generate the stack name.

**Comment by Callisto13** [comment] 2021-08-25 13:35
Closing as dupe of https://github.com/weaveworks/eksctl/issues/581.

As for removing underscores from stack names, see https://github.com/weaveworks/eksctl/issues/2943#issuecomment-859390934

**Closed by Callisto13** 2021-08-25 13:35 UTC
Labels: kind/feature
