### ISSUE TITLE
volume type flag not supported for managed nodegroups

### ISSUE THREAD

**Issue by DevOpserzhao** [weaveworks/eksctl#3088] opened 2021-01-18 09:34 UTC
```
eksctl create cluster --name=eks-zxf01 --node-type t3.small --managed=true --node-volume-size 30 --node-volume-type gp3 --nodes 1
Error: --node-volume-type is not supported for Managed Nodegroups (--managed=true)
```
**Versions**
```
 eksctl version
0.35.0

 kubectl version  
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by DevOpserzhao** [comment] 2021-01-18 09:37
eksctl version
0.35.0

 kubectl version  
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by DevOpserzhao** [comment] 2021-01-18 09:40
eksctl create cluster --name=eks-zxf01 --node-type t3.small --managed=true   --node-volume-size 30 --node-volume-type gp3 --nodes 1
Error: --node-volume-type is not supported for Managed Nodegroups (--managed=true)

**Comment by aclevername** [comment] 2021-01-18 09:54
Hey @DevOpserzhao 👋 , looking at the error the issue is that we don't support specifying the `node-volume-type` for managed nodegroups.  I'm not entirely sure why its not configurable (will investigate). However in the next release of eksctl we will be making `gp3` the default https://github.com/weaveworks/eksctl/pull/3078

**Comment by aclevername** [comment] 2021-01-18 10:30
@DevOpserzhao looking into it it appears to be a bug with our CLI flags. If you use a config file it should work, e.g.:
```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-zxf01
  region: us-west-2
  
managedNodeGroups:
  - name: managed-ng-5
    instanceType: t3.small
    desiredCapacity: 1
    volumeSize: 30
    volumeType: gp3
```

**Comment by aclevername** [comment] 2021-01-19 10:07
this should be fixed as part of the next release https://github.com/weaveworks/eksctl/pull/3090

**Closed by aclevername** 2021-01-19 10:07 UTC
Labels: kind/bug

**Comment by DevOpserzhao** [comment] 2021-01-22 04:07
> @DevOpserzhao looking into it it appears to be a bug with our CLI flags. If you use a config file it should work, e.g.:
> 
> ```
> ---
> apiVersion: eksctl.io/v1alpha5
> kind: ClusterConfig
> 
> metadata:
>   name: eks-zxf01
>   region: us-west-2
>   
> managedNodeGroups:
>   - name: managed-ng-5
>     instanceType: t3.small
>     desiredCapacity: 1
>     volumeSize: 30
>     volumeType: gp3
> ```

region cn-northwest-1 test  success, Thank you
