### ISSUE TITLE
Creating/Deleting custom iamserviceaccount creates/deletes aws-node service account as well

### ISSUE THREAD

**Issue by dragonraid** [weaveworks/eksctl#2968] opened 2020-12-18 16:30 UTC
**What happened?**
Custom IAM service account is created. Upon it's creation `kube-system/aws-node` is created as well.
Upon it's deletion, the `kube-system/aws-node` IAM service account is also deleted.

**What you expected to happen?**
Only custom service account to be created/deleted.

**How to reproduce it?**
```
eksctl create iamserviceaccount \
    --name foo \
    --namespace XXXX \
    --cluster ZZZZ \
    --attach-policy-arn arn:aws:iam::aws:policy/XXXX \
    --approve \
    --override-existing-serviceaccounts
 
[ℹ]  eksctl version 0.34.0
[ℹ]  using region RRRR
[ℹ]  9 existing iamserviceaccount(s) (XXXX/YYYY,XXXX/YYYY,XXXX/YYYY,XXXX/YYYY,YYYY/YYYY,YYYY/YYYY,YYYY/YYYY,...) will be excluded
[ℹ]  2 iamserviceaccounts (XXXX/foo, kube-system/aws-node) were included (based on the include/exclude rules)
[!]  metadata of serviceaccounts that exist in Kubernetes will be updated, as --override-existing-serviceaccounts was set
[ℹ]  2 parallel tasks: { 2 sequential sub-tasks: { create IAM role for serviceaccount "XXXX/foo", create serviceaccount "XXXX/foo" }, 2 sequential sub-tasks: { create IAM role for serviceaccount "kube-system/aws-node", create serviceaccount "kube-system/aws-node" } }
[ℹ]  building iamserviceaccount stack "eksctl-YYYY-primary-addon-iamserviceaccount-XXXX-foo"
[ℹ]  building iamserviceaccount stack "eksctl-YYYY-primary-addon-iamserviceaccount-kube-system-aws-node"
[ℹ]  deploying stack "eksctl-YYYY-primary-addon-iamserviceaccount-XXXX-foo"
[ℹ]  deploying stack "eksctl-YYYY-primary-addon-iamserviceaccount-kube-system-aws-node"
[ℹ]  created serviceaccount "kube-system/aws-node"
[ℹ]  created serviceaccount "XXXX/foo"

eksctl delete iamserviceaccount \
   --name foo \
   --cluster ZZZZ \
   --namespace XXXX
  
[ℹ]  eksctl version 0.34.0
[ℹ]  using region RRRR
[ℹ]  2 iamserviceaccounts (XXXX/foo, kube-system/aws-node) were included (based on the include/exclude rules)
[ℹ]  2 parallel tasks: { 2 sequential sub-tasks: { delete IAM role for serviceaccount "kube-system/aws-node" [async], delete serviceaccount "kube-system/aws-node" }, 2 sequential sub-tasks: { delete IAM role for serviceaccount "XXXX/foo" [async], delete serviceaccount "XXXX/foo" } }
[ℹ]  will delete stack "eksctl-YYYY-primary-addon-iamserviceaccount-kube-system-aws-node"
[ℹ]  will delete stack "eksctl-YYYY-primary-addon-iamserviceaccount-XXXX-foo"
[ℹ]  deleted serviceaccount "XXXX/foo"
[ℹ]  deleted serviceaccount "kube-system/aws-node"
```

**Anything else we need to know?**
OS: macOS
Installed via homebrew.
I am using named profile that references source profile in order to assume role in different AWS account.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version - 0.34.0
$ kubectl version - v1.20.0
```

**Comment by michaelbeaumont** [comment] 2020-12-18 16:48
Duplicate of https://github.com/weaveworks/eksctl/issues/2916

**Comment by michaelbeaumont** [comment] 2020-12-18 16:48
Fixed by https://github.com/weaveworks/eksctl/pull/2917, will be in next release

**Closed by michaelbeaumont** 2020-12-18 16:48 UTC
Labels: kind/bug
