### ISSUE TITLE
Build binary for arm64 

### ISSUE THREAD

**Issue by sayboras** [weaveworks/eksctl#2724] opened 2020-10-11 02:35 UTC
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
Recently, there is a lot of development related to arm ec2 instance (e.g. aws Graviton). It will be great if eksctl is shipped with arm64 binaries as well.

One common use case could be running eksctl from arm ec2 node for private cluster.

**What feature/behavior/change do you want?**
eksctl with arm/arm64 binaries

If it's fine, I can spend sometime to send PR as well.

**Comment by michaelbeaumont** [comment] 2020-10-13 10:45
Duplicate of #2621

**Closed** 2020-10-13 10:45 UTC
Labels: kind/feature
