### ISSUE TITLE
Flakey CRUD test- " We currently do not have sufficient p2.xlarge capacity in the Availability Zone"

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#4732] opened 2022-02-02 08:58 UTC
```
 fetching stack events in attempt to troubleshoot the root cause of the failure
[8] 2022-02-02 01:55:29 [✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Nodegroup mng-2 failed to stabilize: [{Code: AsgInstanceLaunchFailures,Message: Could not launch On-Demand Instances. InsufficientInstanceCapacity - We currently do not have sufficient p2.xlarge capacity in the Availability Zone you requested (us-west-2b). Our system will be working on provisioning additional capacity. You can currently get p2.xlarge capacity by not specifying an Availability Zone in your request or choosing us-west-2a, us-west-2c. Launching EC2 instance failed.,ResourceIds: [eks-mng-2-82bf5c07-70d3-9015-d7e4-4ce657bd6b3d]}, {Code: NodeCreationFailure,Message: Instances failed to join the kubernetes cluster,ResourceIds: [DUMMY_036364eb-6e0e-465a-bf91-7c1f8ee2f891, DUMMY_06260bd0-77c1-4bc1-b5e4-46c815c2e805, DUMMY_1279e385-771a-430d-bd1b-9f29fd801866, DUMMY_1287e32e-30b4-410c-ae93-8b13f13fd5c0, DUMMY_130658e2-d42a-4d7e-979f-863fcfeddd36, DUMMY_1b16ef9b-5257-45c9-bd8e-dd94f32c3735, DUMMY_25349389-cbe9-4338-9470-3a75e77bd068, DUMMY_2da3eb51-4a6a-4c17-bc28-31a6a36c769b, DUMMY_376bd005-545e-41b3-a3bc-84c7ba87946b, DUMMY_3cda6905-acdb-427a-ac84-ec1a09562a04, DUMMY_453c4d30-29ca-4e4a-aa66-779e3d96bf6c, DUMMY_53fed181-408d-4a80-87d0-8f073cfd4c1b, DUMMY_54bd2f9c-4b26-49f6-94ed-9fedeaf3abdd, DUMMY_5b9e901d-d6ab-4755-9e68-665186a4c58f, DUMMY_5fdf8e6c-7c88-4952-9594-680b4cf094f2, DUMMY_6384b29b-1506-4dee-87c4-ad8276c90801, DUMMY_6b6d9289-5306-4fd0-ac74-5937406e0c33, DUMMY_722ed548-4f4e-49b6-9030-b13ba577604b, DUMMY_7789a44d-f67f-467b-8f68-444201b8179e, DUMMY_7ac69cb3-df62-4da1-a301-6a0110ec956d, DUMMY_7fe9930b-e708-4b25-b7d6-6491e3562c21, DUMMY_8869570a-a714-4c43-821b-71b6644ea289, DUMMY_8df11294-226c-49d5-a449-ed60de97a618, DUMMY_93615590-bb0c-4e01-839f-259ef26bb16d, DUMMY_a421c3ea-78bd-4fdc-a139-d63123014b94, DUMMY_a42823a2-57b0-4a20-9785-1fd618a70229, DUMMY_acc3e9f0-a052-491d-ae57-06f463c61ca5, DUMMY_bde6605b-85bf-4873-924b-c0c5c6f410ab, DUMMY_c02916fa-3174-4bb4-b7e1-3be444d92f04, DUMMY_c1352d77-6f34-4672-ad02-432438403d4d, DUMMY_c34ae23b-510d-4c31-a4dd-a4f1a418306b, DUMMY_cb95d506-91ff-4f07-b8f6-32e4c9a63826, DUMMY_d1d07f26-f263-4f59-8535-ee452cad48b5, DUMMY_e5ad700b-e33f-46f7-b287-280512407ffd, DUMMY_e791aa42-91d0-47a3-b585-e12fdd15b167, DUMMY_e7c48c0b-6a7a-4f73-b124-1a512fbfb176, DUMMY_f09800cc-cd88-4fa3-8ebd-ea5931756275, DUMMY_f4c370c0-1f69-4711-9035-64e7f9e2d96a, DUMMY_f515be20-db7c-4a82-8f11-d18939cb08b4]}]"
[8] 2022-02-02 01:55:29 [ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
[8] 2022-02-02 01:55:29 [ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=us-west-2 --cluster=it-crud-beautiful-monster-1643761096 --name=<name>' for each of the failed nodegroup
[8] 2022-02-02 01:55:29 [✖]  waiting for CloudFormation stack "eksctl-it-crud-beautiful-monster-1643761096-nodegroup-mng-2": ResourceNotReady: failed waiting for successful resource state
[8] Error: failed to create nodegroups for cluster "it-crud-beautiful-monster-1643761096"
[8] 
[8] • Failure [1504.220 seconds]
[8] (Integration) Create, Get, Scale & Delete
[8] /__w/eksctl-ci/eksctl-ci/eksctl/integration/tests/crud/creategetdelete_test.go:61
[8]   cluster with 1 node
[8]   /__w/eksctl-ci/eksctl-ci/eksctl/integration/tests/crud/creategetdelete_test.go:131
[8]     and add a second (GPU) nodegroup
[8]     /__w/eksctl-ci/eksctl-ci/eksctl/integration/tests/crud/creategetdelete_test.go:494
[8]       should not return an error [It]
[8]       /__w/eksctl-ci/eksctl-ci/eksctl/integration/tests/crud/creategetdelete_test.go:495
[8] 
[8]       Expected '../../../eksctl "--region" "us-west-2" "create" "nodegroup" "--timeout=45m" "--cluster" "it-crud-beautiful-monster-1643761096" "--nodes" "1" "--node-type" "p2.xlarge" "--node-private-networking" "--node-zones" "us-west-2b,us-west-2c" "mng-2"' to succeed, got return code 1
[8] 
[8]       /__w/eksctl-ci/eksctl-ci/eksctl/integration/tests/crud/creategetdelete_test.go:506
```

https://github.com/weaveworks/eksctl-ci/runs/5029967120?check_suite_focus=true

**Comment by Himangini** [comment] 2022-02-02 12:06
dupe of #4683

**Comment by Himangini** [comment] 2022-02-02 13:38
In order to fix this issue we probably need to pass multiple GPU instance types `"--node-type" "p2.xlarge"` 
Needs some investigation on if we can pass multiple types

**Closed** 2022-02-03 07:12 UTC
Labels: kind/bug, area/testing, flaky-test
