### ISSUE TITLE
Support "imagePullSecrets" for ServiceAccount created by "create cluster"/"create iamserviceaccount"

### ISSUE THREAD

**Issue by artem-nefedov** [weaveworks/eksctl#3108] opened 2021-01-19 15:22 UTC
It would be great if schema for iamserviceaccounts created by eksctl allowed to specify "imagePullSecrets"  field.
Currently, you have to first create a ServiceAccount with eksctl, then patch it separately.

**Comment by aclevername** [comment] 2021-01-21 09:37
Hey @artem-nefedov, thanks for raising this. 

> Currently, you have to first create a ServiceAccount with eksctl, then patch it separately.

You could instead create the serviceaccount yourself, with the imagepull secrets and then when running `eksctl create iamserviceaccount` add the `--override-existing-serviceaccounts` flag. This changes the behaviour of eksctl to patch any existing serviceaccounts with the annotation instead of attempting to create it.

We've had a fair bit of discussion recently regarding how we should interact with serviceaccount https://github.com/weaveworks/eksctl/issues/3042 https://github.com/weaveworks/eksctl/issues/1698, this is another use case that I don't think we'd thought of.

**Comment by michaelbeaumont** [comment] 2021-01-21 14:11
Duplicate of https://github.com/weaveworks/eksctl/issues/3128

**Closed** 2021-01-21 14:14 UTC
Labels: kind/feature
