### ISSUE TITLE
upgrading cluster managed nodegroup results in error, showing version mismatch

### ISSUE THREAD

**Issue by brentley** [weaveworks/eksctl#3201] opened 2021-02-03 16:41 UTC
**What were you trying to accomplish?**
I was running the command: 
```
eksctl upgrade nodegroup --name=nodegroup --cluster=eksworkshop-eksctl --kubernetes-version=1.18 --wait
```

**What happened?**
The upgrade failed. The relevant error appears to be:
```
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_FAILED – "Requested Nodegroup release version 1.18.9-20210125 is invalid. Allowed release version is 1.18.9-20210127 (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: b7bc4ca6-a68c-4815-ae17-0c46ddc32099; Proxy: null)"
```

**How to reproduce it?**
- Begin by creating a 1.17 cluster, including a managed nodegroup (I was using us-west-2 if that matters)
- Upgrade the control plane
- upgrade the add-ons
- run the command above to upgrade the managed nodegroup
- 
If using a config file, include it here, removing any sensitive information!
```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eksworkshop-eksctl
  region: us-west-2
  version: "1.17"

availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  ssh:
    allow: true
    publicKeyName: eksworkshop

secretsEncryption:
  keyARN: arn:aws:kms:us-west-2:xxxxxxxxxxx:key/09b590a9-8502-47ad-8098-f9610858483c
```

**Logs**
https://gist.github.com/brentley/4cd71d2dadc81ffc29033fb724fac10c#file-cluster-nodegroup-upgrade-error-L19

**Anything else we need to know?**
I'm running this from a cloud9 instance that uses AmazonLinux2 and has an instance role attached. 

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.37.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.11-eks-cfdc40", GitCommit:"cfdc40d4c1b7d14eb60152107963ae41aa2e4804", GitTreeState:"clean", BuildDate:"2020-09-17T17:10:39Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by brentley** [comment] 2021-02-03 16:53
I'm not sure if it's noteworthy, but the `aws eks` way of upgrading the nodegroup does work:
```
aws eks update-nodegroup-version --cluster-name eksworkshop-eksctl --nodegroup-name nodegroup
{
    "update": {
        "status": "InProgress", 
        "errors": [], 
        "params": [
            {
                "type": "Version", 
                "value": "1.18"
            }, 
            {
                "type": "ReleaseVersion", 
                "value": "1.18.9-20210127"
            }, 
            {
                "type": "LaunchTemplateName", 
                "value": "eksctl-eksworkshop-eksctl-nodegroup-nodegroup"
            }, 
            {
                "type": "LaunchTemplateVersion", 
                "value": "1"
            }
        ], 
        "type": "VersionUpdate", 
        "id": "ed722767-ea4f-347d-9fd6-799af6136b77", 
        "createdAt": 1612371108.084
    }
}
```

**Comment by aclevername** [comment] 2021-02-03 16:56
Thanks for opening the issue @brentley, couple questions:
1. did you create the cluster  & nodegroup with eksctl or directly using the EKS api?
2. Can you provide the full log output for the `upgrade` command?

Thanks!

**Comment by brentley** [comment] 2021-02-03 16:58
I created the cluster using eksctl (I'm the maintainer of eksworkshop.com and was reviewing a PR, so the cloud9 environment + cluster was freshly created)

the full log output is attached as a gist in the original issue.

**Comment by aclevername** [comment] 2021-02-03 17:13
> I created the cluster using eksctl (I'm the maintainer of eksworkshop.com and was reviewing a PR, so the cloud9 environment + cluster was freshly created)
> 
> the full log output is attached as a gist in the original issue.

Thanks @brentley , sorry I blurred past the provided config 😄 . I'm trying to reproduce locally now.

I didn't actually know how we determined what value to use when issuing an ugprade, taking a look at the code it appears we query SSM to discover the latest available version:
https://github.com/weaveworks/eksctl/blob/20b7906f92a04bea20893cd3535ee3e818af4799/pkg/managed/service.go#L323-L336

**Comment by rtripat** [comment] 2021-02-03 17:19
This is an issue when certain (internal) customers/accounts specify release version instead of letting the EKS API chose it for them. @aclevername is there a strong reason behind eksctl querying SSM parameter to set the release version to MNG API?

**Comment by aclevername** [comment] 2021-02-03 17:23
> This is an issue when certain (internal) customers/accounts specify release version instead of letting the EKS API chose it for them

👍  thanks

> @aclevername is there a strong reason behind eksctl querying SSM parameter to set the release version to MNG API?

Since we use CloudFormation to trigger the upgrade we have to specify the version in the CloudFormation template to trigger the upgrade, we don't hit the EKS api directly. I wasn't around when this was implemented so I'm not sure what alternative methods there are for querying AWS to discover the latest version.

**Comment by aclevername** [comment] 2021-02-03 17:27
> I'm not sure if it's noteworthy, but the `aws eks` way of upgrading the nodegroup does select the latest release version:
> 
> ```
> aws eks update-nodegroup-version --cluster-name eksworkshop-eksctl --nodegroup-name nodegroup
> {
>     "update": {
>         "status": "InProgress", 
>         "errors": [], 
>         "params": [
>             {
>                 "type": "Version", 
>                 "value": "1.18"
>             }, 
>             {
>                 "type": "ReleaseVersion", 
>                 "value": "1.18.9-20210127"
>             }, 
>             {
>                 "type": "LaunchTemplateName", 
>                 "value": "eksctl-eksworkshop-eksctl-nodegroup-nodegroup"
>             }, 
>             {
>                 "type": "LaunchTemplateVersion", 
>                 "value": "1"
>             }
>         ], 
>         "type": "VersionUpdate", 
>         "id": "ed722767-ea4f-347d-9fd6-799af6136b77", 
>         "createdAt": 1612371108.084
>     }
> }
> ```

@brentley just an FYI manually upgrading the nodegroup leaves the CloudFormation template out of date, which *might* lead to problems down the line if we rely on the value in the template anywhere else in the code

**Comment by brentley** [comment] 2021-02-03 17:34
That makes sense, and I wasn't aware that I was on any internal list... so that explains it. Still though, I think a move away from cloudformation here might make sense. querying cloudformation as a source of truth wouldn't be as strong as querying the eks api for the current version info. 

Still, though... I think this discussion might warrant moving this from a bug to maybe a feature request?

**Comment by aclevername** [comment] 2021-02-03 17:53
> That makes sense, and I wasn't aware that I was on any internal list... so that explains it. Still though, I think a move away from cloudformation here might make sense. querying cloudformation as a source of truth wouldn't be as strong as querying the eks api for the current version info.

We use CloudFormation quite extensively to handle all of the AWS resources we create, I think its unlikely we would move away from it unless we had a lot of good reason.  How much we use the CloudFormation template as a source of truth is an area that has potential to change, especially given how easy it is to make changes manually in the EKS console.

> Still, though... I think this discussion might warrant moving this from a bug to maybe a feature request to modify the latest nodegroup version querying and upgrade triggering so that the eks control plane can manage it?

I think thats a reasonable feature request, although I don't actually know how much it differs to CloudFormation handling it? I assumed CloudFormation was making the equivalent API calls behind the scenes. The only value we would gain from talking to the API is the defaulting of values for us, like the version value in this case. We could look into alternative methods for finding the version value as a potential improvement, although I'm not sure what those alternatives are.

**Comment by rtripat** [comment] 2021-02-03 19:14
We are re-evaluating if Brent's account needs to be part of this internal customer list and keep it as minimal as possible.

**Comment by aclevername** [comment] 2021-02-04 17:05
I'm going to close the issue, feel free to open any relevant feature request issues 😄

**Closed by aclevername** 2021-02-04 17:05 UTC
Labels: kind/bug
