### ISSUE TITLE
Make aws-iam-authenticator the default

### ISSUE THREAD

**Issue by jicowan** [weaveworks/eksctl#128] opened 2018-07-19 12:29 UTC
Now that the Heptio authenticator have been moved to aws-sig, make the aws-iam-authenticator the default.  When eksctl creates the kubeconfig, it still refers to the heptio-iam-authenticator.

**Comment by jicowan** [comment] 2018-07-20 16:05
You can install the binary [with the new name] through go now.

**Comment by errordeveloper** [comment] 2018-07-20 17:22
We have Homebrew "package" for macOS users, and that pulls released binary
URL.
And we don't require users to have Go toolchain, so `go get` isn't really
an option.

**Comment by errordeveloper** [comment] 2018-07-25 15:34
duplicate of #112

**Closed by errordeveloper** 2018-07-25 15:34 UTC
