### ISSUE TITLE
Panic error with 0.15.0-rc.0 in China region

### ISSUE THREAD

**Issue by jerry123je** [weaveworks/eksctl#1885] opened 2020-03-04 11:15 UTC
**What happened?**
0.15.0 recent released to improve support for China region EKS, we tried to deploy cluster with a config file, but get panic error

```
eksctl-15 create cluster -f cluster.yaml
[ℹ] eksctl version 0.15.0-rc.0
[ℹ] using region cn-north-1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1488430]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5.NoAccess(...)
github.com/weaveworks/eksctl@/pkg/apis/eksctl.io/v1alpha5/validation.go:126
github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5.(*ClusterConfig).ValidateClusterEndpointConfig(0xc000540160, 0xc0005d76e0, 0x0)
github.com/weaveworks/eksctl@/pkg/apis/eksctl.io/v1alpha5/validation.go:115 +0x40
github.com/weaveworks/eksctl/pkg/ctl/create.doCreateCluster(0xc00035c000, 0xc000330160, 0xc00035c080, 0x0, 0x0)
github.com/weaveworks/eksctl@/pkg/ctl/create/cluster.go:112 +0x168
github.com/weaveworks/eksctl/pkg/ctl/create.createClusterCmd.func1(0xc0001df900, 0xc000495900, 0x0, 0x2, 0x0, 0x0)
github.com/weaveworks/eksctl@/pkg/ctl/create/cluster.go:36 +0x9b
github.com/spf13/cobra.(*Command).execute(0xc0001df900, 0xc0004958c0, 0x2, 0x2, 0xc0001df900, 0xc0004958c0)
github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001de500, 0xc0001232c0, 0x1, 0x1)
github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
github.com/weaveworks/eksctl@/cmd/eksctl/main.go:79 +0x407
```
config file as below:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
name: eks-cluster
region: cn-north-1

vpc:
cidr: 172.10.0.0/16
autoAllocateIPv6: true
```

Tried similar config in us-east-1, no error.

**How to reproduce it?**
Use eksctl 0.15.0 in China region with -f. 

**Anything else we need to know?**
OS: Amazon Linux2 

**Versions**
Please paste in the output of these commands:
```
eksctl version
0.15.0-rc.0
```

**Comment by cPu1** [comment] 2020-03-04 11:39
>Tried similar config in us-east-1, no error.

@jerry123je I presume you either tried a different config file or a different version of eksctl for creating  a cluster in `us-east-1`. There's no region-specific validation in eksctl, so if panics for region `cn-north-1`, it will give the same result for other regions.

The bug you've reported is not specific to cn-north-1, and has been fixed in master. The fix will be out in the next release.

**Comment by cPu1** [comment] 2020-03-04 16:53
FTR, this is the PR that fixed the issue: https://github.com/weaveworks/eksctl/pull/1855

I'm closing this because it's a duplicate of https://github.com/weaveworks/eksctl/issues/1852. Please feel free to reopen it if you find an issue.

**Closed** 2020-03-04 16:53 UTC
Labels: kind/bug
