### ISSUE TITLE
eksctl is not cleaning up keys

### ISSUE THREAD

**Issue by rodrigc** [weaveworks/eksctl#1307] opened 2019-09-06 20:05 UTC
**What happened?**

`eksctl delete cluster` is not cleaning up keys

**What you expected to happen?**
`eksctl delete cluster` should delete keys created with `eksctl create cluster`

**How to reproduce it?**
1.  Create a cluster with `eksctl create cluster`
2.  Delete the cluster with `eksctl delete cluster`
3.  Wait until the cluster is fully deleted
4.  Look at https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#KeyPairs:sort=keyName
5.  I see keys there that I thought would be deleted after the cluster was deleted

**Anything else we need to know?**
N/A

**Versions**

```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.3.1"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", 
```

**Comment by martina-if** [comment] 2019-10-08 12:43
Hi @rodrigc I tried reproducing this issue with the latest version of eksctl and I couldn't. Can you try with a [newer version of eksctl](https://github.com/weaveworks/eksctl/releases/tag/latest_release)? I think it might be an old bug or lack of the feature in `0.3.1`.

**Comment by martina-if** [comment] 2019-10-10 13:22
Hi @rodrigc , I am closing this since I couldn't reproduce it with the latest versions but please feel free to reopen it if you think the issue is not solved.

**Closed by martina-if** 2019-10-10 13:22 UTC
Labels: kind/bug
