### ISSUE TITLE
Add flag to save cloudformation template to a file

### ISSUE THREAD

**Issue by danielwhatmuff** [weaveworks/eksctl#1813] opened 2020-02-13 11:08 UTC
**Why do you want this feature?**
To be able to inspect/version control the raw cloudformation template. Different versions of eksctl may generate a different template based on the same eksctl configuration so this would also allow for a more reliable rollback if issues are encountered.

**What feature/behavior/change do you want?**
A flag to indicate that eksctl should write the rendered cloudformation template (and parameters) to a specified local file just before they are posted to the cloudformation API. A check for the flag somewhere in here https://github.com/weaveworks/eksctl/blob/5963d76300ab76f22de208018eb0567d8f76974b/pkg/cfn/manager/api.go#L115

This would support something like `eks create cluster -f config.yml --write-cfnconfig string`

Interested to get feedback and if positive I can PR.

**Comment by alanoberto** [comment] 2020-03-27 19:49
Waiting for it!!!

**Comment by danielwhatmuff** [comment] 2020-03-28 09:44
> Waiting for it!!!

Ok will take a look

**Comment by pbaezab** [comment] 2020-03-30 21:05
+1

**Comment by felipelagosn** [comment] 2020-03-30 21:06
+1

**Comment by sayboras** [comment] 2020-03-30 21:17
Very useful feature 💯

**Comment by martina-if** [comment] 2020-05-26 08:27
duplicate of #956

Thanks @danielwhatmuff for reporting this. It seems like it's a useful feature. For the sake of keeping the list of issues cleaner I will close this one and keep #956 open. Please upvote it, that will help it being prioritized.

**Closed by martina-if** 2020-05-26 08:27 UTC
Labels: closed/duplicate, kind/feature

**Comment by danielwhatmuff** [comment] 2020-05-26 09:01
No worries, I did make a start on this PR last week but my day job got in the way. Will finish off later this week if I don't see it WIP elsewhere.

**Comment by martina-if** [comment] 2020-05-26 09:37
@danielwhatmuff some things that might be useful #718 #1039

**Comment by danielwhatmuff** [comment] 2020-05-26 10:54
Thanks, I was following the pattern used for the write kubeconfig flag but this is also useful.

**Comment by martina-if** [comment] 2020-05-26 11:44
@danielwhatmuff I am not sure what pattern is best in this case. I didn't really give it much thought, if you want to be sure before opening the PR please reach us on [slack](https://weave-community.slack.com/archives/CAYBZBWGL)
