### ISSUE TITLE
Add AWS_PROFILE env to kubeconfig

### ISSUE THREAD

**Issue by mr-karan** [weaveworks/eksctl#1407] opened 2019-10-07 04:42 UTC
**Why do you want this feature?**
While writing to `~/.kube/config` we can detect the `AWS_PROFILE` value and substitute the same in the section 

```
      command: aws
      env:
      - name: AWS_PROFILE
        value: XYZ
```

**What feature/behavior/change do you want?**
While updating the `kubeconfig` the env section is `NULL`. We can update it with the correct AWS_PROFILE variable

**Comment by rothgar** [comment] 2020-09-04 18:58
I also would like this value to persist by default. It looks like this is how it worked at one point but this may be a regression.

https://github.com/weaveworks/eksctl/pull/74

**Comment by rothgar** [comment] 2021-01-20 07:28
I just verified that the code still exists. I think you may need to set the `--profile` when writing the kubeconfig file. I'll do more testing to verify.

https://github.com/weaveworks/eksctl/blob/master/pkg/utils/kubeconfig/kubeconfig.go#L171-L174

**Comment by rothgar** [comment] 2021-02-05 00:07
Just to close the loop on this. I was able to test the `--profile` flag and it works exactly as expected and I even missed that it's in the `--help` output for `write-kubeconfig`

```
AWS client flags:
  -p, --profile string   AWS credentials profile to use (overrides the AWS_PROFILE environment variable)
```

Running this works great :+1: 

```
eksctl utils write-kubeconfig -c prod --profile demo
```

**Comment by michaelbeaumont** [comment] 2021-02-05 10:27
Thank you for checking back @rothgar! Closing this now.

**Closed by michaelbeaumont** 2021-02-05 10:27 UTC
Labels: good first issue, kind/feature, low-hanging-fruit, needs-investigation
