### ISSUE TITLE
fail to update managed worker nodes from 1.14 to 1.15

### ISSUE THREAD

**Issue by fmedery** [weaveworks/eksctl#1962] opened 2020-03-21 18:01 UTC
**What happened?**
eksctl failed to get the correct AMI:
from Cloudformation stack
```
Requested Nodegroup release version 1.15.10-20200312 is invalid. Allowed release version is 1.15.10-20200228 (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 2e3ded7b-7955-4255-8945-ccc201882424)
```

**What you expected to happen?**
Worker nodes should be 1.15

**How to reproduce it?**
```sh
echo export cluster="old-cluster"
# create a eks cluster + managed worker nodes
eksctl create cluster \
    --name $cluster \
    --version 1.14 \
    --managed
# update control plane
eksctl update cluster --name $cluster --approve

# update add-ons
eksctl utils update-kube-proxy \
    --cluster $cluster \
    --approve

eksctl utils update-aws-node \
    --cluster $cluster \
    --approve

eksctl utils update-coredns \
    --cluster $cluster \
    --approve
# try to update managed worker nodes:
export MANAGED_NODE_GROUP=$(eksctl get nodegroup --cluster $cluster -ojson|jq -r '.[].Name')

echo eksctl upgrade nodegroup \
    --name=${MANAGED_NODE_GROUP} \
    --cluster=$cluster \
    --kubernetes-version=1.15
```
**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
eksctl version
0.15.0

kubectl version --short
Client Version: v1.14.7-eks-1861c5
Server Version: v1.15.10-eks-bac369
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

```[ℹ]  Update nodegroup stack
[✖]  unexpected status "UPDATE_ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[ℹ]  AWS::CloudFormation::Stack/eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3: UPDATE_ROLLBACK_IN_PROGRESS – "The following resource(s) failed to update: [ManagedNodeGroup]. "
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_FAILED – "Requested Nodegroup release version 1.15.10-20200312 is invalid. Allowed release version is 1.15.10-20200228 (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 501bd6c8-c0bd-43c9-874b-5be995316fe5)"
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3: UPDATE_IN_PROGRESS – "User Initiated"
[ℹ]  AWS::CloudFormation::Stack/eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3: UPDATE_ROLLBACK_COMPLETE
[ℹ]  AWS::CloudFormation::Stack/eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3: UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_COMPLETE
[ℹ]  AWS::CloudFormation::Stack/eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3: UPDATE_ROLLBACK_IN_PROGRESS – "The following resource(s) failed to update: [ManagedNodeGroup]. "
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_FAILED – "Requested Nodegroup release version 1.15.10-20200312 is invalid. Allowed release version is 1.15.10-20200228 (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 2e3ded7b-7955-4255-8945-ccc201882424)"
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3: UPDATE_IN_PROGRESS – "User Initiated"
[ℹ]  AWS::CloudFormation::Stack/eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3: CREATE_COMPLETE
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_COMPLETE
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_IN_PROGRESS – "Resource creation Initiated"
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_IN_PROGRESS
[ℹ]  AWS::IAM::Role/NodeInstanceRole: CREATE_COMPLETE
[ℹ]  AWS::IAM::Role/NodeInstanceRole: CREATE_IN_PROGRESS – "Resource creation Initiated"
[ℹ]  AWS::IAM::Role/NodeInstanceRole: CREATE_IN_PROGRESS
[ℹ]  AWS::CloudFormation::Stack/eksctl-eksworkshop-eksctl-old-nodegroup-ng-27c8ace3: CREATE_IN_PROGRESS – "User Initiated"
```

**Comment by sayboras** [comment] 2020-03-22 09:55
@fmedery seems like AWS released the newer image as per https://github.com/awslabs/amazon-eks-ami/releases.

eksctl retrieves image id from ssm `/aws/service/eks/optimized-ami/1.15/amazon-linux-2/recommended/image_id` which is pointing to latest version amazon/amazon-eks-node-1.15-v20200312. Not sure if we need to wait for few days for this to be ready in all regions.

**Comment by fmedery** [comment] 2020-03-22 17:15
Thank you for the reply.
I checked param. store using aws cli and the AMI is in the region:

```sh
export latestid=$(aws ssm get-parameters --region us-east-2 --names /aws/service/eks/optimized-ami/1.15/amazon-linux-2/recommended | jq -r '.Parameters[].Value| fromjson| .image_id')

aws ec2 describe-images \
  --region us-east-2 \
  --image-ids $latestid | jq '.Images[].Description, .Images[].ImageId, .Images[].State'
```
output
```text
"EKS Kubernetes Worker AMI with AmazonLinux2 image, (k8s: 1.15.10, docker:18.09.9ce-2.amzn2)"
"ami-0da2b71057dfd9557"
"available"
```
I was able to successfully to update the worker node group using the AWS console

**Comment by sayboras** [comment] 2020-03-22 21:05
@fmedery Thanks for your info. It's kind of confirmed for what I thought i.e. **AWS Cloudformation** might need to roll out the changes. The error message `Allowed release version is 1.15.10-20200228 (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 2e3ded7b-7955-4255-8945-ccc201882424)` is Cloudformation parameter validation.

As the SSM param is already updated and new AMI is available, I think that we just need to wait for CF to be ready. The current official [docs](https://docs.aws.amazon.com/eks/latest/userguide/eks-linux-ami-versions.html) still mentioned _old_ image (v20200228).

**Comment by sayboras** [comment] 2020-03-22 21:49
Surprisingly, if I am creating a **new** managed cluster with 1.15, it's working fine. 

In CF, we have the below two attributes `Version` and `ReleaseVersion` as per below. Even though, the underlying issue is due to AWS inconsistent values/behavior between services (e.g. SSM, AMI, CF), we still can make one improvement in which just updating `Version` (i.e. kubernetes version) if the current kube nodegroup version is different, then by default AMI will be automatically the lastest working version.

> Version
> The Kubernetes version to use for your managed nodes. By default, the Kubernetes version of the cluster is used, and this is the only accepted specified value.
> 
> Required: No
> 
> Type: String

> ReleaseVersion
> The AMI version of the Amazon EKS-optimized AMI to use with your node group (for example, 1.14.7-YYYYMMDD). By default, the latest available AMI version for the node group's current Kubernetes version is used. For more information, see Amazon EKS-Optimized Linux AMI Versions in the Amazon EKS User Guide.
> 
> Note
> Changing this value triggers an update of the node group if one is available. However, only the latest available AMI release version is valid as an input. You cannot roll back to a previous AMI release version.
> 
> Required: No
> 
> Type: String
> 
> Update requires: No interruption

**Comment by sayboras** [comment] 2020-03-25 08:57
@fmedery @martina-if @marccarre @cPu1 love to hear your thoughts :100:

**Comment by martina-if** [comment] 2020-03-25 13:01
related to https://github.com/aws/containers-roadmap/issues/771

**Comment by cPu1** [comment] 2020-04-06 11:16
>In CF, we have two attributes Version and ReleaseVersion as per below. Even though, the underlying issue is due to AWS inconsistent values/behavior between services (e.g. SSM, AMI, CF), we still can make one improvement in which just updating Version (i.e. kubernetes version) if the current kube nodegroup version is different, then by default AMI will be automatically the lastest working version.

@sayboras great find. However, that'll be a short-term workaround as the AWS team have informed us that they're currently building automation so in the future, the AMIs will be released for both managed and self-managed nodes at the same time. Moreover, the command (`eksctl upgrade nodegroup`) is more generally designed to upgrade to the latest available AMI for the specified _or_ current Kubernetes version.

**Comment by sayboras** [comment] 2020-04-06 12:09
@cPu1 glad to hear that AWS team is on top of this :100:

Let me close the related PR https://github.com/weaveworks/eksctl/pull/1966, we can re-open it anytime if it's required.

**Comment by cPu1** [comment] 2020-04-13 15:15
>Surprisingly, if I am creating a new managed cluster with 1.15, it's working fine.

@sayboras could you elaborate what you meant by "it's working fine"? I thought you meant that you're getting the latest AMI release (`1.15.10-20200312` was the latest when this issue was posted) for your managed nodegroups when creating a new cluster with a managed nodegroup. However, this doesn't seem to be the case as I am getting the same (older) AMI release (`1.15.10-20200228`) for new managed nodegroups that the error message in the issue states as being the only allowed version:

>Allowed release version is 1.15.10-20200228

**Comment by sayboras** [comment] 2020-04-13 22:15
> > Surprisingly, if I am creating a new managed cluster with 1.15, it's working fine.
> 
> @sayboras could you elaborate what you meant by "it's working fine"? I thought you meant that you're getting the latest AMI release (`1.15.10-20200312` was the latest when this issue was posted) for your managed nodegroups when creating a new cluster with a managed nodegroup. However, this doesn't seem to be the case as I am getting the same (older) AMI release (`1.15.10-20200228`) for new managed nodegroups that the error message in the issue states as being the only allowed version:
> 
> > Allowed release version is 1.15.10-20200228

Hi @cPu1, it's working fine if we are creating a **_new_** managed cluster instead of upgrading to 1.15 for existing cluster. While creating new cluster, we didn't pass  either `Version` or `ReleaseVersion` in node group CF stack, the Kubernetes version of the cluster is used (by default) [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-nodegroup.html#cfn-eks-nodegroup-version) (i.e. 1.15). 

Sorrry for confusion about **_latest AMI release_**, what I meant is the latest AMI release **_supported by CF._**. This is the reason why I made changes in #1966, which is doing nothing but just delegate to CF to manage AMI version. However, this might not be aligned with https://github.com/aws/containers-roadmap/issues/810

**Comment by cPu1** [comment] 2020-04-14 10:21
>Hi @cPu1, it's working fine if we are creating a new managed cluster instead of upgrading to 1.15 for existing cluster. While creating new cluster, we didn't pass either Version or ReleaseVersion in node group CF stack, the Kubernetes version of the cluster is used (by default) docs (i.e. 1.15).

I was aware of this. I thought you meant it uses the latest available AMI, but realised later you might've meant that just the nodegroup creation is working fine (while still using an old AMI release). Thanks for clarifying.

The reason I asked for clarification, and also tried it myself was because I was thinking of a workaround that'd let us upgrade a managed nodegroup to the latest available AMI, but it won't work because CF doesn't really use the latest available AMI release if the `releaseVersion` is unset.

**Closed** 2020-05-12 09:33 UTC
Labels: kind/bug, priority/important-longterm
