### ISSUE TITLE
feat(nodegroup): new integration: spot ocean

### ISSUE THREAD

**Issue by idanshoham95** [weaveworks/eksctl#6694] opened 2023-06-14 14:23 UTC
### Why do you want this feature?
Similarly to the existing [integration with kops instance groups](https://kops.sigs.k8s.io/getting_started/spot-ocean/), we'd like to integrate [Ocean](https://spot.io/products/ocean/) by [Spot](https://spot.io/) with eksctl.

### What feature/behavior/change do you want?
Seamlessly integration of [Ocean](https://spot.io/products/ocean/) with unmanaged nodegroups, as part of a demand of AWS customers.

### Pull request
https://github.com/weaveworks/eksctl/pull/6731

Please check out our [proposal documentation](https://github.com/spotinst/weaveworks-eksctl/blob/c35002e7f57dc3fd74d5e2bf764de64239171799/docs/proposal-009-spot-ocean.md).

**Comment by jslaughterSpot** [comment] 2023-06-22 16:06
Along with the above proposal, I want to add some context and stress the demand we are seeing on this side.

Demand for an upstream integration has been increasing as users continue to utilize this tool and expect official, maintained and updated resources. I get this request from a variety of our users on a weekly basis and it's only growing.

In terms of support and maintenance:

Spot by Netapp pledges to fully maintain this integration.
This includes:

- Monthly updates with new features
- Code reviews and feature assessment from the direct EKSCTL community
- Feature parity with our direct API and UI enabling EKSCTL all the latest features
- Spot by Netapp fully managing Support and maintenance of this integration
  - Bug fixes directly from the EKSCTL community
  - Urgent 24/7 support available on our platform
  - Ensuring full compatibility with the newest versions of Kubernetes and EKS

**Comment by swharr** [comment] 2023-06-22 16:21
I would just like to echo that this feature being added would be helpful. I have several ocean clusters and would like to be able to use eksctl to manage them a bit tighter than having to bounce around between CLI management tools.

**Comment by rjmorse** [comment] 2023-06-22 16:27
At Ticketmaster we leverage Spot by NetApp via the current forked EKSCTL to manage our EKS clusters, and have been doing so for years. Over the last year I've seen management of the fork improve (more quickly and regularly rebase upstream changes to the fork as well as adding Spot API support for new Spot/NetApp features) and we would very much appreciate the ability to upstream this capability.

I have to acknowledge the previous attempt at https://github.com/weaveworks/eksctl/issues/2364 and my hope is this is presented in a more suitable manner and possibly work together to progress this.

**Comment by rcohen650** [comment] 2023-06-22 16:40
This would be game changing for our usage of eksctl

**Comment by camclay** [comment] 2023-06-22 16:42
Would greatly appreciate this work being upstreamed, as Kubernetes continues to rapidly develop, having tighter integration of the full EKSCTL with Spot by NetApp helps us to avoid version issues, ans maintain our fleet of EKS clusters in multiple regions.

**Comment by wlieberz** [comment] 2023-06-22 16:48
I'd definitely like to see this upstreamed. I believe it would help reduce ecosystem fragmentation and provide a better experience for eksctl users.

**Comment by usmanakramb** [comment] 2023-06-22 16:58
Would be great to have upstream support and streamline usage of eksctl

**Comment by Sconrad04** [comment] 2023-06-22 17:58
I would definitely love to see this integration for all the reasons mentioned above.

**Comment by soubhik001** [comment] 2023-06-22 17:59
We love managing kubernetes via cli and eksctl is too handy to create a cluster/node group. A direct integration to create an Ocean cluster/node group using eksctl would give us an effortless way to create and maintain unmanaged Kubernetes clusters through Ocean and save a lot of time. Really looking forward to see it getting upstreamed.

**Comment by ultgeek** [comment] 2023-06-22 18:57
This would be a very welcome addition to our use case.

**Comment by Shoobe13** [comment] 2023-06-22 19:29
This integration would be a huge benefit for our usage of eksctl!

**Comment by JenniferFlanaganSpot** [comment] 2023-06-22 20:39
I see a ton of value for our joint customers getting this upstreamed. Prioritize this :)

**Comment by kaugm** [comment] 2023-06-22 21:11
Eksctl is a super useful tool, and this integration would be hugely beneficial for simplifying management of Ocean nodegroups as well. Please add!

**Comment by victorvianas** [comment] 2023-06-22 23:21
Would love to see this integration working. One of the best ways to manage EKS clusters is by using CLI tools like eksctl, and having a daily usage tool working together with Spot by NetApp products will save a ton of DYI work for DevOps Engineers / SREs, etc. Can't agree more with the other users who commented on this thread.

**Comment by CrisNevares** [comment] 2023-06-24 01:27
Would love to see this upstreamed!

**Comment by denishelena** [comment] 2023-06-26 12:46
Hello everyone, we are working with eksctl to provision the Kubernetes cluster, and today have two possibilities, create a Cluster with Spotinst integration and without Spotinst integration. We have seen a bad experience working with two different implementations that are the same thing. It makes sense that Waveworks adds that possibility to the same project, considering that big companies already work with this implementation.

**Comment by jescarri** [comment] 2023-06-29 15:48
Eksctl is a great tool for managing eks clusters, at Ticketmaster we run eks + spot.io, and we manage the clusters using the forked version of eksctl with the spot.io integration, over the years the quality of the integration has improved and support from spot.io on keeping the fork up to date has been great.

We would love to see the support for spot.io in Eksctl upstreamed.

**Comment by Himangini** [comment] 2023-06-29 16:27
Dupe of #2364 
Decision comment on the previous thread: https://github.com/weaveworks/eksctl/issues/2364#issuecomment-843267265

@mikestef9 There's a lot of interest from the community for this feature, can we reconsider the decision?

**Comment by swharr** [comment] 2023-07-12 16:04
> Dupe of #2364 Decision comment on the previous thread: [#2364 (comment)](https://github.com/eksctl-io/eksctl/issues/2364#issuecomment-843267265)
> 
> @mikestef9 There's a lot of interest from the community for this feature, can we reconsider the decision?

I am wondering whats next to get this feature request reconsidered. I know that two years ago it was decided not to integrate, but as the traffic above shows there is a lot of desire to have this feature bolted in upstream

**Comment by mikestef9** [comment] 2023-07-14 20:43
The stance has not changed since the original comment. However, since that comment, we have launched native EKS add-ons marketplace integration https://aws.amazon.com/blogs/aws/new-aws-marketplace-for-containers-now-supports-direct-deployment-to-amazon-eks-clusters/

Adding the Ocean controller to EKS add-ons Marketplace integration is best path forward here.

**Comment by mataneja** [comment] 2023-07-18 16:20
@mikestef9 AWS MP for containers _only_ solves for Ocean helm charts but offers "no" solution for managing Ocean via standard Infrastructure as Code primitives aka eksctl. Is there an alternate ability in the AWS MP to solve for eksctl?

**Comment by tanvp112** [comment] 2023-08-12 10:11
Spot Ocean is a **commercial product** and not open source, right? Best to integrate with marketplace.

**Closed as completed** 2023-10-10 09:56 UTC
Labels: kind/feature
