### ISSUE TITLE
Config file Yaml Anchors and references do not allow overrides

### ISSUE THREAD

**Issue by zanven42** [weaveworks/eksctl#4062] opened 2021-08-09 10:41 UTC
when trying to define nodegroups the below errors

```yaml
nodeGroups:
  - &foo
    name: test
  - <<: *foo
    name: bar
```
```sh
$ eksctl create nodegroup -f ./clusterconfig-dev.eksctl.yaml --dry-run
Error: couldn't create node group filter from command line options: loading config file "./clusterconfig-dev.eksctl.yaml": error converting YAML to JSON: yaml: unmarshal errors:
  line 41: key "name" already set in map
```

example taken from a bigger file than the one provided.

The reason for wanting this is so i can more easily reuse massive definitions to avoid human error on node creation. ( also being able to define extra unused yaml keys would be nice as they come through as undefined )
i.e

```yaml
foo:
  - &node1
    name: foo
nodeGroup:
  - *node1
  ```
  
  ```sh
  $ eksctl create nodegroup -f ./clusterconfig-dev.eksctl.yaml --dry-run
Error: couldn't create node group filter from command line options: loading config file "./clusterconfig-dev.eksctl.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "node1"
```

**Comment by Callisto13** [comment] 2021-08-09 11:15
Hi @zanven42 👋 

This looks like a dupe of https://github.com/weaveworks/eksctl/issues/2956 and https://github.com/weaveworks/eksctl/issues/1104. It looks like there is a solution in the second link, could you verify whether this works for you?

**Comment by zanven42** [comment] 2021-08-09 12:06
in #1104 doing a direct inline does allow for anchors and references to work, which would be enough for me to minimise the amount of typing occurring and work around the limitations of its usage. 

The remainder of the issue would be to allow overwriting duplicate keys which would be expected yaml behaviour, which the solution in #1104 does not include. This is most definitely a dupe of #2956 which has also gone stale upstream in its reporting.

**Comment by Callisto13** [comment] 2021-08-10 08:22
> which would be enough for me to minimise the amount of typing occurring and work around the limitations of its usage.

👍  cool

> which has also gone stale upstream in its reporting

Yeh that's annoying. They don't seem to pay much attention to their issues, maybe opening a dupe one may get attention back on it? Even if it just gets them to say it is a dupe 😂 

I am gonna close this issue 👍

**Closed by Callisto13** 2021-08-10 08:22 UTC
Labels: kind/feature
