### ISSUE TITLE
more helpful behaviour when initial nodegroup fails

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#640] opened 2019-03-17 15:27 UTC
Right now we only write kubeconfig once a nodegroup was created. We should allow user to retry creating the nodegroup separately, and at least specify what commands they can run to do so, and we could write kubeconfig too. This handy because cluster itself takes longer to create, and nodegroup creation failure doesn't mean anything is wrong with the cluster, it could be just an issue with custom fields user sets.

**Comment by michaelbeaumont** [comment] 2021-01-28 07:31
Duplicate of #2125

**Closed by michaelbeaumont** 2021-01-28 07:31 UTC
Labels: area/general-cli, area/nodegroup, needs-investigation, priority/backlog
