### ISSUE TITLE
Missing support on label alpha.service-controller.kubernetes.io/exclude-balancer

### ISSUE THREAD

**Issue by zhiyanliu** [weaveworks/eksctl#1830] opened 2020-02-20 04:33 UTC
**What happened?**
When you want to label node in the group with label "alpha.service-controller.kubernetes.io/exclude-balancer", ``eksctl`` raises an error "Error: unknown 'kubernetes.io' or 'k8s.io' labels were specified: [alpha.service-controller.kubernetes.io/exclude-balancer]"

**How to reproduce it?**
1. Prepare a nodegroup configuration yaml file ``test.yaml`` which contains the label like this.
```
labels:
        alpha.service-controller.kubernetes.io/exclude-balancer: "true"
```
2. Create the nodegroup, the error will raise up.
```
eksctl create nodegroup -f test.yaml
Error: unknown 'kubernetes.io' or 'k8s.io' labels were specified: [alpha.service-controller.kubernetes.io/exclude-balancer]
```

**What you expected to happen?**
``eksctl`` should support label ``alpha.service-controller.kubernetes.io/exclude-balancer`` just like ``node.kubernetes.io/exclude-from-external-load-balancers`` for the node. Kubernetes v1.14 only support label ``alpha.service-controller.kubernetes.io/exclude-balancer`` but don't support ``node.kubernetes.io/exclude-from-external-load-balancers`` ([0] vs. [1]), and *currently* AWS EKS supported latest Kubernetes version is 1.14.9, so we can only to use former label at the moment.
Without the fix for this issue, operator needs to label the node manually for the EKS cluster.

[0] https://v1-14.docs.kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
[1] https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Anything else we need to know?**
The root cause is the validation logic at [2], the valid label ``alpha.service-controller.kubernetes.io/exclude-balancer`` is not listed in the exception list and, don't like ``node.kubernetes.io``, ``alpha.service-controller.kubernetes.io`` is not considered as an allowed ``kubelet`` namespace as well.

[2] https://github.com/weaveworks/eksctl/blob/master/pkg/apis/eksctl.io/v1alpha5/validation.go#L253-L282

**Versions**
```
eksctl version: version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.13.0"}
kubectl version: Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
```

Need anything else input, please let me know, thanks!

**Comment by sayboras** [comment] 2020-03-12 09:49
@zhiyanliu I think it should be fixed as part of https://github.com/weaveworks/eksctl/pull/1879. 

Please give it a try with recent releases and check if the issue is still happening.

**Comment by zhiyanliu** [comment] 2020-03-12 18:23
the change lgtm @sayboras

**Closed** 2020-03-12 18:24 UTC
Labels: kind/bug
