### ISSUE TITLE
AMI auto error with eksctl 0.58.0

### ISSUE THREAD

**Issue by TFAssKID** [weaveworks/eksctl#4029] opened 2021-07-28 06:35 UTC
In version 0.58.0 when I will to deploy cluster with this command:

```bash
eksctl create cluster \
--name XYZ \
--version 1.20 \
--node-private-networking \
--nodegroup-name standard-workers \
--node-type m4.large \
--nodes 2 \
--node-ami auto \
--region us-east-1 \
--with-oidc
```
appear this error:

```bash
Error: invalid AMI "auto" (managedNodeGroups[0].ami)
```
In previusly versions of eksctl work perfectly

**Comment by nikimanoledaki** [comment] 2021-07-28 08:49
Thanks for raising this issue @TFAssKID, I was able to reproduce this and it does look like a regression. Will try to get a fix for this asap!

**Comment by nikimanoledaki** [comment] 2021-07-28 10:01
Hi again! You are coming across this issue now because `--node-ami auto` is a feature of unmanaged nodegroups and we recently introduced a breaking change where nodegroups are now managed by default. More info [here](https://eksctl.io/usage/managed-nodegroups-announcement/) and [here](https://github.com/weaveworks/eksctl/issues/3692), and the docs have also been updated to reflect this.

The simplest way to make your command work as it did before is by adding `--managed=false` to it, which will create an unmanaged nodegroup.

If you'd like to create managed nodegroup instead, you can do so by adding an `overrideBootstrapCommand`, more info [here](https://eksctl.io/usage/custom-ami-support/).

I hope this answers your question and I will close this issue now but feel free to reopen it or get in touch if there's anything else!

**Closed by nikimanoledaki** 2021-07-28 10:01 UTC
Labels: kind/bug
