### ISSUE TITLE
Support a new AWSCLI config format with AWS SSO 

### ISSUE THREAD

**Issue by aibou** [weaveworks/eksctl#1565] opened 2019-11-18 09:49 UTC
**Why do you want this feature?**

In my organization, we started using AWS SSO to login AWS Console, to generate AWS session credentials.
And recently, AWSCLI v2 supports AWS SSO that enables us not to need to rewrite the credentials in `~/.aws/credentials`.
Before this release, we should rewrite `~/.aws/credentials` when the credentials are expired.
It is so useful.

https://aws.amazon.com/jp/blogs/developer/aws-cli-v2-now-supports-aws-single-sign-on/

----

However, eksctl (not just eksctl) does not support it.
So I have to use fixed credentials, it's troublesome for me. 😢

**What feature/behavior/change do you want?**

I would be able to run eksctl command with below configuration:

```~/.aws/config
[profile develop]
sso_start_url = https://xyzxyzxyz.awsapps.com/start
sso_region = us-west-2
sso_account_id = 01234567890123
sso_role_name = AdministratorAccess # <- This parameter named 'Permission Sets' by AWS SSO
region = ap-northeast-1
output = json
```

```
$ AWS_PROFILE=develop eksctl create cluster -f cluster.yml
```

**Comment by atifrasheed79** [comment] 2020-02-21 00:55
Hi, is it something currently being worked on? Should we expect eksctl supporting SSO creds soon or we have to live with IAM users for now?

**Comment by shridhar-at-droit** [comment] 2020-02-24 11:22
Hello,

**Comment by pfiled** [comment] 2020-05-20 21:24
I'm currently use aws2-wrap: https://github.com/linaro-its/aws2-wrap

It would be nice if this was built in though.

**Comment by bitva77** [comment] 2020-11-24 06:35
Just wishing this issue a happy birthday.  It's been a year!

AWS: "Use the aws cli, it's super cool"
Also AWS: "use eksctl to create EKS clusters, it's super cool"

AWS whispering while walking away: "oh they're not fully compatible so good luck to you"

**Comment by DanielAmmar** [comment] 2020-12-28 09:36
btw, I don't know if it is related but i'm getting cryptic error message when running eksctl (using sso profile):
`eksctl get clusters --verbose=4`

`
2020-12-28T11:28:01+02:00 [!]  retryable error (RequestError: send request failed
caused by: Put "http://169.254.169.254/latest/api/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)) from ec2metadata/GetToken - will retry after delay of 57.510881ms
...
`

**Comment by bitva77** [comment] 2020-12-29 04:54
@DanielAmmar yeah I get that when using credentials from an `aws configure sso` but when I use the creds copied from a browser console login, it works fine with eksctl.

No idea what the difference could possibly be

**Comment by urz9999** [comment] 2021-01-14 11:05
In case like this one or other similar cases where AWS SSO result in incompatibilities with your library and you don't want to play with workarounds or complicated fixes, maybe you can give a try to our open-source project: [https://github.com/Noovolari/leapp](https://github.com/Noovolari/leapp). It deals with AWS SSO authentication and accounts/roles retrieval then it creates short-lived temporary credentials in .aws/credentials to maximize compatibility with third party tools / sdks.

**Comment by aclevername** [comment] 2021-03-18 13:46
eksctl hands off the majority of the authentication handling to the aws-sdk-go. Since [aws-sdk-go version 1.37.0](https://github.com/aws/aws-sdk-go/releases/tag/v1.37.0) they added support for AWS SSO. If you try the latest version of eksctl `v0.40.0` I think it will work as we've bumped to use the latest aws-sdk-go. I haven't been able to test this, @DanielAmmar @bitva77 @aibou please let me know if it works, then I can close this issue 😄  Thanks!

**Comment by aibou** [comment] 2021-03-23 10:16
Thank you for your notification! I tried to authenticate for AWS SSO with eksctl `v0.41.0`, and it was successful! 😄
I appreciate very much your corporation. Thank you!

**Comment by aclevername** [comment] 2021-03-23 10:24
> Thank you for your notification! I tried to authenticate for AWS SSO with eksctl `v0.41.0`, and it was successful! 
> I appreciate very much your corporation. Thank you!

Amazing! Glad it worked :smile: 

closing the issue as its now resolved.

**Closed by aclevername** 2021-03-23 10:24 UTC
Labels: blocked/upstream, help wanted, kind/feature, priority/important-soon
