### ISSUE TITLE
eksctl create times out when adding nodes to the cluster

### ISSUE THREAD

**Issue by bonelli** [weaveworks/eksctl#1251] opened 2019-09-02 16:26 UTC
**What happened?**
The creation of a new cluster with eksctl times out when adding nodes to the cluster. The EC2 instances are created, but nodes do not join the nodegroup.

**What you expected to happen?**
I expect the nodes to join the cluster and the creation to finish successfully.

**How to reproduce it?**
In the [bug-report.zip](https://github.com/weaveworks/eksctl/files/3566676/bug-report.zip) i have included the eksctl config file, the eksctl log and the cloudformation stack description taken after the moment in which eksctl failed with the timeout. 

**Anything else we need to know?**
Compiled binary of eksctl version 0.4.3
Linux Ubuntu 18.04.2 LTS

**Versions**

Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.4.3"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-21T15:34:43Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
In the [bug-report.zip](https://github.com/weaveworks/eksctl/files/3566676/bug-report.zip) i have included the eksctl config file, the eksctl log and the cloudformation stack description taken after the moment in which eksctl failed with the timeout.

**Comment by achandak123** [comment] 2019-09-03 16:55
👍 i am hitting the same issue. Here is the output of the describe nodes

```
Name:               ip-192-168-107-166.us-west-2.compute.internal
Roles:              <none>
Labels:             alpha.eksctl.io/cluster-name=spy
                    alpha.eksctl.io/instance-id=i-0d21257e1b4c1d3e8
                    alpha.eksctl.io/nodegroup-name=ng-2dd3b513
                    beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=m5.8xlarge
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=us-west-2
                    failure-domain.beta.kubernetes.io/zone=us-west-2b
                    kubernetes.io/hostname=ip-192-168-107-166.us-west-2.compute.internal
Annotations:        node.alpha.kubernetes.io/ttl=0
                    volumes.kubernetes.io/controller-managed-attach-detach=true
CreationTimestamp:  Fri, 30 Aug 2019 14:12:32 -0700
Taints:             <none>
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  OutOfDisk        False   Tue, 03 Sep 2019 09:54:55 -0700   Fri, 30 Aug 2019 14:12:30 -0700   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False   Tue, 03 Sep 2019 09:54:55 -0700   Fri, 30 Aug 2019 14:12:30 -0700   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Tue, 03 Sep 2019 09:54:55 -0700   Fri, 30 Aug 2019 14:12:30 -0700   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Tue, 03 Sep 2019 09:54:55 -0700   Fri, 30 Aug 2019 14:12:30 -0700   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            False   Tue, 03 Sep 2019 09:54:55 -0700   Fri, 30 Aug 2019 14:12:30 -0700   KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Addresses:
  InternalIP:   192.168.107.166
  InternalDNS:  ip-192-168-107-166.us-west-2.compute.internal
  Hostname:     ip-192-168-107-166.us-west-2.compute.internal
Capacity:
 cpu:                32
 ephemeral-storage:  104845292Ki
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             129144676Ki
 pods:               0
Allocatable:
 cpu:                32
 ephemeral-storage:  96625420948
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             129042276Ki
 pods:               0
System Info:
 Machine ID:                 ec2529652c475c59d71f77dd95fe5bd0
 System UUID:                EC252965-2C47-5C59-D71F-77DD95FE5BD0
 Boot ID:                    419e1526-9089-4f8f-9148-5a0422e23a11
 Kernel Version:             4.14.97-90.72.amzn2.x86_64
 OS Image:                   Amazon Linux 2
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.6.1
 Kubelet Version:            v1.11.5
 Kube-Proxy Version:         v1.11.5
ExternalID:                  ip-192-168-107-166.us-west-2.compute.internal
ProviderID:                  aws:///us-west-2b/i-0d21257e1b4c1d3e8
Non-terminated Pods:         (0 in total)
  Namespace                  Name    CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----    ------------  ----------  ---------------  -------------
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ------------  ----------  ---------------  -------------
  0 (0%)        0 (0%)      0 (0%)           0 (0%)
Events:         <none>
```

**Comment by SeanTurner026** [comment] 2019-09-24 20:27
I'm running into this problem as well. 

I can't see my nodes though.
```
$ kubectl get nodes
No resources found in default namespace.
```

I can see my `kubernetes` service
```
$ kubectl get service
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.100.0.1   <none>        443/TCP   52m
```

The two cloudformation stacks (nodepool and eks cluster) completed successfully.

Here's my `eksctl` output.

```
$ eksctl create cluster -f cluster.yaml  --set-kubeconfig-context
[ℹ]  using region us-east-1
[✔]  using existing VPC (vpc-085786b3059cea8ef) and subnets (private:[subnet-0967adad0fee148ec subnet-0f6cf3a6540008d5b subnet-03efddf6dd735135b] public:[])
[!]  custom VPC/subnets will be used; if resulting cluster doesn't function as expected, make sure to review the configuration of VPC/subnets
[ℹ]  nodegroup "nodeGroup-1" will use "ami-0d3998d69ebe9b214" [AmazonLinux2/1.13]
[ℹ]  using Kubernetes version 1.13
[ℹ]  creating EKS cluster "eks-cross-team" in "us-east-1" region
[ℹ]  1 nodegroup (nodeGroup-1) was included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for cluster itself and 1 nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-east-1 --name=eks-cross-team'
[ℹ]  CloudWatch logging will not be enabled for cluster "eks-cross-team" in "us-east-1"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=us-east-1 --name=eks-cross-team'
[ℹ]  2 sequential tasks: { create cluster control plane "eks-cross-team", create nodegroup "nodeGroup-1" }
[ℹ]  building cluster stack "eksctl-eks-cross-team-cluster"
[ℹ]  deploying stack "eksctl-eks-cross-team-cluster"
[ℹ]  building nodegroup stack "eksctl-eks-cross-team-nodegroup-nodeGroup-1"
[ℹ]  deploying stack "eksctl-eks-cross-team-nodegroup-nodeGroup-1"
[✔]  all EKS cluster resource for "eks-cross-team" had been created
[✔]  saved kubeconfig as "/Users/seanturner/.kube/config"
[ℹ]  adding role "arn:aws:iam::098006065408:role/eksctl-eks-cross-team-nodegroup-n-NodeInstanceRole-1K0SDHHIBBE7W" to auth ConfigMap
[ℹ]  nodegroup "nodeGroup-1" has 0 node(s)
[ℹ]  waiting for at least 2 node(s) to become ready in "nodeGroup-1"
[✖]  timed out (after 25m0s) waiting for at least 2 nodes to join the cluster and become ready in "nodeGroup-1"
```

**Comment by martina-if** [comment] 2020-03-19 17:01
Seems this is not happening anymore so I will close this. Please reopen if this issue is still happening in newer versions of eksctl.

**Closed by martina-if** 2020-03-19 17:01 UTC
Labels: awaiting more information, kind/bug

**Comment by 99pavan** [comment] 2020-08-17 09:20
what is the cause for this timeout issue. Since cluster creation time through the eksctl will take more time, Please provide accurate solution for this.No solution provided still in any of the duplicate ticket as well.

**Comment by redbitshift** [comment] 2020-12-10 05:13
I am seeing timeout on eksctl v0.33.

The node is there. 

```
...
[i]  waiting for at least 1 node(s) to become ready in "linux-nodegroup"
Error: timed out (after 25m0s) waiting for at least 1 nodes to join the cluster and become ready in "linux-nodegroup"
```

**Comment by EngHabu** [comment] 2020-12-30 22:20
Same here...
```
[ℹ]  nodegroup "ng-1" has 0 node(s)
[ℹ]  waiting for at least 5 node(s) to become ready in "ng-1"
Error: timed out (after 25m0s) waiting for at least 5 nodes to join the cluster and become ready in "ng-1"
```

**Comment by alexistdk** [comment] 2021-09-03 13:12
Same here

`[ℹ]  nodegroup "prod-stg-t3-large-Node" has 0 node(s)
[ℹ]  waiting for at least 1 node(s) to become ready in "prod-stg-t3-large-Node"
Error: timed out (after 25m0s) waiting for at least 1 nodes to join the cluster and become ready in "prod-stg-t3-large-Node"
`
