### ISSUE TITLE
Delete nodegroup may fail to drain when using PodDisruptionBudget

### ISSUE THREAD

**Issue by gdrudy** [weaveworks/eksctl#1052] opened 2019-07-23 10:04 UTC
**What happened?**
The cluster is using 3 nodegroups, each in a different AZ and each with a single node/instance.
Five of the applications running on the cluster define a PodDisruptionBudget. All 5 apps have minReplicas set to 3 though some have 3 replicas running while others have 2 replicas running. The PDB shows:

kubectl get pdb --all-namespaces
NAMESPACE      NAME                   MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
istio-system   istio-galley           1               N/A               1                     1d
istio-system   istio-ingressgateway   1               N/A               1                     1d
istio-system   istio-pilot            1               N/A               2                     1d
istio-system   istio-policy           1               N/A               2                     1d
istio-system   istio-telemetry        1               N/A               2                     1d

After modifying all 3 nodegroups in the config file and successfully running 'eksctl create nodegroup', I run the delete nodegroup after all of the pods had settled:

$ eksctl delete nodegroup -f eksctl-3-nodegroup.yaml --only-missing --wait --approve --timeout 5m -v 5

Two of the three nodes drain successfully, but the third fails:

2019-07-23T10:01:53+01:00 [ℹ]  will drain 3 nodegroups in cluster "eksctl3"
2019-07-23T10:01:54+01:00 [ℹ]  cordon node "ip-226.compute.internal"
2019-07-23T10:01:54+01:00 [▶]  already drained: []
2019-07-23T10:01:54+01:00 [▶]  will drain: [ip-226.compute.internal]
2019-07-23T10:01:56+01:00 [!]  ignoring DaemonSet-managed Pods: istio-system/istio-cni-node-zg7vx, kube-system/aws-node-m984d, kube-system/calico-node-z6g9w, kube-system/fluentd-logzio-nbrkh, kube-system/kube-proxy-hsq6d, monitoring/node-exporter-n4pfh
2019-07-23T10:01:59+01:00 [▶]  15 pods to be evicted from ip-226.compute.internal
2019-07-23T10:02:00+01:00 [▶]  no need to cordon node "ip-226.compute.internal"
2019-07-23T10:02:00+01:00 [▶]  already drained: []
2019-07-23T10:02:00+01:00 [▶]  will drain: [ip-226.compute.internal]
2019-07-23T10:02:01+01:00 [!]  ignoring DaemonSet-managed Pods: istio-system/istio-cni-node-zg7vx, kube-system/aws-node-m984d, kube-system/calico-node-z6g9w, kube-system/fluentd-logzio-nbrkh, kube-system/kube-proxy-hsq6d, monitoring/node-exporter-n4pfh
2019-07-23T10:02:01+01:00 [▶]  0 pods to be evicted from ip-226.compute.internal
2019-07-23T10:02:01+01:00 [✔]  drained nodes: [ip-226.compute.internal]
2019-07-23T10:02:02+01:00 [ℹ]  cordon node "ip-195.compute.internal"
2019-07-23T10:02:02+01:00 [▶]  already drained: []
2019-07-23T10:02:02+01:00 [▶]  will drain: [ip-195.compute.internal]
2019-07-23T10:02:04+01:00 [!]  ignoring DaemonSet-managed Pods: istio-system/istio-cni-node-fwtj7, kube-system/aws-node-6qrqt, kube-system/calico-node-j8wp2, kube-system/fluentd-logzio-9xqv9, kube-system/kube-proxy-5zhl8, monitoring/node-exporter-cl2r9
2019-07-23T10:02:08+01:00 [▶]  17 pods to be evicted from ip-195.compute.internal
2019-07-23T10:02:08+01:00 [▶]  no need to cordon node "ip-195.compute.internal"
2019-07-23T10:02:08+01:00 [▶]  already drained: []
2019-07-23T10:02:08+01:00 [▶]  will drain: [ip-195.compute.internal]
2019-07-23T10:02:09+01:00 [!]  ignoring DaemonSet-managed Pods: istio-system/istio-cni-node-fwtj7, kube-system/aws-node-6qrqt, kube-system/calico-node-j8wp2, kube-system/fluentd-logzio-9xqv9, kube-system/kube-proxy-5zhl8, monitoring/node-exporter-cl2r9
2019-07-23T10:02:09+01:00 [▶]  0 pods to be evicted from ip-195.compute.internal
2019-07-23T10:02:09+01:00 [✔]  drained nodes: [ip-195.compute.internal]
2019-07-23T10:02:10+01:00 [ℹ]  cordon node "ip-21.compute.internal"
2019-07-23T10:02:10+01:00 [▶]  already drained: []
2019-07-23T10:02:10+01:00 [▶]  will drain: [ip-21.compute.internal]
2019-07-23T10:02:12+01:00 [!]  ignoring DaemonSet-managed Pods: istio-system/istio-cni-node-5cnw5, kube-system/aws-node-2jfv6, kube-system/calico-node-mcl6l, kube-system/fluentd-logzio-2vkp7, kube-system/kube-proxy-wqrsg, monitoring/node-exporter-w2v8j
2019-07-23T10:02:13+01:00 [✖]  Cannot evict pod as it would violate the pod's disruption budget.

At this point istio-ingressgateway had 1 pod running on the node that failed to drain i.e. p-21.compute.internal and 2 other pods running on the other nodes but both pods were not ready:
istio-ingressgateway-5798b49b67-9jb72     0/1       Running             0          23s       .250   ip-245.compute.internal
istio-ingressgateway-5798b49b67-jpd6h     0/1       Running             0          23s       .70    ip-226.compute.internal
istio-ingressgateway-5798b49b67-v7clf     1/1       Running             0          1h        .124   ip-21.compute.internal

PDB indicates that istio-ingressgateway and indeed istio-pilot were not in a position to be drained:
kubectl get pdb --all-namespaces
NAMESPACE      NAME                   MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
istio-system   istio-galley           1               N/A               2                     1d
istio-system   istio-ingressgateway   1               N/A               0                     1d
istio-system   istio-pilot            1               N/A               0                     1d
istio-system   istio-policy           1               N/A               2                     1d
istio-system   istio-telemetry        1               N/A               2                     1d

i.e. ALLOWED DISUPTIONS is 0 for both apps.

**What you expected to happen?**
Perhaps the 'eksctl delete nodegroup' could hold off starting a node drain until the relocating pods have settled?

**How to reproduce it?**
Hopefully the above description should be enough to allow the problem be reproduced.

**Anything else we need to know?**

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.40"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-07-26T20:40:11Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**

**Comment by laghoule** [comment] 2019-08-06 14:24
Duplicate of https://github.com/weaveworks/eksctl/issues/693

**Comment by laghoule** [comment] 2019-08-09 20:34
Check your replicas setting for istio component. Unsufficient number of replicas will cause this.

**Comment by laghoule** [comment] 2019-08-30 13:41
After more test on my sandbox cluster, there is a bug. I'm working on a fix.

**Comment by laghoule** [comment] 2019-10-09 14:11
Should be fixed in eksctl 0.7.0

**Closed** 2020-03-19 16:51 UTC
Labels: kind/bug
