### ISSUE TITLE
Updating a cluster attempts to create a new ServiceRole

### ISSUE THREAD

**Issue by emoyer0928** [weaveworks/eksctl#2013] opened 2020-04-07 14:20 UTC
**What happened?**
I created a cluster with a custom VPC and IAM roles and then updated the cluster from 1.14 to 1.15.  The cluster update succeeds, but the cloud stack update fails when it attempts to create a new service role.

```
$ eksctl update cluster -n CLUSTER_NAME --approve
2020-04-07T09:14:03-04:00 [ℹ]  eksctl version 0.16.0
2020-04-07T09:14:03-04:00 [ℹ]  using region us-east-1
2020-04-07T09:14:07-04:00 [ℹ]  will upgrade cluster "CLUSTER_NAME" control plane from current version "1.14" to "1.15"
2020-04-07T09:25:34-04:00 [✔]  cluster "CLUSTER_NAME" control plane has been upgraded to version "1.15"
2020-04-07T09:25:34-04:00 [ℹ]  you will need to follow the upgrade procedure for all of nodegroups and add-ons
2020-04-07T09:25:35-04:00 [ℹ]  re-building cluster stack “STACK_NAME”
2020-04-07T09:25:35-04:00 [ℹ]  updating stack to add new resources [PolicyCloudWatchMetrics PolicyNLB ServiceRole] and outputs []
2020-04-07T09:26:27-04:00 [✖]  unexpected status "UPDATE_ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "STACK_NAME"
```

**What you expected to happen?**
I expected the cluster to update from 1.14 to 1.15 without creating new resources.  

**How to reproduce it?**
Create a version 1.14 cluster with a custom VPC and IAM (serviceRoleARN)
Create a managed node group with a custom IAM (instanceRoleARN)
Upgrade the cluster to version 1.15 (eksctl update cluster -n CLUSTER_NAME)

**Anything else we need to know?**
My account does not have the ability to create IAM or VPC resources.  This is why I created the cluster and node group with a custom VPC and IAM roles.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.16.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:17:09Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

```

**Logs**
```
2020-04-07T09:25:55-04:00 [▶]  changes = []*cloudformation.Change{{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "PolicyCloudWatchMetrics",
    ResourceType: "AWS::IAM::Policy"
  },
  Type: "Resource"
}, {
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "PolicyNLB",
    ResourceType: "AWS::IAM::Policy"
  },
  Type: "Resource"
}, {
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "ServiceRole",
    ResourceType: "AWS::IAM::Role"
  },
  Type: "Resource"
}}
2020-04-07T09:25:55-04:00 [▶]  executing changeSet, input = {
  ChangeSetName: “CHANGE_SET_NAME”,
  StackName: "STACK_NAME"
}
2020-04-07T09:25:55-04:00 [▶]  start waiting for CloudFormation stack "STACK_NAME"
2020-04-07T09:25:55-04:00 [▶]  waiting for CloudFormation stack "STACK_NAME"
2020-04-07T09:26:11-04:00 [▶]  waiting for CloudFormation stack "STACK_NAME"
2020-04-07T09:26:27-04:00 [▶]  waiting for CloudFormation stack "STACK_NAME"
2020-04-07T09:26:27-04:00 [✖]  unexpected status "UPDATE_ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "STACK_NAME"
2020-04-07T09:26:27-04:00 [ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
2020-04-07T09:26:28-04:00 [ℹ]  AWS::CloudFormation::Stack/STACK_NAME: UPDATE_ROLLBACK_IN_PROGRESS – "The following resource(s) failed to create: [ServiceRole]. "
2020-04-07T09:26:28-04:00 [ℹ]  AWS::IAM::Role/ServiceRole: CREATE_FAILED – "API: iam:CreateRole User: arn:aws:sts::X:assumed-role/X/X is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::X:role/STACK_NAME-ServiceRole-X with an explicit deny"
```

**Comment by martina-if** [comment] 2020-04-14 15:40
Hi emoyer0928,

Thank you for opening an issue. This is the way this command is intended to work. It updates the cluster and performs necessary updates in the cloudformation stacks to maintain compatibility with new features released in eksctl. I see how this can be an issue but for now there are no plans to decouple these two operations.

Let me check what could be a workaround for this and get back to you.

**Comment by emoyer0928** [comment] 2020-04-14 17:01
Thank you for the update.  I created a new 1.15 cluster as a work around.  When I created the new 1.15 cluster, with the same configuration files, it does not automatically create the role or policy for NLB.  Why are the new features optional when you create a 1.15 cluster but required when you upgrade to 1.15?

**Comment by martina-if** [comment] 2020-04-15 14:00
@emoyer0928 That's really strange, are you sure the new cluster didn't try to create those policies? I tried but I can't reproduce the case when a cluster is created without NLB. Can you give us more information like what arguments or config file you used and the output of the command?

**Comment by emoyer0928** [comment] 2020-04-15 19:13
I'm in a fairly restrictive environment.  I cannot create IAM roles or modify the VPC, and there isn't direct outbound internet access, so I use VPC endpoints.  The eksctl-cluster.yaml and eksctl-worker.yaml config files are in the attached zip.

I follow a 3 step process:  

1. Create the cluster, without node groups, using existing IAM roles and VPC.  Enable the private API endpoint.

$ eksctl create cluster -f eksctl-cluster.yaml
[ℹ]  eksctl version 0.16.0
[ℹ]  using region us-east-1
[✔]  using existing VPC (vpc-X) and subnets (private:[subnet-1a subnet-1b] public:[subnet-1a subnet-1b])
[!]  custom VPC/subnets will be used; if resulting cluster doesn't function as expected, make sure to review the configuration of VPC/subnets
[ℹ]  using Kubernetes version 1.15
[ℹ]  creating EKS cluster "test-eks-cluster" in "us-east-1" region with Fargate profile
[ℹ]  will create a CloudFormation stack for cluster itself and 0 nodegroup stack(s)
[ℹ]  will create a CloudFormation stack for cluster itself and 0 managed nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-east-1 --cluster=test-eks-cluster'
[ℹ]  CloudWatch logging will not be enabled for cluster "test-eks-cluster" in "us-east-1"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=us-east-1 --cluster=test-eks-cluster'
[ℹ]  Kubernetes API endpoint access will use provided values {publicAccess=true, privateAccess=true} for cluster "test-eks-cluster" in "us-east-1"
[ℹ]  2 sequential tasks: { create cluster control plane "test-eks-cluster", 3 sequential sub-tasks: { associate IAM OIDC provider, no tasks, update cluster VPC endpoint access configuration } }
[ℹ]  building cluster stack "eksctl-test-eks-cluster-cluster"
[ℹ]  deploying stack "eksctl-test-eks-cluster-cluster"
[✔]  all EKS cluster resources for "test-eks-cluster" have been created
[✔]  saved kubeconfig as "/Users/X/.kube/config"
[ℹ]  creating Fargate profile "fp-default" on EKS cluster "test-eks-cluster"
[ℹ]  created Fargate profile "fp-default" on EKS cluster "test-eks-cluster"
[ℹ]  kubectl command should work with "/Users/X/.kube/config", try 'kubectl get nodes'
[✔]  EKS cluster "test-eks-cluster" in "us-east-1" region is ready
  
2. Update security groups to allow the cluster SG to access the VPC endpoints for EC2, ECR DKR, and ECR API.  

3. Create a managed node group.
$ eksctl create nodegroup -f eksctl-worker.yaml
[ℹ]  eksctl version 0.16.0
[ℹ]  using region us-east-1
[ℹ]  will use version 1.15 for new nodegroup(s) based on control plane version
[ℹ]  1 nodegroup (test-eks-cluster-nodegroup) was included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for each of 1 managed nodegroups in cluster "test-eks-cluster"
[ℹ]  2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create managed nodegroup "test-eks-cluster-nodegroup" } } }
[ℹ]  checking cluster stack for missing resources
[ℹ]  cluster stack has all required resources
[ℹ]  building managed nodegroup stack "eksctl-test-eks-cluster-nodegroup-test-eks-cluster-nodegroup"
[ℹ]  deploying stack "eksctl-test-eks-cluster-nodegroup-test-eks-cluster-nodegroup"
[✔]  created 0 nodegroup(s) in cluster "test-eks-cluster"
[ℹ]  nodegroup "test-eks-cluster-nodegroup" has 2 node(s)
[ℹ]  node "ip-X-X-X-X.ec2.internal" is ready
[ℹ]  node "ip-X-X-X-Y.ec2.internal" is ready
[ℹ]  waiting for at least 1 node(s) to become ready in "test-eks-cluster-nodegroup"
[ℹ]  nodegroup "test-eks-cluster-nodegroup" has 2 node(s)
[ℹ]  node "ip-X-X-X-X.ec2.internal" is ready
[ℹ]  node "ip-X-X-X-Y.ec2.internal" is ready
[✔]  created 1 managed nodegroup(s) in cluster "test-eks-cluster"
[ℹ]  checking security group configuration for all nodegroups
[ℹ]  all nodegroups have up-to-date configuration


[eksctl-config.zip](https://github.com/weaveworks/eksctl/files/4483271/eksctl-config.zip)

**Comment by michaelbeaumont** [comment] 2020-05-07 11:13
@emoyer0928 It looks like this is due to the fact that you're upgrading the cluster by name, the case for which I can reproduce the error.
If however, you try to upgrade using the same `cluster.yaml` (i.e. with the explicit `serviceRoleArn`) you used to create the cluster, `eksctl` will not try to add any resources.

**Closed** 2020-05-12 11:11 UTC
Labels: area/upgrades, kind/bug, needs-investigation, priority/important-soon
