### ISSUE TITLE
Creating cluster incorrectly updates kubeconfig's authentication API versions

### ISSUE THREAD

**Issue by chazdnato** [weaveworks/eksctl#4867] opened 2022-03-01 17:15 UTC
**What were you trying to accomplish?**
Creating a cluster. We are using `aws sso login` for credentials. Cluster creation was as follows:

```eksctl create cluster --name chuck-dev --region us-east-1 --with-oidc --ssh-access --tags team=REDACTED,ManagedBy=true --version 1.21 --zones us-east-1a,us-east-1c,us-east-1f,us-east-1b --nodes 4
```

**What happened?**
The cluster was created successfully, but the kube config modification step failed:

```
2022-03-01 10:15:19 [✖]  unable to use kubectl with the EKS cluster (check 'kubectl version'): Unable to connect to the server: getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1alpha1, plugin returned version client.authentication.k8s.io/v1beta1

2022-03-01 10:15:19 [ℹ]  cluster should be functional despite missing (or misconfigured) client binaries
2022-03-01 10:15:19 [✔]  EKS cluster "chuck-dev" in "us-east-1" region is ready
```

**How to reproduce it?**
1. ensure `aws` credentials are exported (i.e. `export AWS_PROFILE=foo`)
2. create the cluster: `eksctl create cluster --name chuck-dev --region us-east-1 --with-oidc --ssh-access --tags team=REDACTED,ManagedBy=true --version 1.21 --zones us-east-1a,us-east-1c,us-east-1f,us-east-1b --nodes 4`

**Logs**
Please see:

https://gist.github.com/chazdnato/cf9c20437631a2c3ddff0446534b09d8

**Anything else we need to know?**
Mac OS 12.2.1
eksctl 0.85.0 from homebrew
using `aws sso login`

**Versions**
```
$ eksctl info
eksctl version: 0.85.0
kubectl version: v1.23.4
OS: darwin
```

**Workaround**

If I edit `~/.kube/config` and, in the eksctl created stanzas, replace `client.authentication.k8s.io/v1alpha1` with `client.authentication.k8s.io/v1beta1` , the `kubectl` client works as expected.

```
❯ kubectl get nodes
Unable to connect to the server: getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1alpha1, plugin returned version client.authentication.k8s.io/v1beta1
❯ grep v1alpha1 ~/.kube/config
      apiVersion: client.authentication.k8s.io/v1alpha1
❯ sed -ie 's/v1alpha1/v1beta1/g' ~/.kube/config
❯ kubectl get nodes
NAME                             STATUS   ROLES    AGE    VERSION
ip-192-168-101-54.ec2.internal   Ready    <none>   5m4s   v1.21.5-eks-9017834
ip-192-168-14-2.ec2.internal     Ready    <none>   5m6s   v1.21.5-eks-9017834
ip-192-168-61-107.ec2.internal   Ready    <none>   5m7s   v1.21.5-eks-9017834
ip-192-168-93-70.ec2.internal    Ready    <none>   5m4s   v1.21.5-eks-9017834
```

**Comment by aclevername** [comment] 2022-03-01 17:17
Hey @chazdnato this looks like a duplicate of https://github.com/weaveworks/eksctl/issues/4031. Can you try with `0.86.0-rc0` and see if you can reproduce it? (you will need to recreate the kubeconfig for the API vesion change to propogate). Going to close this issue as I'd rather any follow up happened in https://github.com/weaveworks/eksctl/issues/4031 :smile: thanks!

**Closed by aclevername** 2022-03-01 17:17 UTC
Labels: kind/bug

**Comment by chazdnato** [comment] 2022-03-01 17:22
My apologies! I was looking at open tickets only. I'll try updating to `0.86.0-rc0`

Cheers!

**Comment by chazdnato** [comment] 2022-03-01 18:23
p.s. `0.86.0-rc0` does what is expected, thanks for the quick responses and fix!
