### ISSUE TITLE
Nodes not joining cluster

### ISSUE THREAD

**Issue by mdesanti** [weaveworks/eksctl#265] opened 2018-10-16 12:35 UTC
**What happened?**
When creating a cluster with eksclt nodes never join. The command ends up exiting with a timeout error. If I run `kubectl get nodes` I get `No resources found.`

**What you expected to happen?**
The nodes should be able to join the cluster and I should be able to see them using kubectl.

**How to reproduce it?**
Run `eksctl create cluster --zones=us-east-1a,us-east-1b,us-east-1a` and wait.

**Anything else we need to know?**
No

**Versions**
*ekscvtl version*: `2018-10-15T10:49:51-03:00 [ℹ]  versionInfo = map[string]string{"builtAt":"2018-10-11T09:40:22Z", "gitCommit":"e5d862ed37e616ad712bbefb847612514f85f0dc", "gitTag":"0.1.6"}`

*uname -a*: `Darwin atgvm 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:13:31 PDT 2017; root:xnu-3789.60.24~4/RELEASE_X86_64 x86_64`

*kubectl version*: `Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:03:09Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}`

**Logs**
https://gist.github.com/mdesanti/112036e9cf1d66873c8c1d87465a2e4b

**Comment by errordeveloper** [comment] 2018-10-20 12:28
@mdesanti as discussed on Slack, it looks like you have two issue related to networking.

1. nodes not joining the cluster inside of the VPC
2. you cannot SSH to any of the nodes from either your machine or another EC2 instance

Do you have any updates since we spoke?

I have double checked, and confirmed that SSH is fully functional, there are no issues with keys or SG ingress.

**Comment by errordeveloper** [comment] 2018-10-27 09:38
I'm gonna close this, as there is not enough evidence to prove this is somehow reproducible. I believe there is an issue at the account level of some sort.

**Closed by errordeveloper** 2018-10-27 09:38 UTC
Labels: under investigation
