### ISSUE TITLE
eksctl EKS cluster creation fails with `dial tcp 3.217.2.141:443: i/o timeout` error

### ISSUE THREAD

**Issue by ajit-aws** [weaveworks/eksctl#5523] opened 2022-07-20 16:28 UTC
I am using eksctl version: 0.105.0

when I create cluster using eksctl on ec2 user-data in us-east-1 region, I am intermittently getting error cluster creation stack failed to complete and it does not proceed to sub-task stack creation. Checking at cloudformation stack, I see that the stack was created successfully.

Following is the command and output of the command

 eksctl create cluster --name GuardDuty-Demo --region us-east-1 --zones us-east-1a,us-east-1b,us-east-1c --with-oidc --ssh-access --ssh-public-key guardduty-demo-key --managed
2022-07-20 15:15:30 [ℹ]  eksctl version 0.105.0
2022-07-20 15:15:30 [ℹ]  using region us-east-1
2022-07-20 15:15:30 [ℹ]  subnets for us-east-1a - public:192.168.0.0/19 private:192.168.96.0/19
2022-07-20 15:15:30 [ℹ]  subnets for us-east-1b - public:192.168.32.0/19 private:192.168.128.0/19
2022-07-20 15:15:30 [ℹ]  subnets for us-east-1c - public:192.168.64.0/19 private:192.168.160.0/19
2022-07-20 15:15:30 [ℹ]  nodegroup "ng-8873e38a" will use "" [AmazonLinux2/1.22]
2022-07-20 15:15:30 [ℹ]  using EC2 key pair %!q(*string=<nil>)
2022-07-20 15:15:30 [ℹ]  using Kubernetes version 1.22
2022-07-20 15:15:30 [ℹ]  creating EKS cluster "GuardDuty-Demo" in "us-east-1" region with managed nodes
2022-07-20 15:15:30 [ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial managed nodegroup
2022-07-20 15:15:30 [ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-east-1 --cluster=GuardDuty-Demo'
2022-07-20 15:15:30 [ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "GuardDuty-Demo" in"us-east-1"
2022-07-20 15:15:30 [ℹ]  CloudWatch logging will not be enabled for cluster "GuardDuty-Demo" in "us-east-1"
2022-07-20 15:15:30 [ℹ]  you can enable it with 'eksctl utils update-cluster-logging --enable-types={SPECIFY-YOUR-LOG-TYPES-HERE (e.g. all)} --region=us-east-1 --cluster=GuardDuty-Demo'
2022-07-20 15:15:30 [ℹ]
2 sequential tasks: { create cluster control plane "GuardDuty-Demo",
    2 sequential sub-tasks: {
        4 sequential sub-tasks: {
            wait for control plane to become ready,
            associate IAM OIDC provider,
            2 sequential sub-tasks: {
                create IAM role for serviceaccount "kube-system/aws-node",
                create serviceaccount "kube-system/aws-node",
            },
            restart daemonset "kube-system/aws-node",
        },
        create managed nodegroup "ng-8873e38a",
    }
}
2022-07-20 15:15:30 [ℹ]  building cluster stack "eksctl-GuardDuty-Demo-cluster"
2022-07-20 15:15:31 [ℹ]  deploying stack "eksctl-GuardDuty-Demo-cluster"
2022-07-20 15:16:01 [ℹ]  waiting for CloudFormation stack "eksctl-GuardDuty-Demo-cluster"
2022-07-20 15:16:31 [ℹ]  waiting for CloudFormation stack "eksctl-GuardDuty-Demo-cluster"
2022-07-20 15:17:31 [ℹ]  waiting for CloudFormation stack "eksctl-GuardDuty-Demo-cluster"
2022-07-20 15:18:31 [ℹ]  waiting for CloudFormation stack "eksctl-GuardDuty-Demo-cluster"
2022-07-20 15:19:31 [ℹ]  waiting for CloudFormation stack "eksctl-GuardDuty-Demo-cluster"
2022-07-20 15:20:31 [ℹ]  waiting for CloudFormation stack "eksctl-GuardDuty-Demo-cluster"
2022-07-20 15:21:31 [ℹ]  waiting for CloudFormation stack "eksctl-GuardDuty-Demo-cluster"
2022-07-20 15:22:31 [ℹ]  waiting for CloudFormation stack "eksctl-GuardDuty-Demo-cluster"
2022-07-20 15:23:31 [ℹ]  waiting for CloudFormation stack "eksctl-GuardDuty-Demo-cluster"
2022-07-20 15:24:31 [ℹ]  waiting for CloudFormation stack "eksctl-GuardDuty-Demo-cluster"
2022-07-20 15:25:32 [ℹ]  waiting for CloudFormation stack "eksctl-GuardDuty-Demo-cluster"
2022-07-20 15:26:32 [ℹ]  waiting for CloudFormation stack "eksctl-GuardDuty-Demo-cluster"
2022-07-20 15:27:02 [!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
2022-07-20 15:27:02 [ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-east-1 --name=GuardDuty-Demo'
2022-07-20 15:27:02 [✖]  error creating Clientset: getting list of API resources for raw REST client: Get "https://35CD5D91C857E22217E7137431B72F5F.gr7.us-east-1.eks.amazonaws.com/api?timeout=32s": dial tcp 3.217.2.141:443: i/o timeout
Error: failed to create cluster "GuardDuty-Demo"
Jul 20 15:27:02 cloud-init[3373]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
Jul 20 15:27:02 cloud-init[3373]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Jul 20 15:27:02 cloud-init[3373]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
ci-info: no authorized ssh keys fingerprints found for user ec2-user.
Cloud-init v. 19.3-45.amzn2 finished at Wed, 20 Jul 2022 15:27:02 +0000. Datasource DataSourceEc2.  Up 808.75 seconds

Attached is the cloudformation stack status which completed with no errors
<img width="1153" alt="Screen Shot 2022-07-20 at 12 27 15 PM" src="https://user-images.githubusercontent.com/71732283/180034417-cf479ef2-4d0a-4957-8b26-8dc82cd4f6ca.png">

Let me know how should we fix this intermittent issue.

**Comment by nikimanoledaki** [comment] 2022-07-21 15:10
Hi! I just used the command that you shared with us and the cluster was created successfully. I was not able to reproduce the error. 😕 

How frequently do you come across this issue? Did it start appearing recently?

`error creating Clientset` indicates that it fails to create the Clientset with which to connect to the EKS cluster ([here](https://github.com/weaveworks/eksctl/blob/2298d7ea2fb6ea5387503787312cd1de2f90a225/pkg/kubernetes/client.go#L106)). This relies on your local kubeconfig. 

`i/o timeout` indicates a networking issue, so I suggest having a look at whether this is a firewall/vpn issue.

Unfortunately, I'm not sure that there is much we can do from the side of eksctl 😕

**Comment by ajit-aws** [comment] 2022-07-21 15:24
You are right, it is not easily reproducible, it occurs around 1 out of 10 times. If you look at the command line output, at 2022-07-20 15:27:02 it shows cloudformation stack was not completed successfully and to look at cloudformation logs for error. If you look at the screenshot of the cloudformation stack, it was completed successfully so I am not sure why eksctl is giving error and where do I check for error.

**Comment by readybuilderone** [comment] 2022-08-26 09:50
I met the same issue, any update?

**Comment by nikimanoledaki** [comment] 2022-08-26 09:59
Hi, we have come across this issue with the Kube API being unreachable in our CI as well though it happens quite rarely. It is in our backlog to investigate this further, though it is hard to reproduce. Please bear with us while we try to get to the bottom of this :)

**Comment by ehousey** [comment] 2022-09-01 17:40
I am also seeing this - never before today but 3/3 attempts reproduced it. I noticed this morning that I could not start some of my instances right away due to a capacity problem on the AWS-side. Eventually I was able to start them.
But, I am not able to deploy an EKS cluster. The same error message keeps appearing

022-09-01 17:27:28 [ℹ]  waiting for CloudFormation stack "eksctl-test-eks-cluster"
2022-09-01 17:27:59 [!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
2022-09-01 17:27:59 [ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-east-1 --name=test-eks'
2022-09-01 17:27:59 [✖]  error creating Clientset: getting list of API resources for raw REST client: Get "https://<xxxxxxx>.gr7.us-east-1.eks.amazonaws.com/api?timeout=32s": dial tcp <xx.yy.zz.aa>:443: i/o timeout

The first CF stack completed successfully.

**Comment by ehousey** [comment] 2022-09-01 19:14
> I am also seeing this - never before today but 3/3 attempts reproduced it. I noticed this morning that I could not start some of my instances right away due to a capacity problem on the AWS-side. Eventually I was able to start them. But, I am not able to deploy an EKS cluster. The same error message keeps appearing
> 
> 022-09-01 17:27:28 [ℹ] waiting for CloudFormation stack "eksctl-test-eks-cluster" 2022-09-01 17:27:59 [!] 1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console 2022-09-01 17:27:59 [ℹ] to cleanup resources, run 'eksctl delete cluster --region=us-east-1 --name=test-eks' 2022-09-01 17:27:59 [✖] error creating Clientset: getting list of API resources for raw REST client: Get "https://.gr7.us-east-1.eks.amazonaws.com/api?timeout=32s": dial tcp <xx.yy.zz.aa>:443: i/o timeout
> 
> The first CF stack completed successfully.



Update....on the 5th attempt, the cluster created successfully. This appears to be an AWS-related issue.

**Comment by dduenas** [comment] 2022-09-02 13:30
+1, i read that this is because ec2 instance type availability in the desired zone... it failed yesterday for me, and today is working.

**Comment by Himangini** [comment] 2022-09-12 08:54
Closing this since it seems like an AWS-related issue. Please feel free to reopen if these timeout errors become more frequent.

**Closed by Himangini** 2022-09-12 08:54 UTC
Labels: kind/bug, priority/important-longterm, needs-investigation
