### ISSUE TITLE
eksctl upgrade nodegroup created from console

### ISSUE THREAD

**Issue by cdenneen** [weaveworks/eksctl#2698] opened 2020-10-01 19:35 UTC
**What happened?**
In version 0.28.1 you cannot upgrade a nodegroup that wasn't created via `eksctl` because it does not have a stack to perform the update on.

**What you expected to happen?**
In version 0.24.0 you could upgrade a nodegroup via `eksctl` even if it wasn't created via `eksctl` (no stack)
I expect if a stack can't be found it will use the API call to upgrade the nodegroup as it did in 0.24.0

**Running 0.28.1**
```
❯ eksctl upgrade nodegroup --name testing-nodegroup --cluster apss-use1-c1
Error: error fetching nodegroup template: describing CloudFormation stack "eksctl-apss-use1-c1-nodegroup-testing-nodegroup": ValidationError: Stack with id eksctl-apss-use1-c1-nodegroup-testing-nodegroup does not exist
	status code: 400, request id: 
```
**Running 0.24.0**
```
❯ brew unlink eksctl
Unlinking /usr/local/Cellar/eksctl/0.28.1... 3 symlinks removed
❯ brew link eksctl@0.24.0
Linking /usr/local/Cellar/eksctl@0.24.0/0.24.0... 3 symlinks created
❯ eksctl version
0.24.0
❯ eksctl upgrade nodegroup --name testing-nodegroup --cluster apss-use1-c1 --kubernetes-version 1.16
[ℹ]  upgrading nodegroup to release version 1.16.13-20200921
Error: timed out waiting for nodegroup update to complete: context deadline exceeded
```

The timeout I think needs to be fixed but the upgrade is successful

**Comment by michaelbeaumont** [comment] 2020-10-29 10:12
Thanks @cdenneen, I'm going to track this in #2174

**Comment by michaelbeaumont** [comment] 2020-10-29 10:13
Duplicate of #2174

**Closed by michaelbeaumont** 2020-10-29 10:13 UTC
Labels: kind/bug, priority/important-longterm
