### ISSUE TITLE
eksctl fix to support ARM and GPU instances

### ISSUE THREAD

**Issue by kdaula** [weaveworks/eksctl#4865] opened 2022-03-01 16:37 UTC
story comment https://github.com/weaveworks/eksctl/issues/4865#issuecomment-1068986514

---
eksctl currently treats ARM and GPU instances as mutually exclusive, and this doesnt hold up with the addition of the g5g instances. We are blocked on them fixing their current logic for g5g instances, because their current implementation leads to inconsistent behavior while resolving the AMI SSM parameters

**Comment by aclevername** [comment] 2022-03-01 16:56
Thanks for opening the issue @kdaula . I think this is the cause of that: https://github.com/weaveworks/eksctl/blob/ffed567d78deb481c9ba9411c5575db110e20bfa/pkg/ami/ssm_resolver.go#L119-L126

we should update this code to allow the combination of ARM and GPU :smile:

**Comment by Himangini** [comment] 2022-03-15 14:21
@aclevername will fill out the feature request template here

**Comment by aclevername** [comment] 2022-03-16 10:47
### Description
AWS support arm and x86 instance types, as well as GPU accelerated types. When eksctl attempts to resolve the AMI to use for a nodegroup we check to see wether the instance it an ARM or a GPU type. AWS recently introduces new ARM GPU instance types, e.g. `r6g.medium`. This story is to add support for those instance types in eksctl.

### Scope
- Update our AMI querying logic to support ARM GPU instance types

### User story
As a user of eksctl I want to be able to create nodegroups on ARM GPU instance types

### Acceptance Criteria
Given an existing EKS cluster
When I run `eksctl create nodegroup --instance-type r6g.medium`
Then it should create the nodegroup with an AMI that is suitable for an ARM GPU instance type

### Technical Notes
As pointed out by @arnaldo2792 we need to update the code here:
https://github.com/weaveworks/eksctl/blob/ffed567d78deb481c9ba9411c5575db110e20bfa/pkg/ami/auto_resolver.go#L78-L94

and here:
https://github.com/weaveworks/eksctl/blob/ffed567d78deb481c9ba9411c5575db110e20bfa/pkg/ami/ssm_resolver.go#L119-L126

**Comment by aclevername** [comment] 2022-04-01 10:39
After chatting with @kdaula I think this story is incorrect. https://github.com/weaveworks/eksctl/issues/4916 will add support for ARM GPU Managed nodegroups. Unmanagd nodegroup support for ARM GPU nodes does not currently exist, there is no AMI you can query to fetch for AL2/Ubuntu. Until this is added we can't add support.

This story should change instead to error out early (we currently error when deploying the nodegroup) when an ARM GPU instance type is provided for unmanaged nodegroups. We could add a log msg hinting them towards bottlerocket managed as an alternative.

cc @Himangini I'm going to move this back to refinement since the desired outcome has changed

**Comment by Himangini** [comment] 2022-04-13 13:11
We need to do
- For MNG, allow the combination of ARM and GPU here 
As pointed out by @arnaldo2792 we need to update the code here:
https://github.com/weaveworks/eksctl/blob/ffed567d78deb481c9ba9411c5575db110e20bfa/pkg/ami/auto_resolver.go#L78-L94

and here:
https://github.com/weaveworks/eksctl/blob/ffed567d78deb481c9ba9411c5575db110e20bfa/pkg/ami/ssm_resolver.go#L119-L126

- For UMNG, 
   - we need to investigate if this is supported
   - if it isn't supported then fail with an error to notify that this isn't supported.

**Comment by Skarlso** [comment] 2022-04-22 07:33
I found no AMI for UMNG, which combines ARM + GPU. So we'll error early in that case.

**Comment by Skarlso** [comment] 2022-04-22 11:53
Also, this issue will not work until https://github.com/awslabs/amazon-eks-ami/issues/853 amazon eks ami supports downloading and tagging ARM GPU instances for us to use.

**Comment by Skarlso** [comment] 2022-05-25 14:00
https://github.com/weaveworks/eksctl/pull/5059 To link again the PR which fixes support and is in review.

**Comment by Himangini** [comment] 2022-05-30 11:36
Closed by #5059

**Closed by Himangini** 2022-05-30 11:36 UTC
Labels: kind/feature, area/nodegroup, needs-investigation, bottlerocket
