### ISSUE TITLE
creating cluster with existing SG

### ISSUE THREAD

**Issue by rampatnaik** [weaveworks/eksctl#1332] opened 2019-09-14 00:42 UTC
**Why do you want this feature?**
I am using eksctl to create my cluster 
we use terraform for SG and Networking/SG group create the id 
and we need to attach the existing SG  while creating the cluster

**What feature/behavior/change do you want?**
eksctl create cluster -f cluster.yaml
1. I wanted to attach the existing SG and 
2. I wanted to add tags while creating cluster
key       = "kubernetes.io/role/internal-elb"
value     = "1"

**Comment by martina-if** [comment] 2020-09-15 13:38
related to #1551

**Comment by michaelbeaumont** [comment] 2021-01-18 16:50
Duplicate of https://github.com/weaveworks/eksctl/issues/1551

**Closed by michaelbeaumont** 2021-01-18 16:50 UTC
Labels: kind/feature, priority/backlog
