### ISSUE TITLE
Feature Request: Inconsistency between EKS Management Tools i.e. eksctl, aws cli and management console when it comes to managed NodeGroup

### ISSUE THREAD

**Issue by mohalone911** [weaveworks/eksctl#1680] opened 2019-12-18 16:37 UTC
**What happened?**
eksctl , aws cli and Management Console are not in sync when creating deleting Managed NodeGroups.

**What you expected to happen?**
No matter which tool I use to create the Managed NodeGroups or to pull the information, the results should be consistent.

**How to reproduce it?**
1, Create an EKS Cluster (1.14 , since we are working with managed NodeGroups)
2, Create a NodeGroup (Managed worker nodegroup) using eksctl 
3, When you list the NodeGroups using eksctl (eksctl get nodegroup --clustername), it lists it fine but aws cli can't list it (aws eks list-nodegroups --clustername)..... shows the list as empty
4, Same thing happens when you create a NodeGroup from the Console or awscli and eksctl can't list it.
5, When you delete a NodeGroup that was created using eksctl FROM the console (i.e. the delete was performed from the console), the NodeGroup gets deleted from the console but the underlying CFN Stack (created using eksctl) and Worker Nodes are still running (expected but not consistent). 

**Anything else we need to know?**
Issue happens when using the new AWS EKS Managed worker nodes feature, which can be managed from the console.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version : [ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.11.1"}
$ kubectl version: 
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b8860f", GitCommit:"b8860f6c40640897e52c143f1b9f011a503d6e46", GitTreeState:"clean", BuildDate:"2019-11-25T00:55:38Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
Not Required.

**Comment by martina-if** [comment] 2020-03-20 14:03
Hi @mohalone911  thank you for reporting this.

There is in fact a discrepancy between the tools. For now, the way eksctl has been designed is that so it can only manage resources created by itself. eksctl can't manage other resources at the moment. This would be very tricky since eksctl has certain assumptions in how resources are created.

We don't consider this a bug as of today. I do agree that it would be quite useful as a feature. If you want, you can create a feature request or change this into one. That would help us prioritize this kind of work.

**Comment by michaelbeaumont** [comment] 2020-10-27 15:20
Duplicate of #2773

**Closed by michaelbeaumont** 2020-10-27 15:20 UTC
Labels: awaiting more information, kind/feature

**Comment by michaelbeaumont** [comment] 2020-10-27 15:52
Duplicate of https://github.com/weaveworks/eksctl/issues/2174

**Comment by benjoyce** [comment] 2024-01-08 23:20
I noticed that after changing the instance type of the ECS nodes eksctl created, the eksctl get nodegroups output shows the old instance types, whereas the AWS UI shows the new instance types.  Is there a way to re-sync?
