### ISSUE TITLE
iam.attachPolicyARNs supersedes iam.withAddonPolicies

### ISSUE THREAD

**Issue by blakestoddard** [weaveworks/eksctl#937] opened 2019-06-25 12:37 UTC
**What happened?**
In a cluster config file, if you define a list of policy ARNs to attach via `iam.attachPolicyARNs` but also define a list of add-on policies via `iam.withAddonPolicies`, `eksctl` will not create and attach the additional add-on policies. This appears to be controlled [here](https://github.com/weaveworks/eksctl/blob/05ec5be50e0cfa9d803e20bf22374fbd51a55579/pkg/cfn/builder/iam.go).

Also of note here is that even though I have included `ImageBuilder: true` and `CloudWatch: true` in `iam.withAddonPolicies`, those policies were not attached to the role even though they are AWS-managed policies.

**What you expected to happen?**
The policies that I list in `iam.attachPolicyARNs` will be attached alongside the add-on policies that I "enable" and expect `eksctl` to create and attach to the node IAM role.

**How to reproduce it?**
Use this config, create your cluster, check the node IAM role that was created:
```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: staging-us-east-1
  region: us-east-1
  version: "1.13"

nodeGroups:
  - name: app-v1
    instanceType: m5.large
    desiredCapacity: 3
    privateNetworking: true
    preBootstrapCommands:
      - "yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm"
      - "systemctl enable amazon-ssm-agent"
      - "systemctl start amazon-ssm-agent"
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      withAddonPolicies:
        ImageBuilder: true # allow r/w access to ECR
        ExternalDNS: true
        CertManager: true
        ALBIngress: true
        CloudWatch: true
        EBS: true
```

You will find the following policies attached to the node role:
- AmazonEC2RoleforSSM
- AmazonEKSWorkerNodePolicy
- AmazonEC2ContainerRegistryReadOnly
- AmazonEKS_CNI_Policy

**Anything else we need to know?**
macOS 10.14.5, `eksctl` installed via Homebrew.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.36"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jicowan** [comment] 2019-06-25 21:09
See https://github.com/weaveworks/eksctl/issues/508#issuecomment-480656537

**Comment by blakestoddard** [comment] 2019-06-25 23:37
That's related, yes, but it doesn't quite cover what I'm getting at here. Also interesting is that even though I don't include `AmazonEC2ContainerRegistryReadOnly` in `iam.attachPolicyARNs`, it is still added to the attached policies list on the role. It seems like the logic controlling these attached policies is all over the board.

**Comment by errordeveloper** [comment] 2019-06-27 13:56
Hi @blakestoddard 👋 

So at the moment, if you don't specify anything under `iam`, you will get the minimum policies required for a functional cluster, i.e.:

- `arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy`
- `arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy`
- `arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly`

You can use any of our canned policies through `iam.withAddonPolicies`. Please note that keys are always lower case. We are currently working on new documentation website, which will show correct names of these and other keys.
Anything you add in `iam.withAddonPolicies` gets appended to the instance role.

If you would like to append an existing custom policy - use `iam.attachPolicyARNs`.

If you would like to override all what we provide, you should use `iam.instanceRoleARN`. If you'd like to avoid any calls to IAM APIs, e.g. in case you don't have permission, you can also set `iam.instanceProfileARN`.

Hope this answers your question, but I'm going to keep it open until it's address in the docs.

**Comment by blakestoddard** [comment] 2019-06-27 15:08
> Please note that keys are always lower case. We are currently working on new documentation website, which will show correct names of these and other keys.

Ah! Awesome!

---

I know that this tool is new and development is still actively on-going, I just wanted to make sure this wasn't a bug. 👌

**Comment by njgraham** [comment] 2019-10-04 20:55
I'm seeing the same behaviour I think.  I want to be able to use the canned policies and also add my own.  But, `attachPolicyARNs` seems to override what I've added with `withAddonPolicies` (instead of appending).

So, I guess the workaround is to manually add all the policies that are normally added by the "canned" ones using `attachPolicyARNs`?

That would mean I need to replicate what this does in a new custom policy so I can include it in `attachPolicyARNs` also.
```
      withAddonPolicies:
        autoScaler: true
```

**Comment by MartinEmrich** [comment] 2019-10-15 15:14
Can confirm this with eksctl 0.7.0:
If I use `attachPolicyARNs`, both AmazonEKSWorkerNodePolicy and AmazonEKS_CNI_Policy are missing.

Thus, this gets me the desired result:

```
iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::xxxxxxx:my_custom_policy_1
        - arn:aws:iam::xxxxxxx:my_custom_policy_2
      withAddonPolicies:
        autoScaler: true
        albIngress: true
```

**Comment by renilthomas** [comment] 2020-01-07 16:41
Tried with eksctl 0.11.1, it worked seamlessly.

**Comment by github4es** [comment] 2020-03-12 18:54
Is there a list of what these are and what they do?
```
withAddonPolicies:
        ImageBuilder: true # allow r/w access to ECR
        ExternalDNS: true
        CertManager: true
        ALBIngress: true
        CloudWatch: true
```

**Comment by vpuria** [comment] 2020-04-12 18:53
> Is there a list of what these are and what they do?
> 
> ```
> withAddonPolicies:
>         ImageBuilder: true # allow r/w access to ECR
>         ExternalDNS: true
>         CertManager: true
>         ALBIngress: true
>         CloudWatch: true
> ```

Do we have an answer for this yet ?

**Comment by TBBle** [comment] 2020-06-15 09:23
Contrasting with @errordeveloper 's comment above, and matching @MartinEmrich 's comment, the [docs](https://eksctl.io/usage/iam-policies/#attaching-policies-by-arn) say:
> If a nodegroup includes the `attachPolicyARN`s it must also include the default node policies, like `AmazonEKSWorkerNodePolicy` and `AmazonEKS_CNI_Policy` in this example.

This is also what [`makeManagedPolicies`](https://github.com/weaveworks/eksctl/blob/bf16e0fbe6a1c01fa76b911928524d18c9625c5e/pkg/cfn/builder/iam_helper.go#L277-L278) does, with the default list in [`iamDefaultNodePolicies`](https://github.com/weaveworks/eksctl/blob/bf16e0fbe6a1c01fa76b911928524d18c9625c5e/pkg/cfn/builder/iam.go#L34-L37), so I'd say this issue can be closed as 'working as intended'. Later in [`makeManagedPolicies`](https://github.com/weaveworks/eksctl/blob/bf16e0fbe6a1c01fa76b911928524d18c9625c5e/pkg/cfn/builder/iam_helper.go#L290-L292) the `AmazonEC2ContainerRegistryReadOnly` is added if not using the `ImageBuilder` Addon Policy, to "preserve existing behaviour for unmanaged nodegroups" since Managed Nodegroups are required to have that policy in their InstanceRole.

----

For @github4es and @vpuria, it might be worth opening a new issue to track the documentation of the `withAddonPolicies` option. They're implemented in [`makeManagedPolicies`](https://github.com/weaveworks/eksctl/blob/bf16e0fbe6a1c01fa76b911928524d18c9625c5e/pkg/cfn/builder/iam_helper.go#L287-L297), [`createRole`](https://github.com/weaveworks/eksctl/blob/bf16e0fbe6a1c01fa76b911928524d18c9625c5e/pkg/cfn/builder/iam_helper.go#L41-L271) and [`addResourcesForNodeGroup`](https://github.com/weaveworks/eksctl/blob/1b20719486c24d4436f60cd911ac89e414865e0c/pkg/cfn/builder/nodegroup.go#L172-L185). They certainly could use some more documentation than the [current list](https://eksctl.io/usage/iam-policies/#supported-iam-add-on-policies). It'd be nice if the docs just listed the relevant policy statement, in fact, although clearly that's extra work for the maintainers if it can't be automated.

**Comment by michaelbeaumont** [comment] 2020-06-24 19:37
Closing for https://github.com/weaveworks/eksctl/issues/2371

**Closed by michaelbeaumont** 2020-06-24 19:37 UTC
Labels: area/aws-iam, area/config-file, kind/docs, kind/help
