### ISSUE TITLE
version: auto broken in cluster update

### ISSUE THREAD

**Issue by autarchprinceps** [weaveworks/eksctl#2461] opened 2020-07-22 08:31 UTC
On eksctl version 0.24.0 when doing a eksctl update cluster with version: auto, we now get a:
`Error: unable to parse version "auto": Invalid character(s) found in major number "auto"`
instead of it updating to the newest supported version.
We had a 1.16 cluster and wanted to go to 1.17, if that makes any difference.

On 0.23 and before this definitively worked with upgrades to 1.16 or below then.

**Comment by michaelbeaumont** [comment] 2020-07-22 11:48
@autarchprinceps Your expected behavior with `"auto"` is that it's updated to the latest version, correct?

**Comment by autarchprinceps** [comment] 2020-07-22 11:59
@michaelbeaumont Yes, and that is how it worked before.

**Comment by michaelbeaumont** [comment] 2020-07-22 12:25
For `0.23.0`, I get the same error.

The `upgrade` command changed with that release (https://github.com/weaveworks/eksctl/pull/2318), although unfortunately this was missing from the release notes, it now takes the version into account when doing `upgrade` (`update` is deprecated). 

Previously, the version entered in the config file was ignored and it simply updated the cluster if possible.
However, `"auto"` was never a valid value for `metadata.version`, if you try to create a cluster with that value, it will fail. Is there a reason you have `metadata.version: auto` set?

**Comment by autarchprinceps** [comment] 2020-07-22 13:12
@michaelbeaumont When doing a cluster update followed by a node group replacement to update the AMI, the update nodegroup told you, that it wouldn't update the ami unless you set the metadata.version to auto. With it set to auto it works correctly for everything, but create.
I looked through the code for version 0.23.0, it literally says so here:
```
if cmd.ClusterConfigFile != "" {
  hint = "metadata.version: auto"
}
logger.Warning("will use version %s for new nodegroup(s), while control plane version is %s; to automatically inherit the version use %q", meta.Version, v, hint)
```
https://github.com/weaveworks/eksctl/blob/5a2b46781ace656930fd3c8b6d91f4cef77ec43f/pkg/ctl/create/utils.go#L48

I cannot find any information, on why you switched form update to upgrade or what it does differently either. Any particular reason, why the API was changed, rather than to just fix issues or add features to update?

**Comment by michaelbeaumont** [comment] 2020-07-22 13:15
That code is only used for node group upgrades, and the `auto` version is intended to be used at the command line.

Which API change are you referring to?

**Comment by autarchprinceps** [comment] 2020-07-22 13:20
@michaelbeaumont Yes, that is what I said, and no, if using the auto in the ClusterConfig yaml, it makes the difference between an AMI Upgrade from the existing 1.15 version to 1.15 latest or to 1.16 latest, both with EKS Master Plane at 1.16. The auto version on the cli is the hint before that, if you don't specify a cluster config, that's why line 47 is there.

As for API, I'm talking about renaming update to upgrade. If that is just a name change for human readers, then it really doesn't matter for this case, whether I ran update or upgrade cluster.

**Comment by michaelbeaumont** [comment] 2020-07-22 13:48
Indeed, I was on mobile, I didn't see the exact lines. I believe that's an oversight in documentation/the original bug here. `"auto"` doesn't make sense as a cluster version, only as a specification of behavior for nodegroup updates. Unfortunately these things have been mixed up in the config in this case. In `0.23.0`, the possibility of using `metadata.version` like this was fixed, likely unintentionally. It will probably be easiest just to add it back.

I only wanted to point out the command rename, it wasn't meant as a criticism.

**Comment by autarchprinceps** [comment] 2020-07-22 14:07
No, it's all fine. No hard feelings here. I would just like to know for certain in this case what would the "official" way be?
We want to use the ClusterConfig as much as possible, and we have it integrated into a GitOps style concept with Pipelines. While running with an older AMI version works astoundingly well, if we switch to a new Kubernetes version on the master plane, we would want to update to latest AMI Build of `new-version`.
I can parse the latest supported version out of eksctl version -o json, but as I explained, it at least used to be the case, that when stating an explicit version in metadata.version, it didn't deploy new nodegroups in that newer version and told you to put auto there instead. If this isn't the way anymore and we need to e.g. put auto someplace else, then that's the way we'll use it.

**Comment by michaelbeaumont** [comment] 2020-07-22 14:18
We'll definitely discuss this and completely specify/document how these versions are specified as soon as possible. For now,  does removing `version: auto` and adding `--version auto` to the `create nodegroup` calls work?

**Comment by autarchprinceps** [comment] 2020-07-23 06:58
Yep, that produces it's own problem: Error: cannot use --version when --config-file/-f is set
So there needs to be some way to specify auto within the ClusterConfig

**Comment by michaelbeaumont** [comment] 2020-07-23 09:33
It'll be fixed in the RC tomorrow/is fixed in master now

**Closed** 2020-08-04 08:59 UTC
Labels: area/config-file, area/general-cli, area/nodegroup, area/upgrades, kind/bug, priority/important-soon
