### ISSUE TITLE
use eksctl to generate config file (based on flags)

### ISSUE THREAD

**Issue by trondhindenes** [weaveworks/eksctl#1873] opened 2020-03-01 16:10 UTC
I wish there was a way to do something like `eksctl create cluster --output <configfile>` instead of actually creating the cluster. The benefit would be a working config file as a starting point, instead of experimenting//trying/failing. At the moment, cmd-line flags are far better documented than the config file, so this would serve as a way to bridge that gap.

**Comment by martina-if** [comment] 2020-03-02 09:27
Hi @trondhindenes, thank you for creating this feature request. This is a duplicate of #633. I will close this but please upvote the original issue so we have more information that helps prioritizing it :) Also feel free to add more information if you feel something is missing. Use cases are always great to have.

duplicate of https://github.com/weaveworks/eksctl/issues/633

**Closed by martina-if** 2020-03-02 09:27 UTC
Labels: kind/feature
