### ISSUE TITLE
[Bug] eksctl update iamserviceaccount is detaching other policies from the IAM role

### ISSUE THREAD

**Issue by CalebRollins** [weaveworks/eksctl#6625] opened 2023-05-19 15:25 UTC
### What were you trying to accomplish?
I am trying to run `eksctl update iamserviceaccount` to attach an additional policy to an IAM role without affecting the policies that are already attached to the role.

### What happened?
The policy was attached to the role, but a different policy that was previously attached to the role was detached. Another policy that was attached to the role remained unaffected. I am able to reproduce this on demand by executing the below command with different policy ARN's.

### How to reproduce it?

This is the command I am running
```
eksctl update iamserviceaccount --name eks-avn-faw-connector-sa --region=us-east-1 --cluster eks-avn-dev-ue1 --attach-policy-arn arn:aws:iam::437521038090:policy/AmazonMSK_eks-faw-connector-sasl-secret-policy --approve --namespace apps-namespace
```

**Logs**
Output of the above command
```
2023-05-19 11:15:44 [ℹ]  1 iamserviceaccount (apps-namespace/eks-avn-faw-connector-sa) was included (based on the include/exclude rules)
2023-05-19 11:15:46 [ℹ]  1 task: { 1 task: { update IAMServiceAccount apps-namespace/eks-avn-faw-connector-sa } }
2023-05-19 11:15:46 [ℹ]  updating policies for IAMServiceAccount apps-namespace/eks-avn-faw-connector-sa
2023-05-19 11:15:47 [ℹ]  waiting for CloudFormation changeset "updating-policy-734ceb28-cdd6-4391-b5f4-a094eccea0a0" for stack "eksctl-eks-avn-dev-ue1-addon-iamserviceaccount-apps-namespace-eks-avn-faw-connector-sa"
2023-05-19 11:16:17 [ℹ]  waiting for CloudFormation changeset "updating-policy-734ceb28-cdd6-4391-b5f4-a094eccea0a0" for stack "eksctl-eks-avn-dev-ue1-addon-iamserviceaccount-apps-namespace-eks-avn-faw-connector-sa"
2023-05-19 11:16:18 [ℹ]  waiting for CloudFormation stack "eksctl-eks-avn-dev-ue1-addon-iamserviceaccount-apps-namespace-eks-avn-faw-connector-sa"
2023-05-19 11:16:48 [ℹ]  waiting for CloudFormation stack "eksctl-eks-avn-dev-ue1-addon-iamserviceaccount-apps-namespace-eks-avn-faw-connector-sa"
```

**Anything else we need to know?**
Running in Powershell on Windows
Installed with chocolatey

**Versions**
eksctl version: 0.141.0
kubectl version: v1.26.1
OS: windows

**Comment by CalebRollins** [comment] 2023-05-23 18:40
Is this the intended behavior of `ekctl update iamserviceaccount`?

[The documentation](https://eksctl.io/usage/iamserviceaccounts/) says "To update a service accounts roles permissions you can run eksctl update iamserviceaccount."

I took that to mean we could use the command to add additional policies without affecting existing policies

**Comment by cPu1** [comment] 2023-05-24 12:34
@CalebRollins, this is the intended behaviour. If you need to add more policies, you'll have to specify all existing policies again in `--attach-policy-arn `. Using a config file will help make it easier.

**Comment by CalebRollins** [comment] 2023-05-24 19:11
Ok, thank you.

**Comment by cPu1** [comment] 2023-05-25 12:02
I'm closing the issue as this is the intended behaviour. Please feel free to open a new issue if you have more questions.

**Closed by cPu1** 2023-05-25 12:02 UTC
Labels: kind/bug
