### ISSUE TITLE
SSH_AUTH_SOCK removed when running git commands

### ISSUE THREAD

**Issue by forsberg** [weaveworks/eksctl#1940] opened 2020-03-16 13:37 UTC
It looks like the code that decides what environment variables to pass on to git, used when trying the experimental `eksctl enable repo` command filters out the SSH_AUTH_SOCK environment variable.

https://github.com/weaveworks/eksctl/blob/191286ead564f30cd4ed75082111353a0d5edf42/pkg/git/git.go#L89

I'm using a Yubikey to store the private part of my ssh key, and filtering out SSH_AUTH_SOCK means this doesn't work at all.

For me, using gpg-agent as ssh-agent, a workaround is to create a `/usr/local/bin/git` with the following contents:

```shell script
#!/bin/sh

if [ -z "$SSH_AUTH_SOCK" ] ; then
   export SSH_AUTH_SOCK=/run/user/$(id -u)/gnupg/S.gpg-agent.ssh
fi

exec /usr/bin/git "$@"
```
But I think the preferred solution is to not filter out SSH_AUTH_SOCK.

**Comment by tckb** [comment] 2020-05-12 13:12
I am facing the same issue. It seems pretty weird to decide which environment variable to pass on to git.  Thanks for the quick solution @forsberg

**Comment by Legion2** [comment] 2020-08-02 14:28
This is still an issue in version `0.25.0`. If I run `eksctl.exe enable repo -f cluster.yaml` on windows 10 I expect git to use the running ssh-agent to authenticate. Instead I'm asked to enter my passphrase. And it not just ask once but multiple times for each git operation.

**Comment by Legion2** [comment] 2020-08-02 14:36
Ok, I think I have a different problem. According to #2083 `SSH_AUTH_SOCK` is now correctly set and this issue should be closed. I will open a new Issue for my problem.

**Comment by michaelbeaumont** [comment] 2021-01-18 21:05
Duplicate of https://github.com/weaveworks/eksctl/issues/2082

**Closed** 2021-01-18 21:05 UTC
Labels: kind/bug, priority/backlog
