### ISSUE TITLE
Remove 1.20 from list of supported versions in eksctl

### ISSUE THREAD

**Issue by vipin-mohan** [weaveworks/eksctl#6152] opened 2023-01-12 21:54 UTC

**Comment by vipin-mohan** [comment] 2023-01-12 21:56
We have removed 1.20 from the EKS console and EKS API (i.e., customers cannot create 1.20 clusters). We must also remove it from eksctl to ensure a consistent customer experience
https://github.com/weaveworks/eksctl/blob/e40e547126eeab7a7c71a87ecd5027da64e1ae0b/pkg/apis/eksctl.io/v1alpha5/types.go#L484-L518

**Comment by Himangini** [comment] 2023-01-17 11:31
dupe of #5522

**Closed** 2023-01-18 12:33 UTC
Labels: kind/feature, priority/critical, roadmap
