### ISSUE TITLE
eksctl utils update-kube-proxy upgrades to broken ecr link

### ISSUE THREAD

**Issue by autarchprinceps** [weaveworks/eksctl#2554] opened 2020-08-18 08:53 UTC
When doing a eksctl utils update-kube-proxy, we get an Image Pull error.
It tries to download kube-proxy:v1.17.9, which does not exist. Official EKS documentation states kube-proxy:v1.17.9-eksbuild.1, which does work.

We are running 0.25.0, which is the latest stable.

**Comment by autarchprinceps** [comment] 2020-08-18 09:00
CoreDNS also states officially that it should use the -eksbuild.1 suffix, but does still pull for 1.6.6 without it, but I wouldn't bet, that it will stay that way.

**Comment by michaelbeaumont** [comment] 2020-08-18 09:06
This is fixed now in `0.26-rc.1` and will be fixed in `0.26`.
Duplicate of #2536, duplicate of #1088

**Comment by michaelbeaumont** [comment] 2020-08-18 09:07
Duplicate of #2536

**Closed** 2020-08-18 09:41 UTC
Labels: kind/bug
