### ISSUE TITLE
When creating a cluster with 1 node group with no node, timeout waiting for coredns to become active.

### ISSUE THREAD

**Issue by tanvp112** [weaveworks/eksctl#4607] opened 2022-01-11 04:49 UTC
When I create an EKS cluster with 1 managed node group with `desiredCapacity` equal to zero, the creation failed with:

```
2022-01-11 11:53:59 [ℹ]  no recommended policies found, proceeding without any IAM
2022-01-11 11:53:59 [ℹ]  creating addon
2022-01-11 12:18:59 [!]  1 error(s) occurred while creating addons
2022-01-11 12:18:59 [✖]  timed out waiting for addon "coredns" to become active, status: "DEGRADED"
```

As a result:
- The status for coredns addon is `degraded`.
- kube-proxy addon was not installed. 
- None of the service account declared under iam.serviceAccounts was created.

This is eksctl version 0.77.

In a separate attempt that create another cluster with NO node group, the creation was successful. This cluster can later add node group with zero `desiredCapacity`. Scale the node count up/down also succeeded with no issue.

**Comment by cPu1** [comment] 2022-01-11 08:23
Can you share your ClusterConfig file? I mainly need to check if you have any managed addons configured.

**Comment by tanvp112** [comment] 2022-01-11 08:44
Sure, here you go.  Let me know if there's anything I could tweak.

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: 
  region: 

addons:
- name: vpc-cni
  version: latest
- name: coredns
  version: latest
- name: kube-proxy
  version: latest

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true

vpc:
  clusterEndpoints:
    privateAccess: true

managedNodeGroups:
- name: spark-00
  amiFamily: Bottlerocket
  instanceType: m6i.2xlarge
  minSize: 0
  maxSize: 48
  desiredCapacity: 0
  privateNetworking: true
```

**Comment by cPu1** [comment] 2022-01-11 11:58
Thanks, I was able to reproduce the issue with your config file. When a managed addon is configured, eksctl waits for it to become active, but since addons (CoreDNS in this case) can only become active when there's a node available to run them, they'll remain in an unscheduled state in a cluster with no nodes. We'll add this to our backlog.

**Comment by aclevername** [comment] 2022-01-12 10:48
I thought this was fixed by https://github.com/weaveworks/eksctl/pull/4332

**Comment by aclevername** [comment] 2022-01-12 10:49
https://github.com/weaveworks/eksctl/pull/4332 addressed the scenario of no nodegroups at all, but not when the nodegroup is scaled to 0. An addition to the work done in this PR should be enough

**Closed** 2022-01-14 13:34 UTC
Labels: kind/bug
