### ISSUE TITLE
Worker nodes not getting attached to the EKS cluster, getting timedout

### ISSUE THREAD

**Issue by ghoshaditya** [weaveworks/eksctl#574] opened 2019-02-24 12:28 UTC
I am using a minimal cluster config, with an existing VPC and both private and public subnets.
But once the worker nodes are up, they do not join the cluster and i get a timeout.
Any reason ?

**Comment by errordeveloper** [comment] 2019-02-25 09:09
It's hard to say what could be the issue, have you looked at kubelet logs? (You will need to enable SSH for that).

**Comment by errordeveloper** [comment] 2019-05-31 11:59
Closing as there is no enough context and the issue is several month old - a lot has changed.

**Closed by errordeveloper** 2019-05-31 11:59 UTC
Labels: awaiting more information, kind/help
